### ISSUE TITLE
org.apache.beam.sdk.metrics.Distribution type metrics throw NPE when saving or publishing

### ISSUE THREAD

**Issue by ClaireMcGinty** [spotify/scio#1029]
NPE is thrown after job completes with stack trace:

```
INFO: Exception in thread "main" java.lang.NullPointerException
INFO: 	at com.spotify.scio.ScioResult.com$spotify$scio$ScioResult$$mkDist$1(ScioResult.scala:112)
INFO: 	at com.spotify.scio.ScioResult$$anonfun$2.apply(ScioResult.scala:123)
INFO: 	at com.spotify.scio.ScioResult$$anonfun$2.apply(ScioResult.scala:121)
INFO: 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
INFO: 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
INFO: 	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
INFO: 	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
INFO: 	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
INFO: 	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
INFO: 	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
INFO: 	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
INFO: 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
INFO: 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
INFO: 	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:245)
INFO: 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
INFO: 	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:245)
INFO: 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
INFO: 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
INFO: 	at com.spotify.scio.ScioResult.getBeamMetrics(ScioResult.scala:121)
INFO: 	at com.spotify.scio.ScioContext$ContextScioResult.getMetrics(ScioContext.scala:384)
INFO: 	at com.spotify.data.counters.ScioResultInvocation$ScioInvocation$.getCountersPart$extension(ScioResultInvocation.scala:23)
INFO: 	at com.spotify.data.counters.package$DataCountersPublisherContext.postMetrics(package.scala:98)
INFO: 	at com.spotify.data.counters.package$DataCountersPublisherContext.closeAndPublishMetrics(package.scala:63)
```

I did some investigating and it seems the offending line is in [getBeamMetrics](https://github.com/spotify/scio/blob/2b643c955fcfad4df7b698583eef1107f1264093/scio-core/src/main/scala/com/spotify/scio/ScioResult.scala#L116) in ScioResult. the "attempted" attribute of Distribution metrics is null, although the "committed" attribute is set to the expected values.

I successfully ran a locally patched version with this modification:

```
  protected def getBeamMetrics: BeamMetrics = {
    require(isCompleted, "Pipeline has to be finished to get metrics.")

    def mkDist(d: bm.DistributionResult): BeamDistribution = {
      val result = Option(d).getOrElse {
        logger.warn("Encountered null DistributionResult. Defaulting to DistributionResult.ZERO")
        DistributionResult.ZERO
      }

      BeamDistribution(result.sum(), result.count(), result.min(), result.max(), result.mean())
    }
    def mkGauge(g: bm.GaugeResult): BeamGauge = BeamGauge(g.value(), g.timestamp())

    val beamCounters = allCounters.map { case (k, v) =>
      BeamMetric(k.namespace(), k.name(), v)
    }
    val beamDistributions = allDistributions.map { case (k, v) =>
      BeamMetric(k.namespace(), k.name(), MetricValue(mkDist(v.attempted), v.committed.map(mkDist)))
    }
    val beamGauges = allGauges.map { case (k, v) =>
      BeamMetric(k.namespace(), k.name(),
        MetricValue(mkGauge(v.attempted), v.committed.map(mkGauge)))
    }
    BeamMetrics(beamCounters, beamDistributions, beamGauges)
  }
```

That said, I'm still not sure why `attempted` is null in the first place for this type of metric. happy to dig in more/open a pull request with that modification

**Comment by ClaireMcGinty** [comment]
oh I think [this Apache Beam doc](https://github.com/apache/beam/blob/master/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowMetrics.java#L158) explains it? in batch jobs only committed results are available?

**Comment by nevillelyh** [comment]
Yeah that's probably why. So expected?

**Comment by ClaireMcGinty** [comment]
Expected, but still an issue for anyone wanting to publish distribution metrics from a batch job (which I assume are a lot more common that streaming jobs). The patch I posted above ^ is probably the least disruptive way to solve it since no re-architecture is required. It doesn't even need a logged warning since it's not actually an error. what do you think?

**Comment by nevillelyh** [comment]
Yeah we should do that then.
So this only affects distribution, but fine with counter and gauge?

**Comment by ClaireMcGinty** [comment]
hmm... looking at the code I think it might affect Gauge as well. I can test that one too and get back to you/include it in pull request

**Comment by ClaireMcGinty** [comment]
ok I was testing out gauges and it doesn't get reported from Dataflow metrics (if you look in Scio's internal metrics map Gauges is just an empty list). The dataflow release notes say this is a [known issue](https://cloud.google.com/dataflow/release-notes/release-notes-java-2) though.

**Comment by ClaireMcGinty** [comment]
https://github.com/spotify/scio/pull/1030
