### ISSUE TITLE
Improve JobTest Typesafety

### ISSUE THREAD

**Issue by jto** [spotify/scio#1079]
Currently the types of input and outputs when using `JobTest` to test pipelines are just inferred from the local context of the test.

See for example `com.spotify.scio.examples.complete.game.HourlyTeamScoreTest` from `scio-examples`:

```scala
JobTest[com.spotify.scio.examples.complete.game.HourlyTeamScore.type]
      .args("--input=in.txt", "--output=dataset.table")
      .input(TextIO("in.txt"), inData)
      .output(BigQueryIO[TeamScoreSums]("dataset.table"))(_ should containInAnyOrder (expected))
      .run()
```

As a consequence, the compiler can't automatically infer the types of inputs and output. In this example removing the explicit type parameter for `BigQueryIO` will cause a compilation error:

```
[error] /Users/julient/Documents/Spotify/scio/scio-examples/src/test/scala/com/spotify/scio/examples/complete/game/HourlyTeamScoreTest.scala:61:44: missing parameter type for expanded function ((x$1: <error>) => x$1.should(containInAnyOrder(expected)))
[error]       .output(BigQueryIO("dataset.table"))(_ should containInAnyOrder (expected))
```

The other consequence is more of a problem IMHO. One could pass values of the wrong type in the test and the code would still compile. For example the following code compiles just fine

```scala
val thisIsWrong: List[Int] = List(1, 2, 3)

  "HourlyTeamScore" should "work" in {
    JobTest[com.spotify.scio.examples.complete.game.HourlyTeamScore.type]
      .args("--input=in.txt", "--output=dataset.table")
      .input(TextIO("in.txt"), inData)
      .output(BigQueryIO[Int]("dataset.table"))(_ should containInAnyOrder (thisIsWrong))
      .run()
  }
```

But it will cause a `java.lang.ClassCastException` when executed.

```
[info] HourlyTeamScoreTest:
[info] HourlyTeamScore
[info] - should work *** FAILED ***
[info]   org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.ClassCastException: com.spotify.scio.examples.complete.game.HourlyTeamScore$TeamScoreSums cannot be cast to java.lang.Integer
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:312)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:206)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:62)
[info]   at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:353)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:335)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:370)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:355)
[info]   at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:420)
[info]   ...
[info]   Cause: java.lang.ClassCastException: com.spotify.scio.examples.complete.game.HourlyTeamScore$TeamScoreSums cannot be cast to java.lang.Integer
[info]   at org.apache.beam.sdk.coders.VarIntCoder.encode(VarIntCoder.java:33)
[info]   at org.apache.beam.sdk.coders.Coder.encode(Coder.java:143)
[info]   at org.apache.beam.sdk.util.CoderUtils.encodeToSafeStream(CoderUtils.java:87)
[info]   at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:71)
[info]   at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:56)
[info]   at org.apache.beam.sdk.util.CoderUtils.clone(CoderUtils.java:150)
[info]   at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.<init>(MutationDetectors.java:113)
[info]   at org.apache.beam.sdk.util.MutationDetectors.forValueWithCoder(MutationDetectors.java:42)
[info]   at org.apache.beam.runners.direct.ImmutabilityCheckingBundleFactory$ImmutabilityEnforcingBundle.add(ImmutabilityCheckingBundleFactory.java:112)
[info]   at org.apache.beam.runners.direct.ParDoEvaluator$BundleOutputManager.output(ParDoEvaluator.java:232)
[info]   ...
```

Theoretically the types of inputs and outputs of a pipeline are statically known. 
It would be nice to provide a safer API that can detect this kind of mistakes at compile time.

**Comment by nevillelyh** [comment]
Related to #575 an ongoing effort.
To do this we have to statically express the IO types of a job? How would you handle variable number of inputs and outputs? With shapeless?

**Comment by jto** [comment]
Yes, the Job type should express the types of the IOs. If possible It'd be nice not to force Shapeless on the end user. Honestly, I have some intuition on how to implement that but nothing concrete...

**Comment by jbx** [comment]
Same status as #1081

**Comment by nevillelyh** [comment]
Not sure if this is worth the effort, @jto can we close?
