### ISSUE TITLE
java.lang.ClassCastException: scala.collection.mutable.HashSet cannot be cast to scala.collection.mutable.TreeSet

### ISSUE THREAD

**Issue by welvet** [spotify/scio#1125]
```
import com.spotify.scio._
import scala.collection.mutable

object HashSetTreeSetCastProblem {

  def main(cmdlineArgs: Array[String]): Unit = {
    val (sc, args) = ContextAndArgs(cmdlineArgs)

    sc.parallelize(Map(1 -> 1))
      .aggregateByKey(mutable.TreeSet[Int]())(_ + _, _ ++ _)
      .map(kv => print(kv))

    sc.close()
  }

}
```

This code producing class cast exception which seems to be related to Kryo serialization / deserialization process. If I replace "explicit" mutable.TreeSet to immutable.TreeSet everything works as expected.

```
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.ClassCastException: scala.collection.mutable.HashSet cannot be cast to scala.collection.mutable.TreeSet
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:312)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:206)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:62)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:297)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:369)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:354)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:419)
	at com.spotify.scio.ScioContext.close(ScioContext.scala:354)
	at example.HashSetTreeSetCast$.main(HashSetTreeSetCast.scala:15)
	at example.HashSetTreeSetCast.main(HashSetTreeSetCast.scala)
Caused by: java.lang.ClassCastException: scala.collection.mutable.HashSet cannot be cast to scala.collection.mutable.TreeSet
	at example.HashSetTreeSetCast$$anonfun$main$1.apply(HashSetTreeSetCast.scala:12)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at com.spotify.scio.util.Functions$$anon$4.com$spotify$scio$util$Functions$$anon$$fold(Functions.scala:58)
	at com.spotify.scio.util.Functions$$anon$4$$anonfun$1.apply(Functions.scala:77)
	at com.spotify.scio.util.Functions$$anon$4$$anonfun$1.apply(Functions.scala:77)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.spotify.scio.util.Functions$$anon$4.mergeAccumulators(Functions.scala:77)
	at com.spotify.scio.util.Functions$$anon$4.mergeAccumulators(Functions.scala:50)
```

Versions:
```
val scioVersion = "0.5.2"
val beamVersion = "2.4.0"
val scalaMacrosVersion = "2.1.0"
```

**Comment by nevillelyh** [comment]
This is probably because kryo doesn't have a specific serializer for mutable.TreeSet. Can you try registering one yourself? Don't think it's something we should fix in Scio.
https://github.com/spotify/scio/wiki/FAQ#how-do-i-use-custom-kryo-serializers

**Comment by nevillelyh** [comment]
Will close for now since it's outside our scope. Feel free to reopen if you have questions.
