### ISSUE TITLE
Flink runner jackson related error

### ISSUE THREAD

**Issue by Zhen-hao** [spotify/scio#1130]
submitting a job to a Flink cluster got the following error. 
I found a similar issue from two years ago:
https://groups.google.com/forum/#!topic/jackson-user/ID4f5GR2G5M

```
java.util.concurrent.CompletionException: org.apache.flink.util.FlinkException: Could not run the jar.
	at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleJsonRequest$6(JarRunHandler.java:90)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.flink.util.FlinkException: Could not run the jar.
	... 9 more
Caused by: org.apache.flink.client.program.ProgramInvocationException: The program caused an error: 
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:93)
	at org.apache.flink.client.program.ClusterClient.getOptimizedPlan(ClusterClient.java:334)
	at org.apache.flink.runtime.webmonitor.handlers.JarActionHandler.getJobGraphAndClassLoader(JarActionHandler.java:87)
	at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleJsonRequest$6(JarRunHandler.java:69)
	... 8 more
Caused by: java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.module.scala.DefaultScalaModule could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:739)
	at org.apache.beam.sdk.options.PipelineOptionsFactory.<clinit>(PipelineOptionsFactory.java:469)
	at com.spotify.scio.ScioContext$.parseArguments(ScioContext.scala:152)
	at io.connecterra.SensorEventStream$.main(SensorEventStream.scala:61)
	at io.connecterra.SensorEventStream.main(SensorEventStream.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:525)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:417)
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:83)
	... 11 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.fasterxml.jackson.module.scala.modifiers.ScalaTypeModifierModule$class.$init$(ScalaTypeModifier.scala:32)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.<init>(DefaultScalaModule.scala:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 25 more

```

**Comment by Zhen-hao** [comment]
the build profile is as follows. The dependency tree is attached.

```
import sbt._
import Keys._

val scioVersion = "0.5.2"
val beamVersion = "2.4.0"
val scalaMacrosVersion = "2.1.0"

lazy val commonSettings = Defaults.coreDefaultSettings ++ Seq(
    organization          := "io.connecterra",
    // Semantic versioning http://semver.org/
    version               := "0.1.0-SNAPSHOT",
    scalaVersion          := "2.11.12",
    scalacOptions         ++= Seq(
        "-Ydelambdafy:inline",
        "-target:jvm-1.8",
        "-deprecation",
        "-feature",
        "-unchecked"),
    javacOptions          ++= Seq("-source", "1.8",
        "-target", "1.8")
)

lazy val paradiseDependency =
    "org.scalamacros" % "paradise" % scalaMacrosVersion cross CrossVersion.full
lazy val macroSettings = Seq(
    libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value,
    addCompilerPlugin(paradiseDependency)
)

lazy val noPublishSettings = Seq(
    publish := {},
    publishLocal := {},
    publishArtifact := false
)

lazy val kafka = Seq(
    "org.apache.beam" % "beam-sdks-java-io-kafka" % "2.4.0",
    "org.apache.kafka" % "kafka-clients" % "1.1.0"
)

lazy val avro = Seq(
    "org.apache.avro" % "avro" % "1.8.2",
    "com.sksamuel.avro4s" % "avro4s-core_2.11" % "1.8.3"
)


lazy val flink = Seq(
    "org.apache.beam" %% "beam-runners-flink" % "2.4.0",
    "org.apache.flink" %% "flink-clients" % "1.4.0",
    "org.apache.flink" % "flink-core" % "1.4.0"
)


lazy val root: Project = Project(
    "streaming-test",
    file(".")
).settings(
    commonSettings ++ macroSettings ++ noPublishSettings,
    description := "connecterra streaming test",
    libraryDependencies ++= Seq(
        "com.spotify" %% "scio-core" % scioVersion,
        "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.9.2",
        "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.2",
        "org.slf4j" % "slf4j-simple" % "1.7.25"
    ) ++ kafka ++ avro ++ flink
).enablePlugins(PackPlugin)

lazy val repl: Project = project.in(
    file(".repl")
).settings(
    commonSettings ++ macroSettings ++ noPublishSettings,
    description := "Scio REPL for streaming",
    libraryDependencies ++= Seq(
        "com.spotify" %% "scio-repl" % scioVersion
    ),
    mainClass in Compile := Some("com.spotify.scio.repl.ScioShell")
).dependsOn(
    root
)

enablePlugins(AssemblyPlugin)

assemblyShadeRules in assembly := Seq(
    ShadeRule.rename("org.objenesis.**" -> s"org.objenesis_shaded.@1").inAll,
    ShadeRule.rename("org.objenesis.**" -> s"org.objenesis_shaded.@1").inAll,
    ShadeRule.rename("com.esotericsoftware.kryo.**" ->
        s"com.esotericsoftware.kryo_shaded.@1"
    ).inAll,
    ShadeRule.rename("com.twitter.chill.**" -> s"com.twitter.chill_shaded.@1").inAll
)


assemblyMergeStrategy in assembly := {
    
    case x if Assembly.isConfigFile(x) =>
        MergeStrategy.concat
    case PathList(ps @ _*) if Assembly.isReadme(ps.last) || Assembly.isLicenseFile(ps.last) =>
        MergeStrategy.rename
    case PathList("META-INF", xs @ _*) =>
        (xs map {_.toLowerCase}) match {
            case ("manifest.mf" :: Nil) | ("index.list" :: Nil) | ("dependencies" :: Nil) =>
                MergeStrategy.filterDistinctLines
            case ps @ (x :: xs) if ps.last.endsWith(".sf") || ps.last.endsWith(".dsa") =>
                MergeStrategy.discard
            case "plexus" :: xs =>
                MergeStrategy.discard
            case "services" :: xs =>
                MergeStrategy.filterDistinctLines
            case ("spring.schemas" :: Nil) | ("spring.handlers" :: Nil) =>
                MergeStrategy.filterDistinctLines
            case _ => MergeStrategy.last
        }
    case _ => MergeStrategy.last
        
}

```
[dependent-tree.txt](https://github.com/spotify/scio/files/1948003/dependent-tree.txt)

**Comment by Zhen-hao** [comment]
If I add 
`ShadeRule.rename("com.fasterxml.jackson.**" -> s"com.fasterxml.jackson_shaded.@1").inAll`
to assemblyShadeRules, I get this error

```
The program finished with the following exception:

java.lang.NoSuchMethodError: com.google.protobuf.Internal.checkNotNull(Ljava/lang/Object;)Ljava/lang/Object;
	at com.google.protobuf.MapField$MutatabilityAwareMap.put(MapField.java:334)
	at org.apache.beam.model.pipeline.v1.RunnerApi$Components$Builder.putCoders(RunnerApi.java:1920)
	at org.apache.beam.runners.core.construction.SdkComponents.registerCoder(SdkComponents.java:184)
	at org.apache.beam.runners.core.construction.PCollectionTranslation.toProto(PCollectionTranslation.java:36)
	at org.apache.beam.runners.core.construction.SdkComponents.registerPCollection(SdkComponents.java:138)
	at org.apache.beam.runners.core.construction.PTransformTranslation.toProto(PTransformTranslation.java:173)
	at org.apache.beam.runners.core.construction.SdkComponents.registerPTransform(SdkComponents.java:86)
	at org.apache.beam.runners.core.construction.PipelineTranslation$1.visitPrimitiveTransform(PipelineTranslation.java:87)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:668)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:660)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:660)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.access$600(TransformHierarchy.java:311)
	at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:245)
	at org.apache.beam.sdk.Pipeline.traverseTopologically(Pipeline.java:458)
	at org.apache.beam.runners.core.construction.PipelineTranslation.toProto(PipelineTranslation.java:59)
	at org.apache.beam.runners.core.construction.PipelineTranslation.toProto(PipelineTranslation.java:53)
	at org.apache.beam.runners.flink.FlinkPipelineExecutionEnvironment.translate(FlinkPipelineExecutionEnvironment.java:91)
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:110)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:297)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:369)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:354)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:419)
	at com.spotify.scio.ScioContext.close(ScioContext.scala:354)
	at io.connecterra.SensorEventStream$.main(SensorEventStream.scala:81)
	at io.connecterra.SensorEventStream.main(SensorEventStream.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:525)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:417)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:396)
	at org.apache.flink.client.CliFrontend.executeProgram(CliFrontend.java:802)
	at org.apache.flink.client.CliFrontend.run(CliFrontend.java:282)
	at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:1054)
	at org.apache.flink.client.CliFrontend$1.call(CliFrontend.java:1101)
	at org.apache.flink.client.CliFrontend$1.call(CliFrontend.java:1098)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1866)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1098)
```

**Comment by Zhen-hao** [comment]
It could be a Beam or Flink bug?
https://stackoverflow.com/questions/39288943/apache-beam-with-flink-backend-throws-nosuchmethoderror-on-calls-to-protobuf-jav

**Comment by Zhen-hao** [comment]
solved by manually adding 
`"com.google.protobuf" % "protobuf-java" % "3.4.0"`
and the merging strategy
```scala
case m if m.toLowerCase.contains("com.google.protobuf") =>
        MergeStrategy.first
```

Now the final working build profile is this

```scala
import sbt._
import Keys._

val scioVersion = "0.5.2"
val beamVersion = "2.4.0"
val scalaMacrosVersion = "2.1.0"

lazy val commonSettings = Defaults.coreDefaultSettings ++ Seq(
    organization          := "io.connecterra",
    // Semantic versioning http://semver.org/
    version               := "0.1.0-SNAPSHOT",
    scalaVersion          := "2.11.12",
    scalacOptions         ++= Seq(
        "-Ydelambdafy:inline",
        "-target:jvm-1.8",
        "-deprecation",
        "-feature",
        "-unchecked"),
    javacOptions          ++= Seq("-source", "1.8",
        "-target", "1.8")
)

lazy val paradiseDependency =
    "org.scalamacros" % "paradise" % scalaMacrosVersion cross CrossVersion.full
lazy val macroSettings = Seq(
    libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value,
    addCompilerPlugin(paradiseDependency)
)

lazy val noPublishSettings = Seq(
    publish := {},
    publishLocal := {},
    publishArtifact := false
)

lazy val kafka = Seq(
    "org.apache.beam" % "beam-sdks-java-io-kafka" % "2.4.0",
    "org.apache.kafka" % "kafka-clients" % "1.1.0"
)

lazy val avro = Seq(
    "org.apache.avro" % "avro" % "1.8.2",
    "com.sksamuel.avro4s" % "avro4s-core_2.11" % "1.8.3"
)


lazy val flink = Seq(
    "org.apache.beam" %% "beam-runners-flink" % "2.4.0",
    "org.apache.flink" %% "flink-clients" % "1.4.0",
    "org.apache.flink" % "flink-core" % "1.4.0"
)


lazy val root: Project = Project(
    "streaming-test",
    file(".")
).settings(
    commonSettings ++ macroSettings ++ noPublishSettings,
    description := "connecterra streaming test",
    libraryDependencies ++= Seq(
        "com.spotify" %% "scio-core" % scioVersion,
        "com.google.protobuf" % "protobuf-java" % "3.4.0",
        "org.slf4j" % "slf4j-simple" % "1.7.25"
    ) ++ kafka ++ avro ++ flink
).enablePlugins(PackPlugin)

//envVars in root := Map("GOOGLE_APPLICATION_CREDENTIALS" -> "credentials.json")

lazy val repl: Project = project.in(
    file(".repl")
).settings(
    commonSettings ++ macroSettings ++ noPublishSettings,
    description := "Scio REPL for streaming",
    libraryDependencies ++= Seq(
        "com.spotify" %% "scio-repl" % scioVersion
    ),
    mainClass in Compile := Some("com.spotify.scio.repl.ScioShell")
).dependsOn(
    root
)

enablePlugins(AssemblyPlugin)

assemblyShadeRules in assembly := Seq(
    ShadeRule.rename("com.google.protobuf.**" -> s"com.google.protobuf_shaded.@1").inAll,
    ShadeRule.rename("com.fasterxml.jackson.**" -> s"com.fasterxml.jackson_shaded.@1").inAll,
    ShadeRule.rename("org.objenesis.**" -> s"org.objenesis_shaded.@1").inAll,
    ShadeRule.rename("com.esotericsoftware.kryo.**" ->
        s"com.esotericsoftware.kryo_shaded.@1"
    ).inAll,
    ShadeRule.rename("com.twitter.chill.**" -> s"com.twitter.chill_shaded.@1").inAll
)

assemblyMergeStrategy in assembly := {

    case m if m.toLowerCase.contains("com.google.protobuf") =>
        MergeStrategy.first

    case x if Assembly.isConfigFile(x) =>
        MergeStrategy.concat
    case PathList(ps @ _*) if Assembly.isReadme(ps.last) || Assembly.isLicenseFile(ps.last) =>
        MergeStrategy.rename
    case PathList("META-INF", xs @ _*) =>
        (xs map {_.toLowerCase}) match {
            case ("manifest.mf" :: Nil) | ("index.list" :: Nil) | ("dependencies" :: Nil) =>
                MergeStrategy.last
            case ps @ (x :: xs) if ps.last.endsWith(".sf") || ps.last.endsWith(".dsa") =>
                MergeStrategy.discard
            case "plexus" :: xs =>
                MergeStrategy.discard
            case "services" :: xs =>
                MergeStrategy.filterDistinctLines

            case "log4j.properties" :: Nil  => MergeStrategy.discard


            case _ => MergeStrategy.first
        }
    case _ => MergeStrategy.last

}

```
