### ISSUE TITLE
Stateful Processing fails due to incorrect Type in ValueState

### ISSUE THREAD

**Issue by leonardoam** [spotify/scio#1157]
I'm trying to do stateful processing using Scio and beam. My code is doing something like that:

```scala
sc.pubsubSubscription[String]("projects/arquiveidev/subscriptions/sub_id")
      .map { message =>
        val messageJson = JsonMethods.parse(message)

        val id = (messageJson \ "Data" \ "ID" \\ classOf[JString]).head

        KV.of(id, message)
      }
      .applyTransform(ParDo.of(new DoFn[KV[String,String], String] {
        @StateId("Value") private final val valueSpec = StateSpecs.value(DoubleCoder.of)

        @ProcessElement
        private[arquivei] def processElement(context: ProcessContext, @StateId("Value") valueState: ValueState[Double]): Unit = {

        }
      }))
```

Translating, I'm reading JSON strings from Pub/Sub, parsing an ID to make a KV, and passing to a DoFn which will do a stateful processing using a state called 'Value'.

I'm able to compile the code, but when I run I get the following exception:

```
[error] (run-main-0) java.lang.IllegalArgumentException: com.arquivei.NfeStreamingPipeline$$anon$1, @ProcessElement processElement(ProcessContext, ValueState), @ProcessElement processElement(ProcessContext, ValueState), parameter of type ValueState<Object> at index 1: data type of reference to StateId Value must be a supertype of ValueState<Double>
[error] java.lang.IllegalArgumentException: com.arquivei.NfeStreamingPipeline$$anon$1, @ProcessElement processElement(ProcessContext, ValueState), @ProcessElement processElement(ProcessContext, ValueState), parameter of type ValueState<Object> at index 1: data type of reference to StateId Value must be a supertype of ValueState<Double>
[error] 	at org.apache.beam.sdk.transforms.reflect.DoFnSignatures$ErrorReporter.throwIllegalArgument(DoFnSignatures.java:1351)
[error] 	at org.apache.beam.sdk.transforms.reflect.DoFnSignatures$ErrorReporter.checkArgument(DoFnSignatures.java:1356)
[error] 	at org.apache.beam.sdk.transforms.reflect.DoFnSignatures.analyzeExtraParameter(DoFnSignatures.java:891)
[error] 	at org.apache.beam.sdk.transforms.reflect.DoFnSignatures.analyzeProcessElementMethod(DoFnSignatures.java:736)
[error] 	at org.apache.beam.sdk.transforms.reflect.DoFnSignatures.parseSignature(DoFnSignatures.java:349)
[error] 	at org.apache.beam.sdk.transforms.reflect.DoFnSignatures.lambda$getSignature$0(DoFnSignatures.java:110)
[error] 	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
[error] 	at org.apache.beam.sdk.transforms.reflect.DoFnSignatures.getSignature(DoFnSignatures.java:110)
[error] 	at org.apache.beam.sdk.transforms.ParDo.validate(ParDo.java:556)
[error] 	at org.apache.beam.sdk.transforms.ParDo.of(ParDo.java:437)
[error] 	at com.arquivei.NfeStreamingPipeline$.main(NfeStreamingPipeline.scala:40)
[error] 	at com.arquivei.NfeStreamingPipeline.main(NfeStreamingPipeline.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1169)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1164)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

This exception does not make much sense to me, since I'm passing a ValueState[Double] as argument in the DoFn signature, and the Exception implies that somewhere apache beam is checking this as a ValueState[Object].

My versions are:

```scala
val scioVersion = "0.5.3"
val beamVersion = "2.4.0"
val scalaMacrosVersion = "2.1.0"
val scalaVersion          := "2.11.12"

libraryDependencies ++= Seq(
    "com.spotify" %% "scio-core" % scioVersion,
    "com.spotify" %% "scio-bigquery" % "0.5.3",
    "com.spotify" %% "scio-test" % scioVersion % "test",
    "org.apache.beam" % "beam-runners-direct-java" % beamVersion,
    "org.apache.beam" % "beam-runners-google-cloud-dataflow-java" % beamVersion)
```

Is there any workaround or something I'm doing wrong?

If you need any additional information.

**Comment by leonardoam** [comment]
Just adding some more info:

I used this snippet as a reference, not sure what versions is using: https://gist.github.com/calonso/14b06f4f58faf286cc79181cb46a9b85

Is there any limitation or documentation for doing stateful processing in Scio?

**Comment by leonardoam** [comment]
Doing same thing in Java, and it works:

```java
p.apply("Read from PubSub", PubsubIO
                .readStrings()
                .fromSubscription("projects/arquiveidev/subscriptions/sub_id")
                .withIdAttribute("ID"))
                .apply("Kv", ParDo.of(new DoFn<String, KV<String,String>>() {
                    @ProcessElement
                    public void processElement(ProcessContext context) {
                        JSONObject jsonObject = new JSONObject(context.element());
                        context.output(KV.of(jsonObject.getJSONObject("Data").getString("ID"), context.element()));
                    }
                }))
                .apply("State", ParDo.of(new DoFn<KV<String, String>, String>() {
                    @StateId("Value")
                    private final StateSpec<ValueState<Double>> valueSpec = StateSpecs.value(DoubleCoder.of());

                    @ProcessElement
                    public void processElement(ProcessContext context, @StateId("Value") ValueState<Double> valueState) {
                        KV<String,String> message = context.element();
                        JSONObject jsonObject = new JSONObject(message.getValue());

                        double currentValue = 0.0;
                        try {
                            currentValue = valueState.read();
                        } catch (Exception e) {
                            LOG.info("Init currentValue with zero");
                        }
                        LOG.info("message: "+message);
                        LOG.info(message.getKey()+"="+currentValue);

                        valueState.write(currentValue+jsonObject.getJSONObject("Data").getDouble("Value"));
                    }
                }));
```

Versions:

```xml
    <beam.version>2.4.0</beam.version>

    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-sdks-java-core</artifactId>
      <version>${beam.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-runners-direct-java</artifactId>
      <version>${beam.version}</version>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-runners-google-cloud-dataflow-java</artifactId>
      <version>${beam.version}</version>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-sdks-java-io-google-cloud-platform</artifactId>
      <version>${beam.version}</version>
    </dependency>
```

**Comment by nevillelyh** [comment]
The error message reads `data type of reference to StateId Value must be a supertype of ValueState<Double>` and you have `@StateId("Value") valueState: ValueState[Double]`, which leads me to suspect that it's the different type erasure between `java.lang.Double` vs `scala.Double`.

Can you try if `valueState: ValueState[scala.Double]` works?

**Comment by leonardoam** [comment]
Yes, that was the problem.
Thanks for helping!
I will close this issue for now.
