### ISSUE TITLE
HotKeyFanout crashes on global window with discarding fired panes

### ISSUE THREAD

**Issue by JozoVilcek** [spotify/scio#1159]
Hello,

I am running following function on scio `0.5.3` and Beam DirectRunner
```scala
  def countKeys[T <: Product: ClassTag](stream: SCollection[T], 
                                        flushInterval: Duration): SCollection[(T, Long)] = {
    stream
        .withGlobalWindow(
          options = WindowOptions(
            trigger = Repeatedly.forever(
              AfterProcessingTime.pastFirstElementInPane().plusDelayOf(flushInterval)),
            accumulationMode = AccumulationMode.DISCARDING_FIRED_PANES,
            allowedLateness = Duration.ZERO
          )
        )
        .map((_, 1L))
        .withHotKeyFanout(_ => ThreadLocalRandom.current().nextInt(10))
        .sumByKey
  }
```
The test case feeds some elements to the window and then stops but keep advancing processiong time. The result is crash with this error:
```
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at com.spotify.scio.util.Functions$$anon$2.mergeAccumulators(Functions.scala:187)
	at com.spotify.scio.util.Functions$$anon$2.mergeAccumulators(Functions.scala:183)
	at org.apache.beam.sdk.transforms.Combine$PerKeyWithHotKeyFanout$2.addInput(Combine.java:1711)
	at org.apache.beam.sdk.transforms.Combine$PerKeyWithHotKeyFanout$2.addInput(Combine.java:1700)
	at org.apache.beam.sdk.transforms.Combine$CombineFn.apply(Combine.java:399)
	at org.apache.beam.sdk.transforms.Combine$GroupedValues$1.processElement(Combine.java:2142)
```

When using global window with `ACCUMULATING_FIRED_PANES` it does work. It also works with using hotkeys via pure Beam like in this quick example:
```scala
  def countKeys[T <: Product: ClassTag](stream: SCollection[T], 
                                                  flushInterval: Duration): SCollection[(T, Long)] = {

    val countedKeys = stream
        .withGlobalWindow(
          options = WindowOptions(
            trigger = Repeatedly.forever(
              AfterProcessingTime.pastFirstElementInPane()
                  .plusDelayOf(flushInterval)),
            accumulationMode = AccumulationMode.DISCARDING_FIRED_PANES,
            allowedLateness = Duration.ZERO
          )
        )
        .map(x => KV.of(x, new java.lang.Long(1)))
        .setCoder(KvCoder.of(stream.internal.getCoder, VarLongCoder.of()))
        .internal
        .apply(
          Combine
              .perKey(Sum.ofLongs())
              .withHotKeyFanout(new SerializableFunction[T, Integer] {
                override def apply(input: T): Integer = ThreadLocalRandom.current().nextInt(10)
              }))

    stream.context
        .wrap(countedKeys)
        .map(x => (x.getKey, x.getValue.toLong))
  }
```

**Comment by JozoVilcek** [comment]
OK, so I just find out that if fails the same also if I leave out `.withHotKeyFanout` and do only `sumByKey`. So maybe something wrong with combine function? Or am I doing something wrong?

**Comment by nevillelyh** [comment]
It's possible that you have an empty window which `sumByKey` couldn't handle since it doesn't have a default `ZERO` case. You can probably work around it with `foldByKey` or `aggregateByKey `. See #778.

Gonna close this. Feel free to reopen if you have other questions.

**Comment by JozoVilcek** [comment]
Yes, I was not sure mostly about inconsistency between Scio and Beam behaviour. By reading #778 it is clear. I can live with `aggregateByKey()` which works fine. Thanks!
