### ISSUE TITLE
Group by & Windowing: AbstractList.add UnsupportedOperationException

### ISSUE THREAD

**Issue by Juta** [spotify/scio#1182]
I am writing a pipeline to deduplicate arriving messages in pubsub. If a message with the same key arrives in a 30s window, only the latest message should be kept.

When testing this pipeline on a test set it works fine. However when putting it in production with > 50000 messages each minute in pubsub I get the following error. I have no idea why it is caused and I am unable to reproduce it with a smaller test set of incoming pubsub messages.

```
exception:  "java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.spotify.scio.util.Functions$ReduceFn.addInput(Functions.scala:158)
	at com.spotify.scio.util.Functions$ReduceFn.addInput(Functions.scala:153)
	at com.google.cloud.dataflow.worker.WindmillStateInternals$WindmillCombiningState.add(WindmillStateInternals.java:920)
	at org.apache.beam.runners.core.SystemReduceFn.processValue(SystemReduceFn.java:117)
	at org.apache.beam.runners.core.ReduceFnRunner.processElement(ReduceFnRunner.java:601)
	at org.apache.beam.runners.core.ReduceFnRunner.processElements(ReduceFnRunner.java:344)
	at com.google.cloud.dataflow.worker.StreamingGroupAlsoByWindowViaWindowSetFn.processElement(StreamingGroupAlsoByWindowViaWindowSetFn.java:94)
	at com.google.cloud.dataflow.worker.StreamingGroupAlsoByWindowViaWindowSetFn.processElement(StreamingGroupAlsoByWindowViaWindowSetFn.java:42)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:114)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:72)
	at org.apache.beam.runners.core.LateDataDroppingDoFnRunner.processElement(LateDataDroppingDoFnRunner.java:74)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:133)
	at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
	at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:200)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:158)
	at com.google.cloud.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:75)
	at com.google.cloud.dataflow.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:1211)
	at com.google.cloud.dataflow.worker.StreamingDataflowWorker.access$1000(StreamingDataflowWorker.java:137)
	at com.google.cloud.dataflow.worker.StreamingDataflowWorker$6.run(StreamingDataflowWorker.java:959)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This is my code:

```
object TestWindowing {

  val formatter = DateTimeFormat.forPattern("yyyyMMddHHmmssSSS");

  @BigQueryType.toTable
  case class Message(key: String, text: String, time: Instant)

  def convertMessage(line: String): Message = {
    val json: JsValue = Json.parse(line)
    new Message((json \ "key").as[String],
              (json \ "text").as[String],
              Instant.parse((json \ "time").as[String], formatter))
  }
  def main(cmdlineArgs: Array[String]): Unit = {

    val (sc, args) = ContextAndArgs(cmdlineArgs)
    sc.optionsAs[StreamingOptions].setStreaming(true)

    val rawEvents = sc.withName("Read Pubsub").pubsubSubscription(args("subscription"))
      .withName("Transform to BQ Row").map(convertMessage)
      .withName("Generate session key").map(m => (m.key, m))
      .withName("Group by window").withSessionWindows(Duration.standardSeconds(30L))
      .withName("Group by key").maxByKey(Ordering.by(_.time))
      .withName("Drop key").values
      .withName("Write to BQ").saveAsTypedBigQuery(args("output"), WRITE_APPEND)

    val result = sc.close().waitUntilFinish()
  }
}
```

I am not sure if this is a bug or an issue in my code. Can anybody help me out?

**Comment by nevillelyh** [comment]
So somehow the `JList[T]` to `addInput` method is immutable.
https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/util/Functions.scala#L158

I'm suspecting that `mergeAccumulators` is the culprit, since the returned `JList` is a wrapped Scala `List` and most likely immutable.
https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/util/Functions.scala#L171

**Comment by nevillelyh** [comment]
I can reproduce with the following snippet

```scala
package com.spotify.scio

import com.spotify.scio.util.Functions

import scala.collection.JavaConverters._

object Test {
  def main(args: Array[String]): Unit = {
    val fn = Functions.reduceFn[Int]((x: Int, y: Int) => x + y)
    var a1 = fn.createAccumulator()
    var a2 = fn.createAccumulator()
    a1 = fn.addInput(a1, 1)
    a2 = fn.addInput(a2, 10)
    var a3 = fn.mergeAccumulators(Iterable(a1, a2).asJava)
    a3 = fn.addInput(a3, 100)
    println(fn.extractOutput(a3))
  }
}
```

So the returned `JList[T]` of `mergeAccumulators` is immutable and cannot be used in another `addInput` call.
