### ISSUE TITLE
Intermittent Bigtable lookup failure with BigtableDoFn causing Dataflow job to become throttled.

### ISSUE THREAD

**Issue by andrewnguonly** [spotify/scio#1191]
#### Summary
Dataflow job becomes completely throttled when making request to Bigtable with `BigtableDoFn`. This doesn't happen often; I'm seeing this maybe once per week or once every 2 weeks. Based on the logs from Stackdriver, it seems like a single element in the pipeline is the cause of the entire backup. Restarting the job mitigates the issue.

This may be unrelated to Scio. However, I've never experienced this issue when using `ScalaAsyncDoFn`, which implements Scala's `Future` instead of Google's `ListenableFuture`. The implementation is slightly different.

#### Stackdriver Logs
```
Processing stuck in step [TRANSFORM_NAME] for at least 04h35m00s without outputting or completing in state finish...
Processing stuck in step [TRANSFORM_NAME] for at least 04h30m00s without outputting or completing in state finish...
Processing stuck in step [TRANSFORM_NAME] for at least 04h25m00s without outputting or completing in state finish...
```
These log messages go on indefinitely with the time (`04h35m00s`) increasing by 5 minutes each time.

#### Full Stack Trace
```java
Processing stuck in step Request product id from Bigtable for at least 04h35m00s without outputting or completing in state finish
  at sun.misc.Unsafe.park(Native Method)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:469)
  at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)
  at com.spotify.scio.transforms.AsyncLookupDoFn.finishBundle(AsyncLookupDoFn.java:174)
  at com.[COMPANY].[APPLICATION].GetProductIdDoFn$GetProductIdDoFn$DoFnInvoker.invokeFinishBundle(Unknown Source)
```
In this stack trace, `GetProductIdDoFn` extends `BigtableDoFn`.

#### Possible Workaround
Implement option for hard timeout with `TimeoutFuture`?

**Comment by nevillelyh** [comment]
When you say `ScalaAsyncDoFn`, are you wrapping Bigtable lookups in Scala `Future`? And that works well under the same load as `BigtableDoFn`?

**Comment by andrewnguonly** [comment]
>When you say ScalaAsyncDoFn, are you wrapping Bigtable lookups in Scala Future? And that works well under the same load as BigtableDoFn?

Yes. Before `BigtableDoFn` existed, we implemented lookups to Bigtable using `ScalaAsyncDoFn`. The workload was definitely much less. I suppose that could be related. I can try reducing the maximum number of pending requests to Bigtable to see if that makes a difference.

**Comment by jbx** [comment]
@andrewnguonly - we're trying to clean up the issues a bit. Did you ever find out if reducing the max number of pending tasks fixed the issue?

**Comment by nevillelyh** [comment]
No activity for > 1 year. Closing.
