### ISSUE TITLE
BigQueryType throws ServiceConfigurationError in console

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#12]
This used to work.

```
scala> import com.spotify.scio.bigquery.types.BigQueryType
import com.spotify.scio.bigquery.types.BigQueryType

scala> @BigQueryType.fromTable("di-bigquery-data-commons:track_entity.track_entity_20160224") class TE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
<console>:11: error: exception during macro expansion:
java.util.ServiceConfigurationError: com.google.cloud.dataflow.sdk.runners.PipelineRunnerRegistrar: Provider com.google.cloud.dataflow.sdk.runners.DataflowPipelineRegistrar$Runner not a subtype
        at java.util.ServiceLoader.fail(ServiceLoader.java:231)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:369)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
        at com.google.cloud.dataflow.sdk.repackaged.com.google.common.collect.Iterators.addAll(Iterators.java:362)
        at com.google.cloud.dataflow.sdk.repackaged.com.google.common.collect.Lists.newArrayList(Lists.java:160)
        at com.google.cloud.dataflow.sdk.repackaged.com.google.common.collect.Lists.newArrayList(Lists.java:144)
        at com.google.cloud.dataflow.sdk.options.PipelineOptionsFactory.<clinit>(PipelineOptionsFactory.java:510)
        at com.spotify.scio.bigquery.BigQueryClient$.apply(BigQueryClient.scala:384)
        at com.spotify.scio.bigquery.BigQueryClient$.apply(BigQueryClient.scala:377)
        at com.spotify.scio.bigquery.types.TypeProvider$.bigquery$lzycompute(TypeProvider.scala:32)
        at com.spotify.scio.bigquery.types.TypeProvider$.bigquery(TypeProvider.scala:32)
        at com.spotify.scio.bigquery.types.TypeProvider$.tableImpl(TypeProvider.scala:41)

       @BigQueryType.fromTable("di-bigquery-data-commons:track_entity.track_entity_20160224") class TE
        ^
```

**Comment by nevillelyh** [comment]
Fixed in https://github.com/spotify/scio/commit/03d32e8f008b9a9419f0127578d6f874fe1e1649
