### ISSUE TITLE
OOM when using Sparkey side inputs since scio 0.5.6

### ISSUE THREAD

**Issue by jto** [spotify/scio#1269]
After upgrading from scio `0.5.5` to scio `0.5.6`, the following OOM appeared:

```
java.io.IOException: Map failed
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:940)
	at com.spotify.sparkey.ReadOnlyMemMap.createChunk(ReadOnlyMemMap.java:93)
	at com.spotify.sparkey.ReadOnlyMemMap.<init>(ReadOnlyMemMap.java:76)
	at com.spotify.sparkey.IndexHash.open(IndexHash.java:84)
	at com.spotify.sparkey.SingleThreadedSparkeyReader.<init>(SingleThreadedSparkeyReader.java:32)
	at com.spotify.sparkey.SingleThreadedSparkeyReader.open(SingleThreadedSparkeyReader.java:49)
	at com.spotify.sparkey.Sparkey.openSingleThreadedReader(Sparkey.java:110)
	at com.spotify.sparkey.extra.ThreadLocalSparkeyReader.<init>(ThreadLocalSparkeyReader.java:36)
	at com.spotify.scio.extra.sparkey.RemoteSparkeyUri.getReader(SparkeyUri.scala:69)
	at com.spotify.scio.extra.sparkey.package$SparkeySideInput.get(package.scala:185)
	at com.spotify.scio.extra.sparkey.package$SparkeySideInput.get(package.scala:182)
	at com.spotify.scio.values.SideInput$class.getCache(SideInput.scala:40)
	at com.spotify.scio.extra.sparkey.package$SparkeySideInput.getCache(package.scala:182)
	at com.spotify.scio.values.SideInputContext.apply(SideInput.scala:118)
	at com.spotify.gabo.joins.HotSetLeftJoin$$anonfun$apply$3$$anonfun$7.apply(SparkeyJoiner.scala:111)
	at com.spotify.gabo.joins.HotSetLeftJoin$$anonfun$apply$3$$anonfun$7.apply(SparkeyJoiner.scala:105)
	at com.spotify.scio.util.FunctionsWithSideInput$$anon$3.processElement(FunctionsWithSideInput.scala:56)
Caused by: java.lang.OutOfMemoryError: Map failed
	at sun.nio.ch.FileChannelImpl.map0(Native Method)
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:937)
	at com.spotify.sparkey.ReadOnlyMemMap.createChunk(ReadOnlyMemMap.java:93)
	at com.spotify.sparkey.ReadOnlyMemMap.<init>(ReadOnlyMemMap.java:76)
	at com.spotify.sparkey.IndexHash.open(IndexHash.java:84)
	at com.spotify.sparkey.SingleThreadedSparkeyReader.<init>(SingleThreadedSparkeyReader.java:32)
	at com.spotify.sparkey.SingleThreadedSparkeyReader.open(SingleThreadedSparkeyReader.java:49)
	at com.spotify.sparkey.Sparkey.openSingleThreadedReader(Sparkey.java:110)
	at com.spotify.sparkey.extra.ThreadLocalSparkeyReader.<init>(ThreadLocalSparkeyReader.java:36)
	at com.spotify.scio.extra.sparkey.RemoteSparkeyUri.getReader(SparkeyUri.scala:69)
	at com.spotify.scio.extra.sparkey.package$SparkeySideInput.get(package.scala:185)
	at com.spotify.scio.extra.sparkey.package$SparkeySideInput.get(package.scala:182)
	at com.spotify.scio.values.SideInput$class.getCache(SideInput.scala:40)
	at com.spotify.scio.extra.sparkey.package$SparkeySideInput.getCache(package.scala:182)
	at com.spotify.scio.values.SideInputContext.apply(SideInput.scala:118)
	at com.spotify.gabo.joins.HotSetLeftJoin$$anonfun$apply$3$$anonfun$7.apply(SparkeyJoiner.scala:111)
	at com.spotify.gabo.joins.HotSetLeftJoin$$anonfun$apply$3$$anonfun$7.apply(SparkeyJoiner.scala:105)
	at com.spotify.scio.util.FunctionsWithSideInput$$anon$3.processElement(FunctionsWithSideInput.scala:56)
	at com.spotify.scio.util.FunctionsWithSideInput$$anon$3$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:185)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:146)
	at com.google.cloud.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:323)
	at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
	at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
	at com.google.cloud.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:271)
	at org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:219)
	at org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:69)
	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:517)
	at org.apache.beam.sdk.transforms.DoFnOutputReceivers$WindowedContextOutputReceiver.output(DoFnOutputReceivers.java:42)
	at org.apache.beam.sdk.transforms.Partition$PartitionDoFn.processElement(Partition.java:171)
	at org.apache.beam.sdk.transforms.Partition$PartitionDoFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:185)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:149)
	at com.google.cloud.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:323)
	at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
	at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
	at com.google.cloud.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:271)
	at org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:219)
	at org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:69)
	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:517)
	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:505)
	at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:145)
	at com.spotify.scio.util.Functions$$anon$7$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:185)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:149)
	at com.google.cloud.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:323)
	at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
	at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
	at com.google.cloud.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:271)
	at org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:219)
	at org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:69)
	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:517)
	at org.apache.beam.sdk.transforms.DoFnOutputReceivers$WindowedContextOutputReceiver.output(DoFnOutputReceivers.java:42)
	at org.apache.beam.sdk.transforms.Partition$PartitionDoFn.processElement(Partition.java:171)
	at org.apache.beam.sdk.transforms.Partition$PartitionDoFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:185)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:149)
	at com.google.cloud.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:323)
	at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
	at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:200)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:158)
	at com.google.cloud.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:75)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:391)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:360)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:288)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:134)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:114)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Downgrading to 0.5.5 and running the pipeline on the same dataset works as expected.

**Comment by jto** [comment]
Likely caused by https://github.com/spotify/scio/pull/1231

**Comment by jto** [comment]
I did manage to see the increased memory usage caused by #1231 using the following test:

```scala
runWithContext { sc =>
      val tempLocation = java.nio.file.Files.createTempDirectory("sparkey-it")
      tempLocation.toFile.deleteOnExit
      val basePath = tempLocation + "/sparkey"
      // Create a sparkey KV file
      val writer = com.spotify.sparkey.Sparkey.createNew(new java.io.File(basePath))
      (1 to 100000000).foreach { x => writer.put(x.toString, x.toString) }
      writer.flush()
      writer.writeHash()
      writer.close()

      FileSystems.setDefaultPipelineOptions(sc.options)
      val p1 = sc.parallelize(1 to 100)
      val p2 = new SparkeyScioContext(sc).sparkeySideInput(basePath)
      p1.withSideInputs(p2)
        .map{ (x, si) =>
          si(p2).get(x.toString)
        }.toSCollection
    }
```

Working on a fix.

**Comment by jto** [comment]
So I think I managed to reproduce it locally and it's indeed caused by #1231 

Here's the code to reproduce:

```scala
runWithContext { sc =>

      FileSystems.setDefaultPipelineOptions(sc.options)
      val tempLocation = ItUtils.gcpTempLocation("sparkey-it")
      val basePath = tempLocation + "/sparkey"
      val resourceId = FileSystems.matchNewResource(basePath + ".spi", false)
      // Create a sparkey KV file
      val uri = SparkeyUri(basePath, sc.options)
      val writer =  new SparkeyWriter(uri, -1)
      (1 to 100000000).foreach { x => writer.put(x.toString, x.toString) }
      // writer.flush()
      // writer.writeHash()
      writer.close()

      try {
        val p1 = sc.parallelize(1 to 300)
        val p2 = new SparkeyScioContext(sc).sparkeySideInput(basePath)
        p1.withSideInputs(p2)
          .map{ (x, si) =>
            si(p2).get(x.toString)
          }.toSCollection
      } finally {
        FileSystems.delete(Seq(resourceId).asJava)
      }
    }
```
Note that the test does not OOM be monitoring the heap using a profiler, we can see the difference in behaviour. 
I'll try to implement a fix.
