### ISSUE TITLE
Need to force coder when applying transform to map

### ISSUE THREAD

**Issue by henriknaknese** [spotify/scio#1447]
Had issues when transforming on a map. Fix provided by @jto but should perhaps be integrated/fixed into scio.
```
val data: PCollection[Struct] = sc.pipeline.apply(
  SpannerIO.read()
    .withProjectId(spannerInstanceProject)
    .withInstanceId(spannerInstanceId)
    .withDatabaseId(spannerDatabaseId)
    .withQuery("SELECT * FROM " + spannerTableName))

    val transformedData: SCollection[Transformed] = sc.wrap(data.apply(ParDo.of(new TransformRow())))
```
Reading several rows, as below, from the map breaks
```
val data =
      ids.map(id => ReadOperation.create()
        .withQuery("SELECT * FROM " + spannerTableName + " WHERE id = " + "\"" + id + "\""))
        .applyTransform(SpannerIO.readAll()
        .withProjectId(spannerInstanceProject)
        .withInstanceId(spannerInstanceId)
        .withDatabaseId(spannerDatabaseId))
        .applyTransform(ParDo.of(new TransformRow()))
```
The fix provided by @jto was to fore the Coder after mapping
```
.setCoder(org.apache.beam.sdk.coders.SerializableCoder.of(classOf[ReadOperation])))
```

**Comment by jto** [comment]
The problem comes from Kryo not serializing `ReadOperation` properly with causes a NPE:

```
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
keys (com.google.cloud.spanner.KeySet)
keySet (org.apache.beam.sdk.io.gcp.spanner.AutoValue_ReadOperation)
    at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:101)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
    at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:629)
    at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:86)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
    at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
```
