### ISSUE TITLE
Publish scio-repl jar so it can be used from external projects

### ISSUE THREAD

**Issue by jdanbrown** [spotify/scio#160]
Is there currently a way to run the scio repl from my own project that depends on scio? Ideally I could `java com.spotify.scio.repl.ScioShell` from any project with scio-repl on its classpath, but scio-repl isn't currently published, so I instead have to git clone the scio project, build the scio-repl assembly jar, and manually interact with it.

- https://github.com/spotify/scio/blob/692b429/build.sbt#L331
- https://oss.sonatype.org/content/repositories/releases/com/spotify/

**Comment by jdanbrown** [comment]
Hmm, trying to make this work myself, I run into this error:
```
> scio-repl/run-main com.spotify.scio.repl.ScioShell
[info] Running com.spotify.scio.repl.ScioShell
Welcome to
                 _____
    ________________(_)_____
    __  ___/  ___/_  /_  __ \
    _(__  )/ /__ _  / / /_/ /
    /____/ \___/ /_/  \____/   version 0.1.7

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_91)

Type in expressions to have them evaluated.
Type :help for more information.

[error] (run-main-0) scala.reflect.internal.FatalError: package scala does not have a member Int
scala.reflect.internal.FatalError: package scala does not have a member Int
        at scala.reflect.internal.Definitions$DefinitionsClass.scala$reflect$internal$Definitions$DefinitionsClass$$fatalMissingSymbol(Definitions.scala:1186)
        at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1203)
        at scala.reflect.internal.Definitions$ValueClassDefinitions$class.valueClassSymbol(Definitions.scala:77)
        at scala.reflect.internal.Definitions$ValueClassDefinitions$class.IntClass(Definitions.scala:114)
        at scala.reflect.internal.Definitions$DefinitionsClass.IntClass$lzycompute(Definitions.scala:153)
        at scala.reflect.internal.Definitions$DefinitionsClass.IntClass(Definitions.scala:153)
        at scala.reflect.internal.Definitions$ValueClassDefinitions$class.IntTpe(Definitions.scala:127)
        at scala.reflect.internal.Definitions$DefinitionsClass.IntTpe$lzycompute(Definitions.scala:153)
        at scala.reflect.internal.Definitions$DefinitionsClass.IntTpe(Definitions.scala:153)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:630)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:728)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$sigToType(ClassfileParser.scala:774)
        at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.getType(ClassfileParser.scala:289)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parseMethod(ClassfileParser.scala:568)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$queueLoad$1(ClassfileParser.scala:483)
        at scala.tools.nsc.symtab.classfile.ClassfileParser$$anonfun$parseClass$1.apply$mcV$sp(ClassfileParser.scala:493)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:498)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:139)
        at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader$$anonfun$doComplete$2.apply$mcV$sp(SymbolLoaders.scala:347)
        at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader$$anonfun$doComplete$2.apply(SymbolLoaders.scala:347)
        at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader$$anonfun$doComplete$2.apply(SymbolLoaders.scala:347)
        at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
        at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:347)
        at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:211)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
        at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1659)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
        at scala.tools.nsc.interpreter.IMain.scala$tools$nsc$interpreter$IMain$$_initialize(IMain.scala:132)
        at scala.tools.nsc.interpreter.IMain.global$lzycompute(IMain.scala:161)
        at scala.tools.nsc.interpreter.IMain.global(IMain.scala:160)
        at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:573)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:567)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
        at com.spotify.scio.repl.ScioILoop.com$spotify$scio$repl$ScioILoop$$addImports(ScioILoop.scala:196)
        at com.spotify.scio.repl.ScioILoop$$anonfun$createInterpreter$1.apply(ScioILoop.scala:243)
        at com.spotify.scio.repl.ScioILoop$$anonfun$createInterpreter$1.apply(ScioILoop.scala:242)
        at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:214)
        at com.spotify.scio.repl.ScioILoop.createInterpreter(ScioILoop.scala:242)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:911)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
        at com.spotify.scio.repl.BaseScioShell$class.process(ScioShell.scala:70)
        at com.spotify.scio.repl.ScioShell$.process(ScioShell.scala:82)
        at com.spotify.scio.repl.BaseScioShell$class.main(ScioShell.scala:75)
        at com.spotify.scio.repl.ScioShell$.main(ScioShell.scala:82)
        at com.spotify.scio.repl.ScioShell.main(ScioShell.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last scio-repl/compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last scio-repl/compile:runMain for the full output.
[error] (scio-repl/compile:runMain) Nonzero exit code: 1
[error] Total time: 2 s, completed May 28, 2016 5:23:09 PM
```

Even though running directly against the assembly jar works:
```
$ java -jar scio-repl/target/scala-2.11/scio-repl-0.1.7.jar
Welcome to
                 _____
    ________________(_)_____
    __  ___/  ___/_  /_  __ \
    _(__  )/ /__ _  / / /_/ /
    /____/ \___/ /_/  \____/   version 0.1.7

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_91)

Type in expressions to have them evaluated.
Type :help for more information.

Using 'dan-0' as your BigQuery project.
BigQuery client available as 'bq'
Scio context available as 'sc'

scio>
```

**Comment by nevillelyh** [comment]
We can publish a REPL jar but the current one is built with assembly plugin with some specific settings so not sure if it will work for your case. Can you publish one locally and try it out? Happy to merge PR if it works.

**Comment by jdanbrown** [comment]
Yes, building the assembly jar locally and manually linking it into my project does work, but ideally we could defer the dependency management and linking to sbt/ivy.

Have you already tried this and run into trouble? Any particular settings in the assembly that make this difficult? When I briefly gave it a shot I ran into the error above, did a small amount of digging, and then decided to stop, but I'd be happy to try again with more pointers.

**Comment by nevillelyh** [comment]
Does a standard non-assembly jar work for you? `sbt publish-local` to build and publish to your local `~/.ivy2/`.

Is your project source available somewhere?

**Comment by jdanbrown** [comment]
Nope, depending on a non-assembly jar gives the same error (re-pasted here) that I pasted above when trying to run `com.spotify.scio.repl.ScioShell` from the `scio-repl` sbt project. The assembly jar avoids this error, but it's not clear to me why...

```
> scio-repl/run-main com.spotify.scio.repl.ScioShell
[info] Running com.spotify.scio.repl.ScioShell
Welcome to
                 _____
    ________________(_)_____
    __  ___/  ___/_  /_  __ \
    _(__  )/ /__ _  / / /_/ /
    /____/ \___/ /_/  \____/   version 0.1.7

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_91)

Type in expressions to have them evaluated.
Type :help for more information.

[error] (run-main-0) scala.reflect.internal.FatalError: package scala does not have a member Int
scala.reflect.internal.FatalError: package scala does not have a member Int
        at scala.reflect.internal.Definitions$DefinitionsClass.scala$reflect$internal$Definitions$DefinitionsClass$$fatalMissingSymbol(Definitions.scala:1186)
        ...
```

**Comment by jdanbrown** [comment]
—And I think that solving the `scio-repl/run-main com.spotify.scio.repl.ScioShell` error would solve the larger problem, so I propose let's restrict our focus to that.

**Comment by ravwojdyla** [comment]
@jdanbrown ScioShell currently does not work and was not testing from sbt console itself. There is a couple of changes required to make it to work. There is brunch 1a8f95e (`fix_repl_sbt`) - which has fixes for sbt console launch (via `scio-repl/run`) - the problem it has is that makro can be expanded in that shell - I get:
```
<console>:29: error: macro annotation could not be expanded (the most common reason for that is that you need to enable the macro paradise plugin; another possibility is that you try to use macro annotation in the same compilation run that defines it)
```
I added paradise, tried adding plugin config file etc - but no luck yet - will try a bit harder. @jdanbrown could you give `fix_repl_sbt` a try for your use case?

**Comment by ravwojdyla** [comment]
@jdanbrown should be fixed via #165 - if you could fetch the changes and double check if it would for your use case, we would appreciate it a lot!

**Comment by jdanbrown** [comment]
@ravwojdyla Yep! My test case above works on c8189c8:
```
> scio-repl/run-main com.spotify.scio.repl.ScioShell
[info] Running com.spotify.scio.repl.ScioShell
Welcome to
                 _____
    ________________(_)_____
    __  ___/  ___/_  /_  __ \
    _(__  )/ /__ _  / / /_/ /
    /____/ \___/ /_/  \____/   version 0.1.8-SNAPSHOT

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_91)

Type in expressions to have them evaluated.
Type :help for more information.

Using 'dev-try-gcp' as your BigQuery project.
BigQuery client available as 'bq'
Scio context available as 'sc'

scio>
```

**Comment by ravwojdyla** [comment]
@jdanbrown swell! thanks for the validation. sbt launch works fine in `2.11` but there are some issues in `2.10`, as you can see in #165 - I'm not entirely sure what is wrong there. I think we could look more into this problem and/or throw an fatal exception on `2.10`. what do you think @nevillelyh ?

**Comment by jdanbrown** [comment]
Awesome, thanks!
