### ISSUE TITLE
Coder throws on NPE

### ISSUE THREAD

**Issue by jto** [spotify/scio#1604]
In Scio v 0.5.6 the following code works:
```
scala> import com.spotify.scio._
import com.spotify.scio._

scala> val sc = ScioContext()
sc: com.spotify.scio.ScioContext = com.spotify.scio.ScioContext@55957b5f

scala> def zToNull(z: Iterable[String]):String = {if(z.toList.contains("0")) null else z.toList.mkString(" ")}
zToNull: (z: Iterable[String])String

scala> sc.parallelize(Seq("1", "0")).groupBy(identity).mapValues(zToNull(_)).filter(_._2!=null).values.debug()
res0: com.spotify.scio.values.SCollection[String] = com.spotify.scio.values.SCollectionImpl@54ddd981

scala> sc.close()
1
res1: com.spotify.scio.ScioResult = com.spotify.scio.ScioContext$ContextScioResult@3bb5a279

```
In scio 0.7.0-beta1
```
scala> import com.spotify.scio._
import com.spotify.scio._

scala> val sc = ScioContext()
sc: com.spotify.scio.ScioContext = com.spotify.scio.ScioContext@307530a4

scala>  def zToNull(z: Iterable[String]):String = {if(z.toList.contains("0")) null else z.toList.mkString(" ")}
zToNull: (z: Iterable[String])String

scala> sc.parallelize(Seq("1", "0")).groupBy(identity).mapValues(zToNull(_)).filter(_._2!=null).values.debug()
res0: com.spotify.scio.values.SCollection[String] = com.spotify.scio.values.SCollectionImpl@710f6d48

scala> sc.close()
<console>:6: error: [wartremover:AsInstanceOf] asInstanceOf is disabled
         def set(x: _root_.scala.Any) = value = x.asInstanceOf[java.lang.Throwable]
                                                  ^
<console>:5: error: [wartremover:Var] var is disabled
         var value: java.lang.Throwable = _
             ^
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.RuntimeException: Exception while trying to `encode` field _2 with value null
  at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:332)
  at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:302)
  at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:197)
  at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:64)
  at org.apache.beam.sdk.Pipeline.run(Pipeline.java:313)
  at org.apache.beam.sdk.Pipeline.run(Pipeline.java:299)
  at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:489)
  at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:476)
  at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:542)
  at com.spotify.scio.ScioContext.close(ScioContext.scala:476)
  ... 36 elided
Caused by: java.lang.RuntimeException: Exception while trying to `encode` field _2 with value null
  at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:171)
  at com.spotify.scio.coders.RecordCoder.encode(Coder.scala:181)
  at org.apache.beam.sdk.coders.Coder.encode(Coder.java:136)
  at org.apache.beam.sdk.util.CoderUtils.encodeToSafeStream(CoderUtils.java:82)
  at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:66)
  at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:51)
  at org.apache.beam.sdk.util.CoderUtils.clone(CoderUtils.java:141)
  at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.<init>(MutationDetectors.java:113)
  at org.apache.beam.sdk.util.MutationDetectors.forValueWithCoder(MutationDetectors.java:44)
  at org.apache.beam.runners.direct.ImmutabilityCheckingBundleFactory$ImmutabilityEnforcingBundle.add(ImmutabilityCheckingBundleFactory.java:112)
  at org.apache.beam.runners.direct.ParDoEvaluator$BundleOutputManager.output(ParDoEvaluator.java:260)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:621)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:609)
  at com.spotify.scio.util.Functions$$anon$5.processElement(Functions.scala:172)
Caused by: org.apache.beam.sdk.coders.CoderException: cannot encode a null String
  at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:75)
  at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:69)
  at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:38)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:181)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$2.apply(Coder.scala:181)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$2.apply(Coder.scala:181)
  at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:169)
  at com.spotify.scio.coders.RecordCoder.encode(Coder.scala:181)
  at org.apache.beam.sdk.coders.Coder.encode(Coder.java:136)
  at org.apache.beam.sdk.util.CoderUtils.encodeToSafeStream(CoderUtils.java:82)
  at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:66)
  at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:51)
  at org.apache.beam.sdk.util.CoderUtils.clone(CoderUtils.java:141)
  at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.<init>(MutationDetectors.java:113)
  at org.apache.beam.sdk.util.MutationDetectors.forValueWithCoder(MutationDetectors.java:44)
  at org.apache.beam.runners.direct.ImmutabilityCheckingBundleFactory$ImmutabilityEnforcingBundle.add(ImmutabilityCheckingBundleFactory.java:112)
  at org.apache.beam.runners.direct.ParDoEvaluator$BundleOutputManager.output(ParDoEvaluator.java:260)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:621)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:609)
  at com.spotify.scio.util.Functions$$anon$5.processElement(Functions.scala:172)
  at com.spotify.scio.util.Functions$$anon$5$DoFnInvoker.invokeProcessElement(Unknown Source)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:275)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:240)
  at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimplePushbackSideInputDoFnRunner.processElementInReadyWindows(SimplePushbackSideInputDoFnRunner.java:78)
  at org.apache.beam.runners.direct.ParDoEvaluator.processElement(ParDoEvaluator.java:207)
  at org.apache.beam.runners.direct.DoFnLifecycleManagerRemovingTransformEvaluator.processElement(DoFnLifecycleManagerRemovingTransformEvaluator.java:55)
  at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:160)
  at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:124)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

**Comment by jto** [comment]
Looking at `NullableCoder`I'm not sure we should merge this  PR.
The javadoc (https://beam.apache.org/releases/javadoc/2.9.0/org/apache/beam/sdk/coders/NullableCoder.html) says:
>  NullableCoder uses exactly 1 byte per entry to indicate whether the value is null

which seems super wasteful when a single bit would be enough. I looked into the source code to make sure it was not just a typo, and it's indeed writing an int (https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/NullableCoder.java#L70)

**Comment by labianchin** [comment]
I agree that the `NullableCoder` seems wasteful. On the other hand it can be more user friendly.

Is there a way to make this configurable?

**Comment by anish749** [comment]
I was thinking if we could make the decision of whether to allow nulls (and accordingly choose a NullableCoder) a part of the user's code rather than in Scio. For example, Beam doesn't enforce non-nullability, but allows the user to choose a nullable coder.

May be have an annotation which would need to be used to explicitly specify if we want to use nulls, and accordingly Scio can choose a nullable coder.

**Comment by jto** [comment]
Making NullableCoder efficient should be fairly trivial so IMHO it's what we should be doing. 

Making the user choose a nullable coder is actually pretty tricky since null may appear not only at top level, but also in nested case classes or as members of collections.

**Comment by regadas** [comment]
@jto, quick thought here, what about changing this in the [`CoderMaterializer`](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala#L38) behind a compiler / sys flag?

**Comment by jto** [comment]
That would work but is an all of nothing kind of deal. 
In @anish749 case for example, only 1 step (AFAIK) in the pipeline was crashing, and it was very easily rewritten to not use null at all. Considering that, making everything nullable would also be wasteful.

**Comment by anish749** [comment]
Agreed we shouldn't make everything nullable. I found this problem, because one of the functions was misusing a null. But it took me 3 hrs to find this function because the pipeline was pretty large.

But I am still not sure why the sample in the issue worked in 0.5.6 when the following code doesn't work on 0.5.6

```
scala> val sc = ScioContext()
sc: com.spotify.scio.ScioContext = com.spotify.scio.ScioContext@36828b42

scala> def zToNull(z: Iterable[String]):String = {if(z.toList.contains("0")) null else z.toList.mkString(" ")}
zToNull: (z: Iterable[String])String

scala> sc.parallelize(Seq("1", "0")).groupBy(identity).mapValues(zToNull(_)).values.debug()
res2: com.spotify.scio.values.SCollection[String] = com.spotify.scio.values.SCollectionImpl@15cdd6d7

scala> sc.close()
1
<console>:6: error: [wartremover:AsInstanceOf] asInstanceOf is disabled
  def set(x: Any) = value = x.asInstanceOf[java.lang.Throwable]
                              ^
<console>:5: error: [wartremover:Var] var is disabled
  var value: java.lang.Throwable = _
      ^
org.apache.beam.sdk.Pipeline$PipelineExecutionException: org.apache.beam.sdk.coders.CoderException: cannot encode a null String
  at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:349)
  at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:319)
  at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:210)
  at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:66)
  at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
  at org.apache.beam.sdk.Pipeline.run(Pipeline.java:297)
  at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:369)
  at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:354)
  at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:419)
  at com.spotify.scio.ScioContext.close(ScioContext.scala:354)
  ... 40 elided
Caused by: org.apache.beam.sdk.coders.CoderException: cannot encode a null String
  at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:79)
  at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:39)
  at org.apache.beam.sdk.util.CoderUtils.encodeToSafeStream(CoderUtils.java:85)
  at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:69)
  at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:54)
  at org.apache.beam.sdk.util.CoderUtils.clone(CoderUtils.java:148)

scala>
```

**Comment by jto** [comment]
It used to work bc. 0.5.6 was serialising using Kryo, and Kryo defaults to "everything might be a null".

**Comment by regadas** [comment]
@jto @anish749 yeah I kinda like that it failed ... it raises the question if that value should really be `null` and encoded. I tend to prefer this idea instead of making things magically work ¯\_(ツ)_/¯ .

Also, in @anish749 example couldn't we play with the implicit scoping and override the string coder?

**Comment by jto** [comment]
@regadas We could "supply the right coder" but getting rid of nulls altogether was actually simpler.

**Comment by anish749** [comment]
> It used to work bc. 0.5.6 was serialising using Kryo, and Kryo defaults to "anything might be a null".

But it still fails in 0.5.6 if we don't add a filter step just after the map. so it is not using kryo by default.

**Comment by jto** [comment]
For a few types (primitives, String, etc.), Scio 0.5.6 will use Beam coders. The fact that filtering  nulls makes it work might just be the result an optimisation in Beam (fusioning `map` and `filter` and not using a coder at all between them) so this behaviour may change between versions.

**Comment by labianchin** [comment]
I also liked that it failed and I like the idea of avoiding nulls.

Still, one of the problems of this failure is that the exception/stack trace is not very actionable. Here in Anish's example the problem might be obvious, but when happening in a bigger pipeline it can be quite miserable to troubleshoot and pin point the issue.

**Comment by anish749** [comment]
@jto Right, so in newer versions the fusion isn't happening, and is introducing a new step of encoding/decoding. Is that expected?

**Comment by jto** [comment]
@labianchin I don't think there's a lot we can do. The exception is happening in beam's internal.
