### ISSUE TITLE
How to deal with CoderException: cannot encode a null String

### ISSUE THREAD

**Issue by git4sun** [spotify/scio#1719]
I just started using scio. Trying my code to one input file, worked fine. But when I add more files to the input, got the following exception:

    java.lang.RuntimeException: org.apache.beam.sdk.coders.CoderException: cannot encode a null String
    	at org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:280)
    	at org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)
    	at org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)
    	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:621)
    	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:609)
    	at com.spotify.scio.util.Functions$$anon$3.processElement(Functions.scala:158)
    Caused by: org.apache.beam.sdk.coders.CoderException: cannot encode a null String
    	at org.apache.beam.sdk.coders.StringUtf8Coder.getEncodedElementByteSize(StringUtf8Coder.java:136)
    	at org.apache.beam.sdk.coders.StringUtf8Coder.getEncodedElementByteSize(StringUtf8Coder.java:37)
    	at org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
    	at com.spotify.scio.coders.RecordCoder.registerByteSizeObserver(Coder.scala:279)
    	at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:564)
    	at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:480)
    	at org.apache.beam.runners.dataflow.worker.IntrinsicMapTaskExecutorFactory$ElementByteSizeObservableCoder.registerByteSizeObserver(IntrinsicMapTaskExecutorFactory.java:399)
    	at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputObjectAndByteCounter.update(OutputObjectAndByteCounter.java:125)
    	at org.apache.beam.runners.dataflow.worker.DataflowOutputCounter.update(DataflowOutputCounter.java:64)
    	at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:43)
    	at org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:272)
    	at org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)
    	at org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)
    	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:621)
    	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:609)
    	at com.spotify.scio.util.Functions$$anon$3.processElement(Functions.scala:158)
    	at com.spotify.scio.util.Functions$$anon$3$DoFnInvoker.invokeProcessElement(Unknown Source)
    	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:275)
    	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:240)
    	at org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:325)
    	at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
    	at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
    	at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201)
    	at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
    	at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:76)
    	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:394)
    	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:363)
    	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:291)
    	at org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:135)
    	at org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:115)
    	at org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:102)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

I guess one of my input files may include some malformed data. But how to bypass the bad data?
I tried this:

    val scText = sc.textFile(input)
    scText.setCoder(NullableCoder.of(StringUtf8Coder.of())) 

It didn't help. Can someone help me on this?

**Comment by ClaireMcGinty** [comment]
Hi! looks like your coder isn't getting correctly set for the textFile transform. Can you try setting the `nullableCoders` flag in your [ScioOptions](https://github.com/spotify/scio/blob/master/scio-core/src/main/java/com/spotify/scio/options/ScioOptions.java#L68) instance? When this flag is set, Beam coders will be automatically wrapped in a `NullableCoder` for you.

Example:

```
scala> import org.apache.beam.sdk.options.{PipelineOptionsFactory, PipelineOptions}

scala> val listWithNull: List[String] = List("foo", null.asInstanceOf[String])
scala> val scWithNullableCoders = ScioContext(PipelineOptionsFactory.fromArgs("--nullableCoders=true").create())
scala> val scWithoutNullableCoders = ScioContext()

scala> scWithNullableCoders.parallelize(listWithNull).materialize
res11: scala.concurrent.Future[com.spotify.scio.io.Tap[String]] = Future(<not completed>)

scala> scWithoutNullableCoders.parallelize(listWithNull)
com.spotify.scio.coders.CoderException: cannot encode a null String
  at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:74)
  at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:37)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:203)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:203)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:203)

scala> scWithoutNullableCoders.parallelize(listWithNull).setCoder(NullableCoder.of(StringUtf8Coder.of()))
com.spotify.scio.coders.CoderException: cannot encode a null String
  at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:74)
  at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:37)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:203)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:203)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:203)
```

let me know if that solves your issue!

**Comment by git4sun** [comment]
it worked. Thanks @ClaireMcGinty .

**Comment by omarzouk** [comment]
why, is this *not* default behaviour? this is such a hidden cause of errors for anyone migrating from older versions of scio. It is not even mentioned in the migration guide.
