### ISSUE TITLE
saveAsDynamicAvroFile throws NullPointerException using DataflowRunner

### ISSUE THREAD

**Issue by ajablonski** [spotify/scio#1783]
Hey there!

I'm seeing the following exception crop up when I have a pipeline that uses `saveAsDynamicAvroFile` on Dataflow. 

```
[ForkJoinPool-1-worker-5] ERROR org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler - 2019-03-27T15:14:05.473Z: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.common.io.BaseEncoding$StandardBaseEncoding.trimTrailingPadding(BaseEncoding.java:676)
	at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:231)
	at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:217)
	at com.google.api.client.util.Base64.decodeBase64(Base64.java:93)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.ByteArrayShufflePosition.fromBase64(ByteArrayShufflePosition.java:42)
	at org.apache.beam.runners.dataflow.worker.GroupingShuffleReader$GroupingShuffleReaderIterator.<init>(GroupingShuffleReader.java:239)
	at org.apache.beam.runners.dataflow.worker.GroupingShuffleReader.iterator(GroupingShuffleReader.java:177)
	at org.apache.beam.runners.dataflow.worker.GroupingShuffleReader.iterator(GroupingShuffleReader.java:130)
	at org.apache.beam.runners.dataflow.worker.GroupingShuffleReader.iterator(GroupingShuffleReader.java:69)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:178)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:76)
	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:394)
	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:363)
	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:291)
	at org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:135)
	at org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:115)
	at org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

And here's a pipeline that should (hopefully) let folks reproduce the issue:

```scala
object TestDynamicSave {
  def main(cmdLineArgs: Array[String]): Unit = {
    val (sc, args) = ContextAndArgs(cmdLineArgs)

    val output = args("output")

    sc.parallelize(Array(
      SampleRecord.newBuilder()
        .setField1("A")
        .setField2("1")
        .setField3("message1")
        .build(),
      SampleRecord.newBuilder()
        .setField1("A")
        .setField2("2")
        .setField3("message2")
        .build(),
      SampleRecord.newBuilder()
        .setField1("B")
        .setField2("1")
        .setField3("message3")
        .build(),
      SampleRecord.newBuilder()
        .setField1("B")
        .setField2("2")
        .setField3("message4")
        .build()
    ))
      .saveAsDynamicAvroFile(output, schema = SampleRecord.getClassSchema)(sampleRecord => {
        s"${sampleRecord.getField1}-${sampleRecord.getField2}"
      })

    sc.close().waitUntilDone()
  }
}
```

`SampleRecord` is a simple Avro-generated class that has 3 string fields -- `field1`, `field2`, and `field3`, and you can see that they're all populated here. The issue doesn't appear when using the `DirectRunner`. I'm using Scio 0.7.4, but have also seen the issue in Scio 0.7.1. 

I got the same error when I built something similar on my own (before I knew about `saveAsDynamicAvroFile`), so I suppose it's possible that it's a Beam issue -- if so, any pointers in that direction would be useful.

Thanks!

**Comment by nevillelyh** [comment]
Can't reproduce this on latest master, using project settings in `scio-examples`. Can you double check your project setting to rule out any dependency or configuration related issues?

**Comment by ajablonski** [comment]
Yup -- looks like a dependency issue -- a separate part of the project where I was testing this depended on a version of `com.google.cloud:google-cloud-storage` that (transitively) evicted the older version  of `com.google.apis:google-api-services-storage` used by `beam-runners-google-cloud-dataflow-java`. On further research, it breaks when just writing a standard Avro output; switching to an older, compatible version of `com.google.cloud:google-cloud-storage` fixed the problem.

Sorry for the trouble, and thanks for helping look into this.

**Comment by ajablonski** [comment]
For posterity's sake, here's the particular combination of dependencies that caused the problem for me:

Scio: 0.7.1/0.7.4
Beam/Beam Dataflow runner: 2.9.0
Google cloud storage (com.google.cloud:google-cloud-storage): 1.64.0

I was also using Scala 2.11.11 and Scala Macros 2.1.0, but those seemed extraneous to the issue.

Switching to Google cloud storage 1.61.0 resolved this.

**Comment by billstark** [comment]
I was having the same issue when trying to read data from Pub/Sub. My dependency setting is as follows:

Scio: 0.8.0-beta2
Beam/Beam Dataflow runner: 2.15.0
Google cloud storage (com.google.cloud:google-cloud-storage): 1.64.0

With @ajablonski 's suggestion, I have changed the version for Google cloud storage to 1.61.0 and the issues was resolved as well.

**Comment by dietervdw-spotify** [comment]
Does that mean upgrading post could-storage 1.61.0 is simply a no-go?
This is dependent on the Beam version I guess?

**Comment by simeg** [comment]
We fixed this by upgrading `google-http-java-client` to `1.34.0` like @dietervdw-spotify mentioned.
