### ISSUE TITLE
sampleByKey tests fail in Travis

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#18]
```
[info] - should support sampleByKey()
Exception in thread "Thread-10" Exception in thread "Thread-14" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2598)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:795)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:784)
	at java.lang.Thread.run(Thread.java:745)
java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2598)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at sbt.React.react(ForkTests.scala:114)
	at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
	at java.lang.Thread.run(Thread.java:745)
[info] Run completed in 23 seconds, 252 milliseconds.
[info] Total number of tests run: 124
[info] Suites: completed 6, aborted 0
[info] Tests: succeeded 123, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
```

**Comment by nevillelyh** [comment]
Fixed in https://github.com/spotify/scio/commit/2e21e803c500271ca5550eac59112655779238ac

**Comment by nevillelyh** [comment]
Duplicate of #21
