### ISSUE TITLE
Cannot use DML using BigQuery client

### ISSUE THREAD

**Issue by Tomczik76** [spotify/scio#1925]
I'm getting an error if I use the BigQuery client for running a query that does a `DELETE` query.

```
scala>     bigQueryClient.query.run(query, createDisposition = null)
[run-main-0] INFO com.spotify.scio.bigquery.client.QueryOps$ - Executing standard SQL query (INTERACTIVE): `delete from `XXXXXXX`
            where
              user_key = 'XXXXX'
              and object_id = 'XXXXXXXX'
         `
[run-main-0] ERROR com.spotify.scio.bigquery.client.QueryOps$ - Standard syntax failed due to:
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "q",
    "locationType" : "parameter",
    "message" : "Cannot set create disposition in jobs with DML statements",
    "reason" : "invalidQuery"
  } ],
  "message" : "Cannot set create disposition in jobs with DML statements",
  "status" : "INVALID_ARGUMENT"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:417)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1132)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:515)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:448)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
        at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1$1.apply(QueryOps.scala:230)
        at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1$1.apply(QueryOps.scala:215)
        at scala.util.Try$.apply(Try.scala:192)
        at com.spotify.scio.bigquery.client.QueryOps.com$spotify$scio$bigquery$client$QueryOps$$run$1(QueryOps.scala:215)
        at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1.apply(QueryOps.scala:238)
        at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1.apply(QueryOps.scala:238)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
        at com.spotify.scio.bigquery.client.QueryOps.com$spotify$scio$bigquery$client$QueryOps$$run(QueryOps.scala:238)
        at com.spotify.scio.bigquery.client.QueryOps.isLegacySql(QueryOps.scala:256)
        at com.spotify.scio.bigquery.client.QueryOps.run(QueryOps.scala:193)
        at $line32.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<init>(<console>:40)
        at $line32.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<clinit>(<console>)
        at $line32.$eval$.$print$lzycompute(<console>:7)
        at $line32.$eval$.$print(<console>:6)
        at $line32.$eval.$print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:819)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:691)
        at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:425)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:993)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:891)
        at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:1004)
        at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
        at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:82)
        at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
        at sbt.Logger$$anon$4.apply(Logger.scala:84)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:748)
[run-main-0] ERROR com.spotify.scio.bigquery.client.QueryOps$ - Legacy syntax failed due to:
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "q",
    "locationType" : "parameter",
    "message" : "1.1 - 4.96: Unrecognized token delete.\n[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)]",
    "reason" : "invalidQuery"
  } ],
  "message" : "1.1 - 4.96: Unrecognized token delete.\n[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)]",
  "status" : "INVALID_ARGUMENT"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:417)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1132)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:515)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:448)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
        at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1$1.apply(QueryOps.scala:230)
        at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1$1.apply(QueryOps.scala:215)
        at scala.util.Try$.apply(Try.scala:192)
        at com.spotify.scio.bigquery.client.QueryOps.com$spotify$scio$bigquery$client$QueryOps$$run$1(QueryOps.scala:215)
        at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1.apply(QueryOps.scala:238)
        at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1.apply(QueryOps.scala:238)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
        at com.spotify.scio.bigquery.client.QueryOps.com$spotify$scio$bigquery$client$QueryOps$$run(QueryOps.scala:238)
        at com.spotify.scio.bigquery.client.QueryOps.isLegacySql(QueryOps.scala:260)
        at com.spotify.scio.bigquery.client.QueryOps.run(QueryOps.scala:193)
        at $line32.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<init>(<console>:40)
        at $line32.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<clinit>(<console>)
        at $line32.$eval$.$print$lzycompute(<console>:7)
        at $line32.$eval$.$print(<console>:6)
        at $line32.$eval.$print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:819)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:691)
        at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:425)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:993)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:891)
        at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:1004)
        at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
        at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:82)
        at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
        at sbt.Logger$$anon$4.apply(Logger.scala:84)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:748)
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "q",
    "locationType" : "parameter",
    "message" : "1.1 - 4.96: Unrecognized token delete.\n[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)]",
    "reason" : "invalidQuery"
  } ],
  "message" : "1.1 - 4.96: Unrecognized token delete.\n[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)]",
  "status" : "INVALID_ARGUMENT"
}
  at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
  at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
  at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
  at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:417)
  at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1132)
  at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:515)
  at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:448)
  at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
  at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1$1.apply(QueryOps.scala:230)
  at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1$1.apply(QueryOps.scala:215)
  at scala.util.Try$.apply(Try.scala:192)
  at com.spotify.scio.bigquery.client.QueryOps.com$spotify$scio$bigquery$client$QueryOps$$run$1(QueryOps.scala:215)
  at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1.apply(QueryOps.scala:238)
  at com.spotify.scio.bigquery.client.QueryOps$$anonfun$com$spotify$scio$bigquery$client$QueryOps$$run$1.apply(QueryOps.scala:238)
  at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
  at com.spotify.scio.bigquery.client.QueryOps.com$spotify$scio$bigquery$client$QueryOps$$run(QueryOps.scala:238)
  at com.spotify.scio.bigquery.client.QueryOps.isLegacySql(QueryOps.scala:260)
  at com.spotify.scio.bigquery.client.QueryOps.run(QueryOps.scala:193)
  ... 42 elided

```

**Comment by martellj** [comment]
I am working on proposing a solution to this issue.

**Comment by mewppis** [comment]
@martellj Do you have any update on this?
