### ISSUE TITLE
NullPointerException thrown when running private method "QueryOps.isInvalidQuery"

### ISSUE THREAD

**Issue by martellj** [spotify/scio#1929]
Periodically when running a query without either the `#standardSql` or `#legacySql` comments in the query, we are receiving the following stack trace:

```
java.lang.NullPointerException
	at com.spotify.scio.bigquery.client.QueryOps.com$spotify$scio$bigquery$client$QueryOps$$isInvalidQuery(QueryOps.scala:245)
	at com.spotify.scio.bigquery.client.QueryOps.isLegacySql(QueryOps.scala:258)
	at com.spotify.scio.bigquery.client.QueryOps.run(QueryOps.scala:193)
	at com.dowjones.dna.dataflow.snapshot.Query$$anonfun$1.apply(Query.scala:89)
	at com.dowjones.dna.dataflow.snapshot.Query$$anonfun$1.apply(Query.scala:89)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

One of the following getters is returning `null`:

`e.getDetails.getErrors.get(0).getReason`

This issue appears to be the result of intermittent failures from BigQuery. Looking at the documentation for `GoogleJsonError`.  It appears `getDetails`, `getErrors` and `getReason` can return `null`.

**Comment by martellj** [comment]
PR: https://github.com/spotify/scio/pull/1930

**Comment by nevillelyh** [comment]
Can you provide a repro-able query using a public dataset?

**Comment by martellj** [comment]
@nevillelyh unfortunately I can't.  The issue only appears intermittently and the NPE is suppressing the underlying exception.

**Comment by martellj** [comment]
@regadas Should I close this issue?

**Comment by regadas** [comment]
@martellj Thanks!
