### ISSUE TITLE
SQL join using interpolation with aliases

### ISSUE THREAD

**Issue by anish749** [spotify/scio#1951]
I am trying out the sql thing:
Scio v0.8.0-SNAPSHOT (after the alpha release)
The following code works:
```
    val s: SCollection[User] = thousand.users
    val a: SCollection[Artist] = thousand.artists

    val z = tsql"SELECT s.* FROM $s as s INNER JOIN $a as a ON $s.userId = $a.artistId"
      .as[User]
```

The following code doesn't
```
    val s: SCollection[User] = thousand.users
    val a: SCollection[Artist] = thousand.artists

    val z = sql"SELECT s.* FROM $s as s INNER JOIN $a as a ON $s.userId = $a.artistId"
      .as[User]
```

Looks like when using `sql` interpolator, aliasing "as s" doesn't work.

The following works:
```
    val s: SCollection[User] = thousand.users
    val a: SCollection[Artist] = thousand.artists

    val z = sql"SELECT SCOLLECTION_2.* FROM $s INNER JOIN $a ON $s.userId = $a.artistId"
      .as[User]
```

Bioler plate [here](https://gist.github.com/anish749/fd12ee02f32c7df7e2b08ccc0b89ed55#file-qscio-scala-L63-L72)

case class definitions [here](https://gist.github.com/anish749/fd12ee02f32c7df7e2b08ccc0b89ed55#file-qscio-scala-L158-L173)

```
Exception in thread "main" java.lang.RuntimeException: 
SqlValidatorException: Table 'SCOLLECTION_2' not found

Query:
SELECT s.* FROM  SCOLLECTION_2 as s INNER JOIN  SCOLLECTION_3 as a ON  SCOLLECTION_2.userId =  SCOLLECTION_3.artistId 


schema of SCOLLECTION_2:
┌──────────────────────────────────────────┬──────────┬──────────┐
│ NAME                                     │ TYPE     │ NULLABLE │
├──────────────────────────────────────────┼──────────┼──────────┤
│ userId                                   │ STRING   │ NO       │
│ userIdLong                               │ INT64    │ NO       │
│ fields                                   │ STRING[] │ NO       │
└──────────────────────────────────────────┴──────────┴──────────┘
        

schema of SCOLLECTION_3:
┌──────────────────────────────────────────┬──────────┬──────────┐
│ NAME                                     │ TYPE     │ NULLABLE │
├──────────────────────────────────────────┼──────────┼──────────┤
│ artistId                                 │ STRING   │ NO       │
│ artistIdLong                             │ INT64    │ NO       │
│ artistName                               │ STRING   │ NO       │
│ fields                                   │ STRING[] │ NO       │
└──────────────────────────────────────────┴──────────┴──────────┘
        
Query result schema (inferred) is unknown.
Expected schema:
┌──────────────────────────────────────────┬──────────┬──────────┐
│ NAME                                     │ TYPE     │ NULLABLE │
├──────────────────────────────────────────┼──────────┼──────────┤
│ userId                                   │ STRING   │ NO       │
│ userIdLong                               │ INT64    │ NO       │
│ fields                                   │ STRING[] │ NO       │
└──────────────────────────────────────────┴──────────┴──────────┘
        
	at com.spotify.scio.sql.SqlSCollection2$$anonfun$queryAs$2.apply(Query2.scala:134)
	at com.spotify.scio.sql.SqlSCollection2$$anonfun$queryAs$2.apply(Query2.scala:134)
	at scala.util.Either.fold(Either.scala:189)
	at com.spotify.scio.sql.SqlSCollection2.queryAs(Query2.scala:134)
	at com.spotify.scio.sql.SQLBuilders$$anon$2.as(SQLBuilders.scala:60)
	at benchmark.ExpressionJoin$.$anonfun$main$1(ExpressionJoin.scala:12)
	at benchmark.ExpressionJoin$.$anonfun$main$1$adapted(ExpressionJoin.scala:7)
	at qscio.DataflowBenchmark.benchLocal(DataflowBenchmark.scala:68)
	at qscio.DataflowBenchmark.benchLocal$(DataflowBenchmark.scala:63)
	at benchmark.ExpressionJoin$.benchLocal(ExpressionJoin.scala:6)
	at benchmark.ExpressionJoin$.main(ExpressionJoin.scala:7)
	at benchmark.ExpressionJoin.main(ExpressionJoin.scala)
Caused by: org.apache.beam.sdk.extensions.sql.impl.ParseException: Unable to parse query SELECT s.* FROM  SCOLLECTION_2 as s INNER JOIN  SCOLLECTION_3 as a ON  SCOLLECTION_2.userId =  SCOLLECTION_3.artistId 
	at org.apache.beam.sdk.extensions.sql.impl.BeamSqlEnv.parseQuery(BeamSqlEnv.java:145)
	at org.apache.beam.sdk.extensions.sql.SqlTransform.expand(SqlTransform.java:111)
	at org.apache.beam.sdk.extensions.sql.SqlTransform.expand(SqlTransform.java:79)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:537)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:488)
	at org.apache.beam.sdk.values.PCollectionTuple.apply(PCollectionTuple.java:261)
	at com.spotify.scio.sql.SqlSCollection2.query(Query2.scala:116)
	at com.spotify.scio.sql.SqlSCollection2.query(Query2.scala:105)
	at com.spotify.scio.sql.SqlSCollection2.queryAs(Query2.scala:131)
	... 8 more
Caused by: org.apache.beam.repackaged.beam_sdks_java_extensions_sql.org.apache.calcite.tools.ValidationException: org.apache.beam.repackaged.beam_sdks_java_extensions_sql.org.apache.calcite.runtime.CalciteContextException: From line 1, column 72 to line 1, column 84: Table 'SCOLLECTION_2' not found
	at org.apache.beam.repackaged.beam_sdks_java_extensions_sql.org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:190)
	at org.apache.beam.sdk.extensions.sql.impl.BeamQueryPlanner.convertToBeamRel(BeamQueryPlanner.java:123)
	at org.apache.beam.sdk.extensions.sql.impl.BeamSqlEnv.parseQuery(BeamSqlEnv.java:143)
	... 16 more
```

**Comment by regadas** [comment]
Hi @anish749 I just tested this agains master and I was unable to replicate it ... I was using this example 

```scala
    val s: SCollection[User] = thousand.users
    val a: SCollection[Artist] = thousand.artists

    val z = tsql"SELECT s.* FROM $s as s INNER JOIN $a as a ON $s.userId = $a.artistId"
      .as[User]
````

**Comment by anish749** [comment]
@regadas Yes, the interpolator with `tsql` works fine
Can you try
```
    val s: SCollection[User] = thousand.users
    val a: SCollection[Artist] = thousand.artists

    val z = sql"SELECT s.* FROM $s as s INNER JOIN $a as a ON $s.userId = $a.artistId"
      .as[User]
```

This is using the `sql` interpolator.

**Comment by regadas** [comment]
Ah yes! 🤦‍♂ took the wrong example by mistake!

**Comment by regadas** [comment]
@anish749 found out what is going on. At first glance `sql` is correct but it's actually not!

either do this:
```diff
- sql"SELECT s.* FROM $s as s INNER JOIN $a as a ON $s.userId = $a.artistId"
+ sql"SELECT s.* FROM $s as s INNER JOIN $a as a ON s.userId = a.artistId"
```
or:
```diff
- sql"SELECT s.* FROM $s as s INNER JOIN $a as a ON $s.userId = $a.artistId"
+ sql"SELECT $s.* FROM $s INNER JOIN $a ON $s.userId = $a.artistId"
```

as soon as you use `as` you are renaming/aliasing the table, you need to keep using that otherwise the underlying table name will be used `SCOLLECTION_X` and because it was renamed it's not available.

A take from this issue is that we can try improve the error message.

**Comment by anish749** [comment]
Thanks for taking a look.
May be use the variable name instead of the `SCOLLECTION_X` (not sure if that is possible).
I wasn't able to find any doc in the code when looking up the functions, so I was making wild guesses.

**Comment by anish749** [comment]
@regadas I thought about this a bit, I feel that `tsql` and `sql` _should_ follow similar semantics. It might be confusing as a user to remember when alias when using `tsql` / `sql`

I am not sure which form of aliasing comes more naturally.

**Comment by regadas** [comment]
@anish749 they kinda of follow the same semantics aliasing works the same in both `tsql` and `sql`. The only difference is the underlying collection name in `tsql` is the variable name itself while on `sql` since it's interpolated and it's not possible to infer the variable name we use the `SCOLLECTION_X` name.

**Comment by nevillelyh** [comment]
So looks like `sql` is working as desired. Should this be a `wontfix` then? The behavior & error message can be a bit confusing though.
