### ISSUE TITLE
Exception-wrapping in Coder breaks SynchronousChainedCombinedDriver under Flink

### ISSUE THREAD

**Issue by cchepelov** [spotify/scio#2024]
While trying to do a fairly simple outer join job:
```scala
val left = readCSV[LeftRecord](leftInputPath)
val right = readCSV[RightRecord](leftInputPath)

val leftByKey = left.map(v => v.key -> v)
val rightByKey = right.flatMap(v => v.maybeKey.map(key => key -> v))

// key is of type "case class Isrc(value: String)" which has appropriate Kryo

val joined = leftByKey.fullOuterJoin(rightByKey)

joined
   .map { case (key, pair) => pair.toString }
   .saveAsTextFile("foo.txt")
sc.close()
```
on very small inputs (40-70K lines each, 0 to 1 lines per key, very rarely a couple more), the job crashes quickly under Flink (both local and remote)

The immediately apparent error is an `EOFException`, even though the fact is not immediately obvious upon inspection:

```
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:146)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:265)
	... 22 common frames omitted
Caused by: com.spotify.scio.coders.CoderException: null
	at org.apache.flink.runtime.io.disk.SimpleCollectingOutputView.nextSegment(SimpleCollectingOutputView.java:79)
```  

> (yes, the report says it's a `CoderException` yet the code at https://github.com/apache/flink/blob/master/flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/SimpleCollectingOutputView.java#L79 clearly says `EOFException` )

```text
	at org.apache.flink.runtime.memory.AbstractPagedOutputView.advance(AbstractPagedOutputView.java:137)
	at org.apache.flink.runtime.memory.AbstractPagedOutputView.write(AbstractPagedOutputView.java:198)
	at org.apache.beam.runners.flink.translation.wrappers.DataOutputViewWrapper.write(DataOutputViewWrapper.java:48)
	at com.esotericsoftware.kryo.io.Output.flush(Output.java:163)
	at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:45)
	at com.twitter.chill.TraversableSerializer.$anonfun$write$1(Traversable.scala:31)
	at com.twitter.chill.TraversableSerializer.$anonfun$write$1$adapted(Traversable.scala:27)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.twitter.chill.TraversableSerializer.write(Traversable.scala:27)
	at com.twitter.chill.TraversableSerializer.write(Traversable.scala:21)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)
	at com.spotify.scio.coders.KryoAtomicCoder$$anonfun$encode$1.apply(KryoAtomicCoder.scala:141)
	at com.spotify.scio.coders.KryoAtomicCoder$$anonfun$encode$1.apply(KryoAtomicCoder.scala:131)
	at com.spotify.scio.coders.KryoAtomicCoder$.withKryoState(KryoAtomicCoder.scala:274)
	at com.spotify.scio.coders.KryoAtomicCoder.encode(KryoAtomicCoder.scala:131)
	at org.apache.beam.sdk.coders.Coder.encode(Coder.java:136)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:211)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:211)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:211)
	at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:195)
	at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:211)
	at org.apache.beam.sdk.transforms.join.UnionCoder.encode(UnionCoder.java:71)
	at org.apache.beam.sdk.transforms.join.UnionCoder.encode(UnionCoder.java:32)
	at org.apache.beam.sdk.coders.KvCoder.encode(KvCoder.java:71)
	at org.apache.beam.sdk.coders.KvCoder.encode(KvCoder.java:36)
	at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.encode(WindowedValue.java:529)
	at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.encode(WindowedValue.java:520)
	at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.encode(WindowedValue.java:480)
	at org.apache.beam.runners.flink.translation.types.CoderTypeSerializer.serialize(CoderTypeSerializer.java:85)
	at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.serialize(TupleSerializer.java:125)
	at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.serialize(TupleSerializer.java:30)
	at org.apache.flink.runtime.operators.sort.NormalizedKeySorter.write(NormalizedKeySorter.java:281)
	at org.apache.flink.runtime.operators.chaining.SynchronousChainedCombineDriver.collect(SynchronousChainedCombineDriver.java:169)
	at org.apache.flink.runtime.operators.util.metrics.CountingCollector.collect(CountingCollector.java:35)
	at org.apache.flink.runtime.operators.chaining.ChainedMapDriver.collect(ChainedMapDriver.java:79)
	at org.apache.flink.runtime.operators.util.metrics.CountingCollector.collect(CountingCollector.java:35)
	at org.apache.flink.api.java.operators.translation.PlanFilterOperator$FlatMapFilter.flatMap(PlanFilterOperator.java:58)
	at org.apache.flink.runtime.operators.FlatMapDriver.run(FlatMapDriver.java:109)
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:503)
	at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:368)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)
	... 1 common frames omitted
Caused by: com.spotify.scio.coders.CoderException$$anon$1:  - Coder was materialized at
	at com.spotify.scio.coders.CoderMaterializer$.beam(CoderMaterializer.scala:51)
	at com.spotify.scio.coders.CoderMaterializer$.beam(CoderMaterializer.scala:27)
	at com.spotify.scio.coders.CoderMaterializer$.kvCoder(CoderMaterializer.scala:80)
	at com.spotify.scio.values.PairSCollectionFunctions.toKV(PairSCollectionFunctions.scala:93)
	at com.spotify.scio.util.ArtisanJoin$.cogroupImpl(ArtisanJoin.scala:74)
	at com.spotify.scio.util.ArtisanJoin$.joinImpl(ArtisanJoin.scala:104)
	at com.spotify.scio.util.ArtisanJoin$.outer(ArtisanJoin.scala:154)
	at com.spotify.scio.values.PairSCollectionFunctions.fullOuterJoin(PairSCollectionFunctions.scala:256)
	at com.transparencyrights.Xxxxx.run(Xxxxx.scala:54)
```

Drilling down: 

1. `flink.SimpleCollectingOutputView.nextSegment()` throws `EOFException()` due to the depletion of a fixed-size memory buffer. (I have suggested https://github.com/apache/flink/pull/8981 to provide a clearer message than 'null')
2. the error is caught and rethrown a couple times as some internal Kryo buffers are rolled back, to cancel the effect of a potentially partially written Kryo object tree. During that, it is encapsulated into a KryoException which is then decapsulated as the exception leaves the Kryo stack.
3. Scio's `WrappedBCoder.catching` catches the `EOFException` (which is still the original exception thrown from `flink.SimpleCollectingOutputView.nextSegment()`, **and wraps it into a `CoderException`**
4. as we can see in the stack above, Scio's `WrappedBCoder` was actually called by BEAM's FullWindowedValueCoder, which was called by Flink's TupleSerializer
5. Flink's TupleSerializer was called by Flink's `NormalizedKeySorter.write`
6. Flink's `NormalizedKeySorter.write` is instructed to catch `EOFException`, and turns it into a "false" result. This "false" result is used by Flink's `SynchronousChainedCombineDriver.collect` to flush out some buffers, free up some memory, and carry on.

Now, due to step (3), step (6) fails and the `CoderException(EOFException) keeps traveling up the call stack, until the job is aborted.

Step (1) is a bit weird from the point of view of step (3) as the latter clearly doesn't expect a Coder to do more than flatten objects into bytes, but Flink's intricate memory management tries very hard to avoid copies and memory pressure.

I see few easy solutions here. 

**[A]** Can I modify `WrappedBCoder` so that it wraps all exceptions *except* EOFException, with a comment to the effect we sacrifice the materializer logging due to the use of EOFException for internal signalling within the Flink runner? This feels… A bit gross, but the materialization location is too useful to leave out.

**[B]** As an alternative, since `Throwable.setStackTrace()` is public, would the following make sense:
   - actually *alter and rethrow* the caught exception in `WrappedBCoder.catching`
   - the materialization stack trace gets appended at the end of the caught exception, before it gets rethrown
   - CoderException isn't private; it will have to be @deprecated for a while. There won't be any CoderException thrown anymore.

**[C]** this one is ugly, but `CoderException$` already started playing this game. Implement **[A]** or **[B]** if there is a trace of Flink anywhere in the caught call stack, otherwise keep wrapping exceptions as usual.

I can't say I really like [C]. It's a form of per-backend subclassing hidden in complexity. [A] isn't very regular, as it promotes `EOFException` to something special that escapes the normal `CoderException` wrapping, which is not useful in a non-Flink context and hopes that Flink doesn't use any other exception. [B] would be the most regular, but it means an effective change of API for all consumers. On the other hand, there is no instance of something catching specifically `scio.CoderException` in scio's code base. WDYT?

**Comment by jto** [comment]
Hi @cchepelov.
Thanks for opening the issue and for the analysis. 
To be honest I'm not really sure what to do here. [B] does seem to be the least terrible option but it's clearly not good...
@nevillelyh wdyt ?

**Comment by cchepelov** [comment]
Yup, after a good night's rest, I went ahead and implemented [B] (temporarily? limited to EOFException) in https://github.com/spotify/scio/pull/2025 — this got me to succesful completion in both local and remote Flink. The good news is that there were no changes required in either Flink or BEAM.

**Comment by nevillelyh** [comment]
Yeah I agree [B] is the best solution out of the three. I don't think many users catch `CoderException` so probably worth breaking. Plus it'll be part of 0.8 so it's acceptable.

**Comment by cchepelov** [comment]
Thanks for the feedback Neville. Will update the PR accordingly (12 hours 
from now)

**Comment by cchepelov** [comment]
done (tests 'fail' in the PR due to a lack of credits in CircleCI (?), dunno if I can resolve this on my end)
