### ISSUE TITLE
Fix NoClassDefFoundError ShutdownHookManager in tests

### ISSUE THREAD

**Issue by regadas** [spotify/scio#2096]
This does not affect the outcome of the test ... but can be misleading. I think this appeared with the latest `Beam` version.

```
Exception in thread "Thread-43" java.lang.NoClassDefFoundError: org/apache/hadoop/util/ShutdownHookManager$2
	at org.apache.hadoop.util.ShutdownHookManager.getShutdownHooksInOrder(ShutdownHookManager.java:124)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:52)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.util.ShutdownHookManager$2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by nevillelyh** [comment]
How did Hadoop deps got pulled in? Through cassandra/parquet but affects everything since they all share the same JVM & hence shutdown hook?

**Comment by regadas** [comment]
the culprit here seems to really be `sbt 1.3.0-RC3`

**Comment by LukaszByczynski** [comment]
Solution for fix that issue:

add `-Dsbt.classloader.close=false` to .sbtopts

https://github.com/sbt/sbt/issues/4794

**Comment by regadas** [comment]
Oh cool! I missed that! Thanks for the pointer @LukaszByczynski
