### ISSUE TITLE
NoSuchMethodError when flink run

### ISSUE THREAD

**Issue by cecol** [spotify/scio#2171]
My project depends on 
```
scalaVersion := "2.12.4"
val beamVersion = "2.12.0"
val scioVersion = "0.8.0-alpha1"
val flinkVersion = "1.7.2"
```
`runMain xxx.MyMain --runner=FlinkRunner` in sbt console can work.
But I try `flink run -c xxx.MyMain -m localhost:8081 my-project-assembly-0.1.jar --runner=FlinkRunner`, it fails with
```
java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at com.spotify.scio.coders.Beam.<init>(Coder.scala:64)
	at com.spotify.scio.coders.Beam$.apply(Coder.scala:64)
	at com.spotify.scio.coders.CoderGrammar.beam(Coder.scala:381)
	at com.spotify.scio.coders.CoderGrammar.beam$(Coder.scala:380)
	at com.spotify.scio.coders.Coder$.beam(Coder.scala:446)
	at com.spotify.scio.coders.instances.ScalaCoders.shortCoder(ScalaCoders.scala:355)
	at com.spotify.scio.coders.instances.ScalaCoders.shortCoder$(ScalaCoders.scala:354)
	at com.spotify.scio.coders.Coder$.shortCoder(Coder.scala:446)
	at com.spotify.scio.coders.instances.JavaCoders.$init$(JavaCoders.scala:82)
	at com.spotify.scio.coders.Coder$.<init>(Coder.scala:446)
	at com.spotify.scio.coders.Coder$.<clinit>(Coder.scala)
	at com.momagic.dmp.adgyde.log.AdgydeUserLogs$.<init>(AdgydeUserLogs.scala:35)
	at com.momagic.dmp.adgyde.log.AdgydeUserLogs$.<clinit>(AdgydeUserLogs.scala)
	at com.momagic.dmp.adgyde.log.AdgydeUserLogs.main(AdgydeUserLogs.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:423)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:813)
	at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:287)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:213)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1050)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$11(CliFrontend.java:1126)
	at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1126)
``` 

`my-project-assembly-0.1.jar` is made from `sbt clean assembly` with following configurations:
```
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", _*) => MergeStrategy.discard
  case p
    if p.toLowerCase.contains("license")
      || p.toLowerCase.contains("readme")
      || p.toLowerCase.contains("notice") =>
    MergeStrategy.discard
  case p
    if p.endsWith("pem")
      || p.endsWith("key")
      || p.endsWith("cnf")
      || p.endsWith(".proto")
      || p.endsWith("txt") =>
    MergeStrategy.first
  case p if p.equals("log4j.properties") || p.equals("reference.conf") => MergeStrategy.concat
  case PathList("com", "esotericsoftware", "kryo", _*) => MergeStrategy.first
  case PathList("com", "esotericsoftware", "minlog", _*) => MergeStrategy.first
  case PathList("com", "esotericsoftware", "reflectasm", _*) => MergeStrategy.first
  case PathList("com", "google", "cloud", "bigtable", "data", "v2", _*) => MergeStrategy.first
  case PathList("org", "apache", "beam", "sdk", "coders", _*) => MergeStrategy.first
  case PathList("org", "apache", "beam", "sdk", "util", _*) => MergeStrategy.first
  case PathList("org", "apache", "beam", "vendor", "grpc", "v1p13p1", _*) => MergeStrategy.first
  case PathList("pureconfig", _*) => MergeStrategy.first
  case _ => MergeStrategy.singleOrError
}
```
Otherwise it would conflict when building jar.

My Flink cluster is on k8s and the running image is `flink:1.7.2-scala_2.12`.
I can reach the web UI with `http://localhost:8001/api/v1/namespaces/default/services/flink-jobmanager:ui/proxy/#/jobmanager/config`

I have no idea how to deal with it
Can anyone help?

**Comment by regadas** [comment]
Hi @cecol this means that `scala-library` is not in the classpath. It seems that the assembly didn't included it somehow. You can try also `flink run -C <classpath>` and add the `scala-library.jar` there.

Anyway, this is a very old and stalled issue. Recently #2785 it was better support for `Flink` and `runMain xxx.MyMain --runner=FlinkRunner` works out of the box.

Closing this for now due to #2785
