### ISSUE TITLE
Investigate flaky AsyncLookupDoFn test?

### ISSUE THREAD

**Issue by ClaireMcGinty** [spotify/scio#2249]
This test has been really flaky locally for me (cc @benkogan has been having issues with it too?) The failing test is [AsyncLookupDoFnTest#work with failures](https://github.com/spotify/scio/blob/5c4833255caa476ba1328726cb59d4535cb865a8/scio-test/src/test/scala/com/spotify/scio/transforms/AsyncLookupDoFnTest.scala#L91):

```
[info]   org.apache.beam.sdk.util.IllegalMutationException: PTransform apply@{OutcomeOf.scala:85}623/ParMultiDo(FailingJavaLookup) mutated value KV{1, com.spotify.scio.transforms.BaseAsyncLookupDoFn$Try@1a85e4e7} after it was output (new value was KV{1, com.spotify.scio.transforms.BaseAsyncLookupDoFn$Try@388faea3}). Values must not be mutated in any way after being output.
[info]   at org.apache.beam.runners.direct.ImmutabilityCheckingBundleFactory$ImmutabilityEnforcingBundle.commit(ImmutabilityCheckingBundleFactory.java:134)
[info]   at org.apache.beam.runners.direct.EvaluationContext.commitBundles(EvaluationContext.java:210)
[info]   at org.apache.beam.runners.direct.EvaluationContext.handleResult(EvaluationContext.java:151)
[info]   at org.apache.beam.runners.direct.QuiescenceDriver$TimerIterableCompletionCallback.handleResult(QuiescenceDriver.java:262)


[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.finishBundle(DirectTransformExecutor.java:189)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:126)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   ...
[info]   Cause: org.apache.beam.sdk.util.IllegalMutationException: Value KV{1, com.spotify.scio.transforms.BaseAsyncLookupDoFn$Try@1a85e4e7} mutated illegally, new value was KV{1, com.spotify.scio.transforms.BaseAsyncLookupDoFn$Try@388faea3}. Encoding was AQD_____D0QBAGphdmEubGFuZy5SdW50aW1lRXhjZXB0aW_uAQEAAgFmYWlsdXJlsQEBWAEBAWphdmEudXRpbC5BcnJheUxpc_QBAAA, now AQD_____D7UJAQBqYXZhLmxhbmcuUnVudGltZUV4Y2VwdGlv7gEBAAIBZmFpbHVyZbEBEQEBY29tLnNwb3RpZnkuc2Npby50cmFuc2Zvcm1zLkZhaWxpbmdKYXZhTG9va3VwRG9G7gFBc3luY0xvb2t1cERvRm5UZXN0LnNjYWzh0gIBYXN5bmNMb29rdfABBgfAAggBAWNvbS5zcG90aWZ5LnNjaW8udHJhbnNmb3Jtcy5CYXNlQXN5bmNMb29rdXBEb0buAUJhc2VBc3luY0xvb2t1cERvRm4uamF24ZgCAXByb2Nlc3NFbGVtZW70AQFjb20uc3BvdGlmeS5zY2lvLnRyYW5zZm9ybXMuRmFpbGluZ0phdmFMb29rdXBEb0ZuJERvRm5JbnZva2XyAAEBaW52b2tlUHJvY2Vzc0VsZW1lbvQBAcUBb3JnLmFwYWNoZS5iZWFtLnJlcGFja2FnZWQuZGlyZWN0X2phdmEucnVubmVycy5jb3JlLlNpbXBsZURvRm5SdW5uZXIBU2ltcGxlRG9GblJ1bm5lci5qYXbhrAMQARIT4AINAQHWAW9yZy5hcGFjaGUuYmVhbS5yZXBhY2thZ2VkLmRpcmVjdF9qYXZhLnJ1bm5lcnMuY29yZS5TaW1wbGVQdXNoYmFja1NpZGVJbnB1dERvRm5SdW5uZXIBU2ltcGxlUHVzaGJhY2tTaWRlSW5wdXREb0ZuUnVubmVyLmphduGcAQFwcm9jZXNzRWxlbWVudEluUmVhZHlXaW5kb3fzAQFvcmcuYXBhY2hlLmJlYW0ucnVubmVycy5kaXJlY3QuUGFyRG9FdmFsdWF0b_IBUGFyRG9FdmFsdWF0b3IuamF24aYDDQEBzgFvcmcuYXBhY2hlLmJlYW0ucnVubmVycy5kaXJlY3QuRG9GbkxpZmVjeWNsZU1hbmFnZXJSZW1vdmluZ1RyYW5zZm9ybUV2YWx1YXRvcgFEb0ZuTGlmZWN5Y2xlTWFuYWdlclJlbW92aW5nVHJhbnNmb3JtRXZhbHVhdG9yLmphduFsDQEBb3JnLmFwYWNoZS5iZWFtLnJ1bm5lcnMuZGlyZWN0LkRpcmVjdFRyYW5zZm9ybUV4ZWN1dG_yAURpcmVjdFRyYW5zZm9ybUV4ZWN1dG9yLmphduHAAgFwcm9jZXNzRWxlbWVudPMBICH4AQFyde4BAWphdmEudXRpbC5jb25jdXJyZW50LkV4ZWN1dG9ycyRSdW5uYWJsZUFkYXB0ZfIBRXhlY3V0b3JzLmphduH-BwFjYWzsAQFqYXZhLnV0aWwuY29uY3VycmVudC5GdXR1cmVUYXPrAUZ1dHVyZVRhc2suamF24ZQEJAEBamF2YS51dGlsLmNvbmN1cnJlbnQuVGhyZWFkUG9vbEV4ZWN1dG_yAVRocmVhZFBvb2xFeGVjdXRvci5qYXbh-hEBcnVuV29ya2XyAQFqYXZhLnV0aWwuY29uY3VycmVudC5UaHJlYWRQb29sRXhlY3V0b3IkV29ya2XyLuAJJAEBamF2YS5sYW5nLlRocmVh5AFUaHJlYWQuamF24dgLJFgBAQFqYXZhLnV0aWwuQXJyYXlMaXP0AQAA.
[info]   at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.illegalMutation(MutationDetectors.java:153)
[info]   at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.verifyUnmodifiedThrowingCheckedExceptions(MutationDetectors.java:148)
[info]   at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.verifyUnmodified(MutationDetectors.java:123)
[info]   at org.apache.beam.runners.direct.ImmutabilityCheckingBundleFactory$ImmutabilityEnforcingBundle.commit(ImmutabilityCheckingBundleFactory.java:124)
[info]   at org.apache.beam.runners.direct.EvaluationContext.commitBundles(EvaluationContext.java:210)
[info]   at org.apache.beam.runners.direct.EvaluationContext.handleResult(EvaluationContext.java:151)
[info]   at org.apache.beam.runners.direct.QuiescenceDriver$TimerIterableCompletionCallback.handleResult(QuiescenceDriver.java:262)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.finishBundle(DirectTransformExecutor.java:189)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:126)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```

possibly related to my local java environment, since CircleCI runs are pretty reliable...

**Comment by nevillelyh** [comment]
It could be a red herring due to how `Try` roundtrips (or fails to) ser/de? IIRC `Exception` ser/de may not roundtrip since the stacktrace field is generated at class creation and might be different, i.e. actual error site vs inside mutation detector.

**Comment by ClaireMcGinty** [comment]
@nevillelyh I think you're right, the `Throwable` field of `Try` isn't roundtripping correctly -- the unit test succeeded when I experimented with (a) just storing the exception's String message, not the object itself, in `Try`, or (b) modifying [`jTryCoder`](https://github.com/spotify/scio/blob/87d9173f18c44b1843fe559ee6fc8eaddb1d525b/scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala#L83) to just use a Beam `SerializableCoder.of(classOf[BaseAsyncLookupDoFn.Try[A]])`, since we did make `Try` implement `Serializable`. I'm still not sure what makes this test flaky/why it succeeds on CircleCI!

**Comment by ClaireMcGinty** [comment]
A simple fix would be to add `k.addDefaultSerializer(classOf[Throwable], new JavaSerializer())` to the ScioKryoRegistrar and use the default Java serialization, but this blows up the size of the Throwable encoding. :(

**Comment by nevillelyh** [comment]
That should be fine if there aren't any better alternatives, assuming exceptions are uncommon and shouldn't go through shuffle in most cases.
