### ISSUE TITLE
SCollectionMatchers.containValue[T] requires T to be Serializable

### ISSUE THREAD

**Issue by drobert** [spotify/scio#2294]
When using the construct `mySColl should inWindow(foo) { containValue[T](bar) }`, the type `T` must be serializable or else the process fails with:
```
unable to serialize DoFnWithExecutionInformation{doFn=org.apache.beam.sdk.testing.PAssert$GroupedValuesCheckerDoFn@6367a688, mainOutputTag=Tag<output>, schemaInformation=DoFnSchemaInformation{elementConverters=[]}}
java.lang.IllegalArgumentException: unable to serialize DoFnWithExecutionInformation{doFn=org.apache.beam.sdk.testing.PAssert$GroupedValuesCheckerDoFn@6367a688, mainOutputTag=Tag<output>, schemaInformation=DoFnSchemaInformation{elementConverters=[]}}
	at org.apache.beam.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:55)
	at org.apache.beam.repackaged.direct_java.runners.core.construction.ParDoTranslation.translateDoFn(ParDoTranslation.java:563)
...
Caused by: java.io.NotSerializableException: io.chrisdavenport.fuuid.FUUID
```

Here is some code that can reproduce the use case:
```scala

import java.util.UUID

import com.spotify.scio.testing._
import com.spotify.scio.values.WindowOptions
import io.chrisdavenport.fuuid.FUUID
import org.apache.beam.sdk.transforms.windowing.{
  AfterProcessingTime,
  AfterWatermark,
  IntervalWindow,
  Repeatedly
}
import org.apache.beam.sdk.values.TimestampedValue
import org.apache.beam.sdk.values.WindowingStrategy.AccumulationMode
import org.joda.time.{Duration, Instant}

// for holding values while ensuring no closures of test-related context
object SerializableSpec {
  // FUUID is non-serializable
  // class: https://github.com/ChristopherDavenport/fuuid/blob/master/modules/core/src/main/scala/io/chrisdavenport/fuuid/FUUID.scala
  case class Message(id: FUUID, body: String)

  val safeMsg = Message(FUUID.fromUUID(UUID.randomUUID), "one")
}

class SerializableSpec extends PipelineSpec {
  "SCollection[T]" should "not require T to be Serializable" in {
    val inTestMsg =
      SerializableSpec.Message(FUUID.fromUUID(UUID.randomUUID), "one")

    val epoch = new Instant(0)
    val windowDuration = Duration.standardSeconds(1)
    val window1 = new IntervalWindow(epoch, epoch.plus(windowDuration))

    runWithContext { sc =>
      // selecting between these two makes no difference
      //val msg = inTestMsg
      val msg = SerializableSpec.safeMsg

      val stream = testStreamOf[SerializableSpec.Message]
      // one element in the first window
        .addElements(TimestampedValue.of(msg, epoch.plus(Duration.millis(250))))
        .advanceWatermarkToInfinity()

      val result = sc
        .testStream(stream)
        .withFixedWindows(
          duration = windowDuration,
          options = WindowOptions(
            trigger = Repeatedly.forever(
              AfterWatermark.pastEndOfWindow.withEarlyFirings(
                AfterProcessingTime.pastFirstElementInPane.alignedTo(
                  windowDuration))),
            accumulationMode = AccumulationMode.DISCARDING_FIRED_PANES,
            allowedLateness = Duration.ZERO
          )
        )
        // fails
        .map(_.id)
       // succeeds
       //.map(_.id.toString)

      result should inWindow(window1) {
        haveSize(1)
        // fails
        containValue(msg.id)
        // succeeds
        //containValue(msg.id.toString)
      }
    }
  }
}
```

Of note:
- FUUID is not serializable
- toggling between the `msg` examples above should demonstrate this isn't a closure-related issue but is actually a type T-related issue
- this issue does *not* reproduce when using `containsInAnyOrder` but reproduces reliably with `containValue`

To reproduce the error in the code above, run with:
- final step of SCollection as `.map(_.id)` (results in `SCollection[FUUID]`)
- assertion as `containValue(msg.id)`

The test works when switching to a serializable type T of String via:
- final step of SCollection as `.map(_.id.toString)`
- assertion as `containValue(msg.id.toString)`

I would expect (or at least hope) that the assertion would utilize the defined `Coder[T]` to rather than falling back to java serialization, as this does not afflict other assertions.

**Comment by nevillelyh** [comment]
Does it work if you remove `val msg = SerializableSpec.safeMsg`, and just use `SerializableSpec.safeMsg` directly everywhere in the test? Alternatively `import SerializableSpec.{safeMsg => msg}`?

**Comment by drobert** [comment]
No, the problem reproduces if I replace all instances of `msg` with `SerializableSpec.safeMsg` directly.

**Comment by drobert** [comment]
I should have left this as an in-line comment in my code snippet above, but this construct also works correctly with all of the same code from the broken scenario:
```scala
      result should inWindow(window1) {
        haveSize(1)
        // works
        containInAnyOrder(List(SerializableSpec.safeMsg.id))
        // fails
        containValue(SerializableSpec.safeMsg.id)
      }
```

**Comment by drobert** [comment]
Updated code snippet to try to remove some ambiguity from the conversation:

```scala

object SerializableSpec {
  case class Message(id: FUUID, body: String)

  val safeMsg = Message(FUUID.fromUUID(UUID.randomUUID), "one")
}

class SerializableSpec extends PipelineSpec {
  "SCollection[T]" should "not require T to be Serializable" in {
    val epoch = new Instant(0)
    val windowDuration = Duration.standardSeconds(1)
    val window1 = new IntervalWindow(epoch, epoch.plus(windowDuration))

    runWithContext { sc =>
      val stream = testStreamOf[SerializableSpec.Message]
      // one element in the first window
        .addElements(TimestampedValue.of(SerializableSpec.safeMsg,
                                         epoch.plus(Duration.millis(250))))
        .advanceWatermarkToInfinity()

      val result = sc
        .testStream(stream)
        .withFixedWindows(
          duration = windowDuration,
          options = WindowOptions(
            trigger = Repeatedly.forever(
              AfterWatermark.pastEndOfWindow.withEarlyFirings(
                AfterProcessingTime.pastFirstElementInPane.alignedTo(
                  windowDuration))),
            accumulationMode = AccumulationMode.DISCARDING_FIRED_PANES,
            allowedLateness = Duration.ZERO
          )
        )
        // fails (SCollection[FUUID])
        .map(_.id)
      // succeeds (SCollection[String])
      //.map(_.id.toString)

      result should inWindow(window1) {
        haveSize(1)
        // succeeds (for any SCollection[T])
        containInAnyOrder(List(SerializableSpec.safeMsg.id))
        // fails (SCollection[FUUID])
        containValue(SerializableSpec.safeMsg.id)
        // succeeds (SCollection[String])
        //containValue(msg.id.toString)
      }
    }
  }
}
```

**Comment by nevillelyh** [comment]
Found the culprit:
https://github.com/spotify/scio/blob/master/scio-test/src/main/scala/com/spotify/scio/testing/SCollectionMatchers.scala#L231

We make 2 lambdas, `should` and `shouldNot` to pass to `satisfies`, which requires them to be Java serializable. The lambdas pull in `v` which is `FUUID` in your case and fails ser/de.

**Comment by nevillelyh** [comment]
This seems to affect `containInAnyOrder` and `containValue` only, due to how assertion lambdas are constructed inside around the test data. They're fixed by wrapping non-serializable `value` in a serializable  `Externalizer` that uses `Coder[T]` and bytes to ensure the value survives Java ser/de.

The other matches that take `predicate` are actually not fixable, since we have no control over user code. So they'll still fail if the predicate lambda pulls in something bad and the user will have to fix them with scoping or externalizer trick.

**Comment by nevillelyh** [comment]
This is a good one. It's buried pretty deep and totally not obvious. Thanks for reporting.
