### ISSUE TITLE
sparseLeftOuterJoin causing coder exception

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2395]
Reported by a user. From `com.twitter.algebird.Hash128$$$Lambda$74/834041222`. The join key was `String`, replacing it with `Array[Byte]` fixes it. Need to triage/repro.

```
com.spotify.scio.coders.CoderException: Exception while trying to `decode` an instance of scala.Tuple2: Can't decode field _1
    at com.spotify.scio.coders.CoderException$.apply(Coder.scala:150)
    at com.spotify.scio.coders.WrappedBCoder.com$spotify$scio$coders$WrappedBCoder$$buildException(Coder.scala:184)
    at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:191)
    at com.spotify.scio.coders.WrappedBCoder.decode(Coder.scala:201)
    at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.decode(WindowedValue.java:543)
    at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.decode(WindowedValue.java:480)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromSafeStream(CoderUtils.java:115)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:98)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:92)
    at org.apache.beam.runners.dataflow.worker.GroupingShuffleReader$GroupingShuffleReaderIterator$ValuesIterator.next(GroupingShuffleReader.java:427)
    at org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowAndCombineFn.processElement(BatchGroupAlsoByWindowAndCombineFn.java:131)
    at org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowAndCombineFn.processElement(BatchGroupAlsoByWindowAndCombineFn.java:57)
    at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:115)
    at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73)
    at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:114)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77)
    at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:411)
    at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:380)
    at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:306)
    at org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:135)
    at org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:115)
    at org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:102)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.spotify.scio.coders.CoderException$$anon$1:  - Coder was materialized at
    at com.spotify.scio.coders.CoderException.getCause(Coder.scala:155)
    at java.lang.Throwable.printStackTrace(Throwable.java:665)
    at java.lang.Throwable.printStackTrace(Throwable.java:721)
    at org.apache.beam.runners.dataflow.worker.logging.DataflowWorkerLoggingHandler.formatException(DataflowWorkerLoggingHandler.java:88)
    at org.apache.beam.runners.dataflow.worker.WorkItemStatusClient.reportError(WorkItemStatusClient.java:137)
    at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:385)
    ... 8 more
Caused by: com.spotify.scio.coders.CoderException: Unable to find class: com.twitter.algebird.Hash128$$$Lambda$74/834041222
Serialization trace:
fn$1 (com.twitter.algebird.Hash128$$anon$1)
hash (com.twitter.algebird.BFHash)
hashes (com.twitter.algebird.BFSparse)
    at com.spotify.scio.coders.CoderException$.apply(Coder.scala:150)
    at com.spotify.scio.coders.WrappedBCoder.com$spotify$scio$coders$WrappedBCoder$$buildException(Coder.scala:184)
    at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:191)
    at com.spotify.scio.coders.WrappedBCoder.decode(Coder.scala:198)
    at com.spotify.scio.coders.RecordCoder$$anonfun$decode$4.apply$mcV$sp(Coder.scala:265)
    at com.spotify.scio.coders.RecordCoder$$anonfun$decode$4.apply(Coder.scala:265)
    at com.spotify.scio.coders.RecordCoder$$anonfun$decode$4.apply(Coder.scala:265)
    at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:237)
    at com.spotify.scio.coders.RecordCoder.decode(Coder.scala:265)
    at org.apache.beam.sdk.coders.Coder.decode(Coder.java:159)
    at com.spotify.scio.coders.WrappedBCoder$$anonfun$decode$2.apply(Coder.scala:201)
    at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:189)
    at com.spotify.scio.coders.WrappedBCoder.decode(Coder.scala:201)
    at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.decode(WindowedValue.java:543)
    at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.decode(WindowedValue.java:480)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromSafeStream(CoderUtils.java:115)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:98)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:92)
    at org.apache.beam.runners.dataflow.worker.GroupingShuffleReader$GroupingShuffleReaderIterator$ValuesIterator.next(GroupingShuffleReader.java:427)
    at org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowAndCombineFn.processElement(BatchGroupAlsoByWindowAndCombineFn.java:131)
    at org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowAndCombineFn.processElement(BatchGroupAlsoByWindowAndCombineFn.java:57)
    at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:115)
    at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73)
    at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:114)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77)
    at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:411)
    at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:380)
    ... 8 more
Caused by: com.spotify.scio.coders.CoderException$$anon$1:  - Coder was materialized at
    at com.spotify.scio.coders.CoderException.getCause(Coder.scala:155)
    at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:707)
    at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
    at java.lang.Throwable.printStackTrace(Throwable.java:667)
    at java.lang.Throwable.printStackTrace(Throwable.java:721)
    at org.apache.beam.runners.dataflow.worker.logging.DataflowWorkerLoggingHandler.formatException(DataflowWorkerLoggingHandler.java:88)
    at org.apache.beam.runners.dataflow.worker.WorkItemStatusClient.reportError(WorkItemStatusClient.java:137)
    at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:385)
    ... 8 more
Caused by: java.lang.ClassNotFoundException: com.twitter.algebird.Hash128$$$Lambda$74/834041222
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:136)
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:115)
    at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:610)
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:599)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:648)
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:605)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:648)
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:605)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729)
    at com.spotify.scio.coders.KryoAtomicCoder$$anonfun$decode$1.apply(KryoAtomicCoder.scala:156)
    at com.spotify.scio.coders.KryoAtomicCoder$$anonfun$decode$1.apply(KryoAtomicCoder.scala:151)
    at com.spotify.scio.coders.KryoAtomicCoder$.withKryoState(KryoAtomicCoder.scala:264)
    at com.spotify.scio.coders.KryoAtomicCoder.decode(KryoAtomicCoder.scala:151)
    at com.spotify.scio.coders.WrappedBCoder$$anonfun$decode$1.apply(Coder.scala:198)
    at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:189)
    at com.spotify.scio.coders.WrappedBCoder.decode(Coder.scala:198)
    at com.spotify.scio.coders.RecordCoder$$anonfun$decode$4.apply$mcV$sp(Coder.scala:265)
    at com.spotify.scio.coders.RecordCoder$$anonfun$decode$4.apply(Coder.scala:265)
    at com.spotify.scio.coders.RecordCoder$$anonfun$decode$4.apply(Coder.scala:265)
    at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:237)
    at com.spotify.scio.coders.RecordCoder.decode(Coder.scala:265)
    at org.apache.beam.sdk.coders.Coder.decode(Coder.java:159)
    at com.spotify.scio.coders.WrappedBCoder$$anonfun$decode$2.apply(Coder.scala:201)
    at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:189)
    at com.spotify.scio.coders.WrappedBCoder.decode(Coder.scala:201)
    at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.decode(WindowedValue.java:543)
    at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.decode(WindowedValue.java:480)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromSafeStream(CoderUtils.java:115)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:98)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:92)
    at org.apache.beam.runners.dataflow.worker.GroupingShuffleReader$GroupingShuffleReaderIterator$ValuesIterator.next(GroupingShuffleReader.java:427)
    at org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowAndCombineFn.processElement(BatchGroupAlsoByWindowAndCombineFn.java:131)
    at org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowAndCombineFn.processElement(BatchGroupAlsoByWindowAndCombineFn.java:57)
    at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:115)
    at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73)
    at org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:114)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
    at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77)
    at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:411)
    at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:380)
    ... 8 more
```

**Comment by nevillelyh** [comment]
No activity for > 1 year, closing.
