### ISSUE TITLE
`tsql` error message is a stacktrace in some cases

### ISSUE THREAD

**Issue by jto** [spotify/scio#2397]
For some errors (type mismatch between espected type and query output type), the compiler will issue the following compilation error instead of a proper schema error:

```
exception during macro expansion: 
scala.tools.reflect.ToolBoxError: reflective compilation has failed:

type mismatch;
 found   : String
 required: Long
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.throwIfErrors(ToolBoxFactory.scala:331)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.wrapInPackageAndCompile(ToolBoxFactory.scala:213)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compile(ToolBoxFactory.scala:267)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.$anonfun$compile$13(ToolBoxFactory.scala:444)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:370)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.compile(ToolBoxFactory.scala:437)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.eval(ToolBoxFactory.scala:459)
	at com.spotify.scio.schemas.FastEval.eval(To.scala:187)
	at com.spotify.scio.schemas.FastEval$.apply(To.scala:206)
	at com.spotify.scio.sql.Query2$.typed2Impl(Query2.scala:91)
```

**Comment by jto** [comment]
Hum I can't reproduce it in a test case :/

**Comment by jto** [comment]
Did not happen to me in a while, can't repro, closing.
