### ISSUE TITLE
Unexpected 'ConcurrentModificationException' while deriving Java beans Schema

### ISSUE THREAD

**Issue by regadas** [spotify/scio#2495]
```
[info] - should Serialize Java beans using a Schema Coder *** FAILED *** (452 milliseconds)
[info]   java.util.ConcurrentModificationException:
[info]   at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
[info]   at org.apache.beam.sdk.schemas.utils.ReflectUtils.getMethods(ReflectUtils.java:77)
[info]   at org.apache.beam.sdk.schemas.JavaBeanSchema$GetterTypeSupplier.get(JavaBeanSchema.java:56)
[info]   at org.apache.beam.sdk.schemas.utils.StaticSchemaInference.schemaFromClass(StaticSchemaInference.java:83)
[info]   at org.apache.beam.sdk.schemas.utils.JavaBeanUtils.schemaFromJavaBeanClass(JavaBeanUtils.java:64)
[info]   at org.apache.beam.sdk.schemas.JavaBeanSchema.schemaFor(JavaBeanSchema.java:87)
[info]   at com.spotify.scio.schemas.RawRecord$.apply(Schema.scala:154)
[info]   at com.spotify.scio.schemas.instances.JavaInstances.javaBeanSchema(JavaInstances.scala:70)
[info]   at com.spotify.scio.schemas.instances.JavaInstances.javaBeanSchema$(JavaInstances.scala:69)
[info]   at com.spotify.scio.schemas.instances.JavaInstances$.javaBeanSchema(JavaInstances.scala:86)
```

**Comment by jto** [comment]
@regadas do you know how to reproduce it ?

**Comment by regadas** [comment]
@jto unfortunately no 😞 I've been seeing this popping up in CI but I haven't really dug into how I can get this consistently.

**Comment by jto** [comment]
Is this still hapening ? I don't think I've seen it in a while.

**Comment by regadas** [comment]
I haven't seen this in awhile as well let's close this.
