### ISSUE TITLE
Erorr with external Flink when reaading files "No filesystem found for scheme file"

### ISSUE THREAD

**Issue by lordlinus** [spotify/scio#2528]
I am able to run the scio using --flinkRunner, but unable to submit the job to an external flink cluster. ( error below )

Can someone please advise the correct way to submit scio assembly jar to external Flink clusters with correct Filesystem reader

Error
>org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:546)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:427)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:813)
	at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:287)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:213)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1050)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$11(CliFrontend.java:1126)
	at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1126)
Caused by: java.lang.IllegalArgumentException: No filesystem found for scheme file
	at org.apache.beam.sdk.io.FileSystems.getFileSystemInternal(FileSystems.java:463)
	at org.apache.beam.sdk.io.FileSystems.match(FileSystems.java:120)
	at org.apache.beam.sdk.io.FileSystems.match(FileSystems.java:141)
	at datarepublic.GetMatches$.main(GetMatches.scala:31)
	at datarepublic.GetMatches.main(GetMatches.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	... 9 more
`

version in sbt 

> val scioVersion = "0.8.0-beta2"
val beamVersion = "2.16.0"
val scalaMacrosVersion = "2.1.1"
val flinkVersion = "1.7.2"

Jobs submitted using command below
>./bin/flink run -m localhost:6123 -c example.MyExample example-scio-fat.jar

i am using the sbt-assembly yo build the fat jar ( it is roughly 191 MB) witht the below settings
>    assemblyJarName in assembly := "example-scio-fat.jar",
    assemblyShadeRules in assembly := Seq(
      ShadeRule.rename("org.objenesis.**" -> s"org.objenesis_shaded.@1").inAll,
      ShadeRule.rename("com.esotericsoftware.kryo.**" -> s"com.esotericsoftware.kryo_shaded.@1").inAll,
      ShadeRule.rename("com.twitter.chill.**" -> s"com.twitter.chill_shaded.@1").inAll
    ),
    test in assembly := {},
      mainClass in assembly := Some("example.MyExample"),
      assemblyMergeStrategy in assembly := {
      case PathList("META-INF", xs @ _*) => MergeStrategy.discard
      case x                             => MergeStrategy.first
    }

i am reading files from the local filesystem like below
> val input = "/some/local/path/**.csv" # get all csv files  
 FileSystems.setDefaultPipelineOptions(sc.options)
    val uris = FileSystems.`match`(input).metadata().asScala.map(_.resourceId().toString)
    SCollection
      .unionAll(uris.map(uri => sc.textFile(uri)))

**Comment by nevillelyh** [comment]
The file systems API uses service provider, so you probably need to make sure `META-INF/services/org.apache.beam.sdk.io.FileSystemRegistrar` is merged with `concat` instead of `first`/`discard` strategy. Same goes for `PipelineOptionsRegistrar` and possible some other services.

**Comment by lordlinus** [comment]
Awesome. Thanks
using the merge strategy from the scio built.sbt script and all works well.
