### ISSUE TITLE
Either coders throw ClassCastException in Scio 0.8.0

### ISSUE THREAD

**Issue by anne-decusatis** [spotify/scio#2595]
On Scio 0.8.0:

Open SBT test console:

```
sbt
> project scio-core
> test:console
```

Paste the following into the console:

```
import com.spotify.scio.coders._
import com.spotify.scio._
case class Example(stringT: Either[Array[Byte], String], longT: Either[Array[Byte], Long])
val sc = ScioContext.forTest()
val c = CoderMaterializer.beam(sc, implicitly[Coder[Example]])
c.encode(Example(Right("str"), Right(0L)), System.out)
```

Expected:
Coder should throw no exceptions and successfully encode an Example case class containing two Eithers of different types

Actual: 
The following exception is thrown: 

```
java.lang.RuntimeException: Exception while trying to `encode` an instance of Example:  Can't encode field longT value Right(0)
  at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:272)
  at com.spotify.scio.coders.RecordCoder.encode(Coder.scala:284)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:216)
  at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:226)
  ... 47 elided
Caused by: java.lang.RuntimeException: Exception while trying to `encode` an instance of scala.util.Right:  Can't encode field value value 0
  at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:272)
  at com.spotify.scio.coders.RecordCoder.encode(Coder.scala:284)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:216)
  at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:226)
  at com.spotify.scio.coders.DisjunctionCoder.encode(Coder.scala:126)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:216)
  at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:226)
  at com.spotify.scio.coders.RefCoder$$anonfun$encode$1.apply$mcV$sp(Coder.scala:184)
  at com.spotify.scio.coders.RefCoder$$anonfun$encode$1.apply(Coder.scala:184)
  at com.spotify.scio.coders.RefCoder$$anonfun$encode$1.apply(Coder.scala:184)
  at com.spotify.scio.coders.RefCoder.check(Coder.scala:180)
  at com.spotify.scio.coders.RefCoder.encode(Coder.scala:184)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$4.apply$mcV$sp(Coder.scala:284)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$4.apply(Coder.scala:284)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$4.apply(Coder.scala:284)
  at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:269)
  at com.spotify.scio.coders.RecordCoder.encode(Coder.scala:284)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:216)
  at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:226)
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
  at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:37)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$4.apply$mcV$sp(Coder.scala:284)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$4.apply(Coder.scala:284)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$4.apply(Coder.scala:284)
  at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:269)
  at com.spotify.scio.coders.RecordCoder.encode(Coder.scala:284)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:216)
  at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:226)
  at com.spotify.scio.coders.DisjunctionCoder.encode(Coder.scala:126)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:216)
  at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:226)
  at com.spotify.scio.coders.RefCoder$$anonfun$encode$1.apply$mcV$sp(Coder.scala:184)
  at com.spotify.scio.coders.RefCoder$$anonfun$encode$1.apply(Coder.scala:184)
  at com.spotify.scio.coders.RefCoder$$anonfun$encode$1.apply(Coder.scala:184)
  at com.spotify.scio.coders.RefCoder.check(Coder.scala:180)
  at com.spotify.scio.coders.RefCoder.encode(Coder.scala:184)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$4.apply$mcV$sp(Coder.scala:284)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$4.apply(Coder.scala:284)
  at com.spotify.scio.coders.RecordCoder$$anonfun$encode$4.apply(Coder.scala:284)
  at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:269)
  at com.spotify.scio.coders.RecordCoder.encode(Coder.scala:284)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply$mcV$sp(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$2.apply(Coder.scala:226)
  at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:216)
  at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:226)
```

**Comment by jto** [comment]
uh oh. 
I know why it's doing that and it's pretty bad (also, totally my fault...). 
I'll implement a fix quickly.

![hidding](https://media.giphy.com/media/jUwpNzg9IcyrK/giphy.gif)
