### ISSUE TITLE
Codec error - GenericRecordCoder NoClassDefFoundError

### ISSUE THREAD

**Issue by sivakon** [spotify/scio#2612]
Steps to reproduce - 

- Run `repl/run` and paste the following

```scala
import org.apache.avro.Schema
import org.apache.avro.generic.{GenericData, GenericRecord}

import scala.collection.JavaConverters._


def f(name: String, tpe: Schema.Type) =
    new Schema.Field(
      name,
      Schema.createUnion(List(Schema.create(Schema.Type.NULL), Schema.create(tpe)).asJava),
      null: String,
      null: AnyRef
    )

val schema = Schema.createRecord("GenericTestRecord", null, null, false)
  schema.setFields(
    List(
      f("int_field", Schema.Type.INT)
    ).asJava
  )


def newGenericRecord(i: Int): GenericRecord = {
    val r = new GenericData.Record(schema)
    r.put("int_field", 1 * i)
    r
  }


implicit val coder = Coder.avroGenericRecordCoder(schema)
```

Error 
```
scio> implicit val coder = Coder.avroGenericRecordCoder(schema)
java.lang.NoClassDefFoundError: org/apache/avro/data/TimeConversions$TimestampConversion
  at org.apache.beam.sdk.coders.AvroCoder.<init>(AvroCoder.java:269)
  at org.apache.beam.sdk.coders.AvroGenericCoder.<init>(AvroGenericCoder.java:26)
  at org.apache.beam.sdk.coders.AvroGenericCoder.of(AvroGenericCoder.java:30)
  at org.apache.beam.sdk.coders.AvroCoder.of(AvroCoder.java:129)
  at com.spotify.scio.coders.instances.AvroCoders.avroGenericRecordCoder(AvroCoders.scala:115)
  at com.spotify.scio.coders.instances.AvroCoders.avroGenericRecordCoder$(AvroCoders.scala:114)
  at com.spotify.scio.coders.Coder$.avroGenericRecordCoder(Coder.scala:474)
  ... 60 elided
Caused by: java.lang.ClassNotFoundException: org.apache.avro.data.TimeConversions$TimestampConversion
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  at com.spotify.scio.repl.ScioReplClassLoader.loadClass(ScioReplClassLoader.scala:72)
```

**Comment by jto** [comment]
Hi @sivakon,

Thanks for your repport :)
It looks like the issue is specific to your project and you are simply missing a dependency on avro. I tested on a couple of project and `scio-core/console` and everything looks fine.

**Comment by sivakon** [comment]
I put the dependencies, in `build.sbt`. Still I get the same error. Reproducible error. 

SBT version - 1.3.7

https://github.com/sivakon/scio-demo/blob/master/build.sbt#L40-L41

**Comment by jto** [comment]
Your projects pulls the wrong version of avro (`1.9`) because its using the plugin `sbt-avro-1-9`.
Scio and beam only support avro `1.8`

**Comment by sivakon** [comment]
@jto  Got it. Thanks.
