### ISSUE TITLE
SMB save fails on Avro map field

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2649]
I can repro with the following code:

```scala
import com.spotify.scio._
import com.spotify.scio.avro._
import com.spotify.scio.smb._
import com.spotify.scio.coders.Coder
import org.apache.avro.Schema
import org.apache.avro.generic.{GenericRecord, GenericRecordBuilder}
import org.apache.beam.sdk.extensions.smb.AvroSortedBucketIO

import scala.collection.JavaConverters._
import scala.util.Random

object Debug {
  val schemaString =
    """
      |{
      |  "type": "record",
      |  "name": "Record",
      |  "namespace": "com.spotify.data",
      |  "fields": [
      |    {
      |      "name": "id",
      |      "type": "int"
      |    },
      |    {
      |      "name": "map",
      |      "type": [
      |        "null",
      |        {
      |          "type": "map",
      |          "values": "string"
      |        }
      |      ],
      |      "default": null
      |    }
      |  ]
      |}
      |""".stripMargin

  val schema = new Schema.Parser().parse(schemaString)

  def makeRecord: GenericRecord = {
    val builder = new GenericRecordBuilder(schema)
      .set("id", Random.nextInt(100))
    if (Random.nextBoolean()) {
      val m = (1 to Random.nextInt(10) + 1)
        .map(i => s"key$i" -> Random.nextInt(100).toString)
        .toMap
      builder.set("map", m.asJava)
    }
    Random.nextInt(10)
    builder.build()
  }

  def main(args: Array[String]): Unit = {
    val sc = ScioContext()
    implicit val coder = Coder.avroGenericRecordCoder(schema)
    sc.parallelize(Seq.fill(100)(makeRecord))
        .saveAsSortedBucket(AvroSortedBucketIO
          .write(classOf[Integer], "id", schema)
          .to("out")
          .withNumBuckets(2),
        )
//      .saveAsAvroFile("out", schema = schema) // this works fine
    sc.run()
  }
}
```

Stacktrace:
```
[error] Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: org.apache.avro.file.DataFileWriter$AppendWriteException: org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"map","values":"string"}]: {key1=17, key2=46, key5=68, key6=16, key3=27, key4=55}
[error]         at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:348)
[error]         at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:318)
[error]         at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:213)
[error]         at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
[error]         at org.apache.beam.sdk.Pipeline.run(Pipeline.java:315)
[error]         at org.apache.beam.sdk.Pipeline.run(Pipeline.java:301)
[error]         at com.spotify.scio.ScioContext.execute(ScioContext.scala:598)
[error]         at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:586)
[error]         at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:574)
[error]         at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:694)
[error]         at com.spotify.scio.ScioContext.run(ScioContext.scala:574)
[error]         at Debug$.main(Debug.scala:64)
[error]         at Debug.main(Debug.scala)
[error] Caused by: org.apache.avro.file.DataFileWriter$AppendWriteException: org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"map","values":"string"}]: {key1=17, key2=46, key5=68, key6=16, key3=27, key4=55}
[error]         at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:308)
[error]         at org.apache.beam.sdk.io.AvroIO$Sink.write(AvroIO.java:1886)
[error]         at org.apache.beam.sdk.extensions.smb.FileOperations$Writer.write(FileOperations.java:143)
[error]         at org.apache.beam.sdk.extensions.smb.SortedBucketSink$WriteTempFiles$1.lambda$processElement$0(SortedBucketSink.java:322)
[error]         at java.util.ArrayList.forEach(ArrayList.java:1257)
[error]         at org.apache.beam.sdk.extensions.smb.SortedBucketSink$WriteTempFiles$1.processElement(SortedBucketSink.java:319)
[error] Caused by: org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"map","values":"string"}]: {key1=17, key2=46, key5=68, key6=16, key3=27, key4=55}

```

**Comment by ClaireMcGinty** [comment]
fixed in #2664, we can close?
