### ISSUE TITLE
FileStorage.avro should support GCS files

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#266]
If files are materialized to GCS, `FileStorage.avroFile` should not assume `toFile` exists.

```
scio> :scioOpts --runner=DataflowPipelineRunner --stagingLocation=gs://scio-example/user/rav/df-staging --zone=europe-west1-d --project=gabocontinuousintegration
Scio options updated. Use :newScio to get a new Scio context.

scio> :newScio
Scio context available as 'sc'

scio> sc.textFile("gs://scio-example/test-data/README.md").flatMap(_.split("[^a-zA-Z0-9]+")).filter(_.nonEmpty).count
count   countApproxDistinct   countByValue

scio> sc.textFile("gs://scio-example/test-data/README.md").flatMap(_.split("[^a-zA-Z0-9]+")).filter(_.nonEmpty).countByValue.materialize
res4: scala.concurrent.Future[com.spotify.scio.io.Tap[(String, Long)]] = List()

scio> sc.close()
[main] INFO com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner - Executing pipeline on the Dataflow Service, which will have billing implications related to Google Compute Engine usage and other Google Cloud Services.
[main] INFO com.google.cloud.dataflow.sdk.util.PackageUtil - Uploading 5 files from PipelineOptions.filesToStage to staging location to prepare for execution.
[main] INFO com.google.cloud.dataflow.sdk.util.PackageUtil - Uploading PipelineOptions.filesToStage complete: 2 files newly uploaded, 3 files cached
Dataflow SDK version: 1.7.0
[main] INFO com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner - To access the Dataflow monitoring console, please navigate to https://console.developers.google.com/project/gabocontinuousintegration/dataflow/job/2016-09-19_14_43_58-14979696488092329768
Submitted job: 2016-09-19_14_43_58-14979696488092329768
[main] INFO com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner - To cancel the job using the 'gcloud' tool, run:
> gcloud alpha dataflow jobs --project=gabocontinuousintegration cancel 2016-09-19_14_43_58-14979696488092329768
res5: com.spotify.scio.ScioResult = com.spotify.scio.ScioResult@4049837d

scio> res4.waitForResult().value
java.lang.UnsupportedOperationException
  at com.google.cloud.dataflow.sdk.util.gcsfs.GcsPath.toFile(GcsPath.java:461)
  at com.spotify.scio.io.FileStorage$$anonfun$avroFile$1.apply(FileStorage.scala:65)
  at com.spotify.scio.io.FileStorage$$anonfun$avroFile$1.apply(FileStorage.scala:65)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at com.spotify.scio.io.FileStorage$class.avroFile(FileStorage.scala:65)
  at com.spotify.scio.io.GcsStorage.avroFile(FileStorage.scala:111)
  at com.spotify.scio.io.ObjectFileTap.value(Tap.scala:85)
  ... 32 elided
```

**Comment by ravwojdyla** [comment]
Introduced with #258 and released in scio `0.2.3`
