### ISSUE TITLE
scio not handling transient for non-serializable objects

### ISSUE THREAD

**Issue by sgireddy** [spotify/scio#2663]
I am using javax.crypto.Mac for hashing which has been returning ArrayIndexOutOfBoundsException. I was able to repro the same issue using MinimalWordCount example for both beam (java) and scio. In beam I got Mac not serializable exception which went away after marking it as transient and re-initializing when it is null, but the same class is not working in Scio. Here is a gist with both bream and scio versions: 

     https://gist.github.com/sgireddy/06780918382c535b8c60c333db174f5c

Stack Trace:

        Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.ArrayIndexOutOfBoundsException
            at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:348)
            at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:318)
            at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:213)
            at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
            at org.apache.beam.sdk.Pipeline.run(Pipeline.java:315)
            at org.apache.beam.sdk.Pipeline.run(Pipeline.java:301)
            at com.spotify.scio.ScioContext.execute(ScioContext.scala:598)
            at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:586)
            at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:574)
            at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:694)
            at com.spotify.scio.ScioContext.run(ScioContext.scala:574)
            at org.example.dataflow.ScioMinimalWordCount$.main(ScioMinimalWordCount.scala:28)
            at org.example.dataflow.ScioMinimalWordCount.main(ScioMinimalWordCount.scala)
        Caused by: java.lang.ArrayIndexOutOfBoundsException
            at java.lang.System.arraycopy(Native Method)
            at sun.security.provider.DigestBase.engineUpdate(DigestBase.java:114)
            at java.security.MessageDigest$Delegate.engineUpdate(MessageDigest.java:584)
            at java.security.MessageDigest.update(MessageDigest.java:335)
            at com.sun.crypto.provider.HmacCore.engineDoFinal(HmacCore.java:194)
            at javax.crypto.Mac.doFinal(Mac.java:561)
            at javax.crypto.Mac.doFinal(Mac.java:636)
            at org.example.dataflow.Crypto.calculateHmacSHA256(Crypto.java:36)
            at org.example.dataflow.ScioMinimalWordCount$$anonfun$2$$anonfun$apply$3.apply(ScioMinimalWordCount.scala:21)
            at org.example.dataflow.ScioMinimalWordCount$$anonfun$2$$anonfun$apply$3.apply(ScioMinimalWordCount.scala:20)
            at com.spotify.scio.util.Functions$$anon$9.processElement(Functions.scala:263)

**Comment by syodage** [comment]
@sgireddy try moving the 
` @transient lazy val crypto = new Crypto()` inside the main method that solve the issue for me. 

Also your code work as it with dataflow runner.

**Comment by sgireddy** [comment]
wow... thank you so much for quick response @syodage
