### ISSUE TITLE
`scio-extra` NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by regadas** [spotify/scio#3001]
Exception is thrown when using Java 8. Works as expected in Java 11.

```
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at com.spotify.scio.extra.bigquery.ToTableRow.toByteArray(ToTableRow.scala:115)
	at com.spotify.scio.extra.bigquery.ToTableRow.toTableRowField(ToTableRow.scala:64)
	at com.spotify.scio.extra.bigquery.ToTableRow.toTableRowField$(ToTableRow.scala:56)
	at com.spotify.scio.extra.bigquery.AvroConverters$.toTableRowField(AvroConverters.scala:28)
	at com.spotify.scio.extra.bigquery.AvroConverters$$anonfun$toTableRow$1$$anonfun$apply$1.apply(AvroConverters.scala:36)
```

**Comment by regadas** [comment]
Closed via #3006
