### ISSUE TITLE
Custom ScioIO subclass Serde Error

### ISSUE THREAD

**Issue by xiaoyao1991** [spotify/scio#3065]
## Problem
I created a subclass of `ScioIO`, and in its `read` and `write` I delegate the call to, say, scio's `PubsubIO`, to get me the `SCollection[PubsubMessage]`, and then I did some thrift serder transform after that, but somehow when I try to submit the job (as a **streaming** job) to dataflow, it fails with 

```INFO: Adding pubsubSubscription@{MyIO.scala:21}:1/PubsubUnboundedSource as step s1
Jun 17, 2020 3:04:40 PM org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator addStep
INFO: Adding pubsubSubscription@{MyIO.scala:21}:1/MapElements/Map as step s2
Exception in thread "main" java.lang.IllegalArgumentException: unable to deserialize Custom DoFn With Execution Info
	at org.apache.beam.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:74)
	at org.apache.beam.runners.core.construction.ParDoTranslation.doFnWithExecutionInformationFromProto(ParDoTranslation.java:697)
	at org.apache.beam.runners.core.construction.ParDoTranslation.getSchemaInformation(ParDoTranslation.java:389)
	at org.apache.beam.runners.core.construction.ParDoTranslation.getSchemaInformation(ParDoTranslation.java:374)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$8.translateSingleHelper(DataflowPipelineTranslator.java:997)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$8.translate(DataflowPipelineTranslator.java:989)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$8.translate(DataflowPipelineTranslator.java:986)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.visitPrimitiveTransform(DataflowPipelineTranslator.java:484)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:665)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:657)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.access$600(TransformHierarchy.java:317)
	at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:251)
	at org.apache.beam.sdk.Pipeline.traverseTopologically(Pipeline.java:463)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.translate(DataflowPipelineTranslator.java:423)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator.translate(DataflowPipelineTranslator.java:182)
	at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:886)
	at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:192)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:317)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:303)
	at com.spotify.scio.ScioContext.execute(ScioContext.scala:607)
	at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:595)
	at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:583)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:703)
	at com.spotify.scio.ScioContext.run(ScioContext.scala:583)
	at com.twitter.finatra.beam.scio.ScioBeamJob.main(ScioBeamJob.scala:76)
	at com.twitter.tyrion.ManagedSourceSinkExample.main(ManagedSourceSinkExample.scala)
Caused by: java.io.InvalidClassException: com.twitter.io.MyIO; no valid constructor
	at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:169)
	at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:874)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2043)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.apache.beam.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:71)
	... 25 more
```  
  
It looks like somehow under the hood of Scio's pubsubSubscription it is calling some map transform, and my MyIO is declared as an instance val in the DoFn that comes with the map. 

## To Reproduce
`MyIO` subclass is a case class that extends from a `BaseIO` class which extends the `ScioIO`

  
```scala
package example

import com.spotify.scio.coders.Coder
import com.spotify.scio.io.{EmptyTap, EmptyTapOf, ScioIO, Tap}
import com.spotify.scio.values.SCollection
import com.spotify.scio.{Args, ScioContext}
import org.apache.beam.sdk.io.gcp.pubsub.PubsubMessage

abstract class BaseIO[T <: ThriftStruct: Coder: Manifest] extends ScioIO[T] {
  override type ReadP = String
  override type WriteP = String
  final override val tapT = EmptyTapOf[T]

  override def tap(params: ReadP): Tap[Nothing] = EmptyTap
}

object MyIO {
  val pubsubEmptyAttributes = new java.util.HashMap[String, String]()
}

case class MyIO[T <: ThriftStruct: Coder: Manifest]() extends BaseIO[T] {
  override protected def read(sc: ScioContext, params: String): SCollection[T] = {
    sc.pubsubSubscription[PubsubMessage](params).map { message =>
      val thriftCoder = ThriftCoderFactory.thriftCoder[T]
      thriftCoder.fromBytes(message.getPayload)
    }
  }

  override protected def write(data: SCollection[T], params: String): Tap[Nothing] = {
    data.map { record =>
      val thriftParser = ThriftCoderFactory.thriftParser[T]
      val thriftBytes = thriftParser.toBytes(record)
      new PubsubMessage(thriftBytes, MyIO.pubsubEmptyAttributes)
    }.saveAsPubsub(params)

    EmptyTap
  }
}

object CustomScioIOExample  {
   def main(args: Array[String]): Unit = {
    ....
    sc.read(MyIO[LogEvent]())(args("input"))
      .map(s => s)
      .write(MyIO[LogEvent]())(args("output"))
  }
}
```

When I explicitly make `BaseIO` extends `Serializable`, this issue goes away and the job can submit successfully.

**Comment by regadas** [comment]
Hi @xiaoyao1991 your example at first sight seems ok, however you say:

> MyIO is declared as an instance val in the DoFn that comes with the map.

This is not in your example and i think it's what makes it require `Serializable` because `DoFn` need to be serializable. Everything referenced inside it needs to be `Serializable` and the closure needs to be defeated in some cases.

**Comment by nevillelyh** [comment]
Can't see the signature of `ThriftCoderFactory.thriftCoder[T]` or `ThriftCoderFactory.thriftParser[T]` but I'm suspecting it has implicit args, probably `Manifest`? That'll most likely be treated as a member of `MyIO` and pull `MyIO` into the lambda.

Also these 2 coder/parser are constructed per message which can add non-trivial overhead. So yeah `DoFnWithResource` can be an option. You just need to pass `Manifest` or whatever needed to construct coder/paser into the DoFn (in a serializable way).

**Comment by xiaoyao1991** [comment]
@regadas sorry, I meant `it looks like my MyIO is mistakenly declared as an instance val in a DoFn underlying ScioIO's readPubsub`

I did try to wrap my thrift decoding logic in a Beam `PTransform`, and declare the `thriftCoder` as a `lazy val` (I've seen similar class deserialization error in a DoFn before when I use vanilla Beam, and making it `lazy val` made it work), removed the `.map` and just apply the `PTransform` but still doesn't work. 

I may be wrong, but when I saw the exception message comes after `INFO: Adding pubsubSubscription@{MyIO.scala:21}:1/MapElements/Map as step s2`, I thought the error is somewhere in/underlying `pubsubSubscription`.

**Comment by xiaoyao1991** [comment]
@regadas @nevillelyh thanks for pointing out `DoFnWithResource`, I'll try it. 

I checked ThriftCoderFactory but didn't see implicit args.

**Comment by xiaoyao1991** [comment]
@nevillelyh  I find that the ThriftCoder generated by the ThriftCoderFactory does have a thrift binary protocol and codec as member val. 

But like I mentioned in my above comment, I tried wrapping the logic
```.map { message =>
      val thriftCoder = ThriftCoderFactory.thriftCoder[T]
      thriftCoder.fromBytes(message.getPayload)
    }```

in a `PTransform` and declared the thriftCoder a lazy val. That should do the trick right?

**Comment by jto** [comment]
Hi @xiaoyao1991,
did you eventually figure this out ? Do you still need help with the issue ?

**Comment by xiaoyao1991** [comment]
@jto I made BaseIO explicitly extends Serializable and this error just goes away. I can't confidently say it's solved, but I'm not seeing further issues atm.
