### ISSUE TITLE
Scio Repl Typed BigQuery Reflections error

### ISSUE THREAD

**Issue by arturroo** [spotify/scio#3082]
Hello,

When I try to get Typed BigQuery result in Scio Repl I get error with Reflections:
PowerShell 5.1
Scio 0.9.1
Runner: DirectRunner
```
scio> [0m    @BigQueryType.fromQuery(
        """
          |SELECT * FROM `myproject.mydataset.mytable`""".stripMargin)
    class MYTABLE
     |      |      | [main] INFO com.spotify.scio.bigquery.client.QueryOps$ - Executing standard SQL query (INTERACTIVE): `
SELECT * FROM `myproject.mydataset.mytable``
[main] INFO com.spotify.scio.bigquery.client.QueryOps$ - Getting SQL query schema with dry-run
[main] INFO com.spotify.scio.bigquery.client.QueryOps$ - Executing standard SQL query (INTERACTIVE): `
SELECT * FROM `myproject.mydataset.mytable``
defined class MYTABLE
defined object MYTABLE
[32m
scio> [0m
[32m
scio> [0mdef gcpRaw = sc.typedBigQuery[MYTABLE]()
gcpRaw: com.spotify.scio.values.SCollection[MYTABLE]
[32m
scio> [0mgcpRaw.count
scala.ScalaReflectionException: object MYTABLE is an inner module, use reflectModule on an InstanceMirror to obtain its ModuleMirror
  at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$abort(JavaMirrors.scala:155)
  at scala.reflect.runtime.JavaMirrors$JavaMirror.ErrorInnerModule(JavaMirrors.scala:158)
  at scala.reflect.runtime.JavaMirrors$JavaMirror.reflectModule(JavaMirrors.scala:230)
  at scala.reflect.runtime.JavaMirrors$JavaMirror.reflectModule(JavaMirrors.scala:69)
  at com.spotify.scio.bigquery.types.BigQueryType.<init>(BigQueryType.scala:383)
  at com.spotify.scio.bigquery.types.BigQueryType$.apply(BigQueryType.scala:371)
  at com.spotify.scio.bigquery.syntax.ScioContextOps$.typedBigQuery$extension2(ScioContextSyntax.scala:119)
  at com.spotify.scio.bigquery.syntax.ScioContextOps$.typedBigQuery$extension0(ScioContextSyntax.scala:110)
  at gcpRaw(<console>:37)
  ... 46 elided
[32m
scio> [0m
```
The clean source code, that I paste into Scio Repl:
```
@BigQueryType.fromQuery(
  """
    |SELECT * FROM `myproject.mydataset.mytable`""".stripMargin)
class MYTABLE
def gcpRaw = sc.typedBigQuery[MYTABLE]()
gcpRaw.count
```

**Comment by RustedBones** [comment]
tried with scio 0.13, this worked. Closing the issue
