### ISSUE TITLE
`BaseAsyncLookupDoFn` might fail randomly with `java.lang.IllegalStateException`

### ISSUE THREAD

**Issue by regadas** [spotify/scio#3175]
```
 org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.IllegalStateException
 at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:348)
 at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:318)
 at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:213)
 at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
 at org.apache.beam.sdk.Pipeline.run(Pipeline.java:317)
 at org.apache.beam.sdk.Pipeline.run(Pipeline.java:303)
 at com.spotify.scio.ScioContext.execute(ScioContext.scala:625)
 at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:613)
 at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:601)
 at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:690)
 ...
 Cause: java.lang.IllegalStateException:
 at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkState(Preconditions.java:748)
 at com.spotify.scio.transforms.BaseAsyncLookupDoFn.finishBundle(BaseAsyncLookupDoFn.java:201)
```

**Comment by regadas** [comment]
I'm noticing that this happens explicitly with `ScalaAsyncLookupDoFn`.
