### ISSUE TITLE
Wordcount also not working with Flink setup of 1.9.1

### ISSUE THREAD

**Issue by RohitR1** [spotify/scio#3228]
I tried running wordcount with Flink 1.9.1 but it failed with error: 

```bash
[main] INFO org.apache.beam.sdk.io.FileBasedSource - Filepattern gs://dataflow-samples/shakespeare/kinglear.txt matched 1 files with total size 157283
[main] INFO org.apache.flink.client.program.rest.RestClusterClient - Submitting job a0afc70d43baf6aff71159462941d652 (detached: false).
[main] INFO org.apache.flink.runtime.rest.RestClient - Shutting down rest endpoint.
[main] INFO org.apache.flink.runtime.rest.RestClient - Rest endpoint shutdown complete.
[main] ERROR org.apache.beam.runners.flink.FlinkRunner - Pipeline execution failed
org.apache.flink.client.program.ProgramInvocationException: Could not retrieve the execution result. (JobID: a0afc70d43baf6aff71159462941d652)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:255)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:338)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:326)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:301)
	at org.apache.flink.client.RemoteExecutor.executePlanWithJars(RemoteExecutor.java:209)
	at org.apache.flink.client.RemoteExecutor.executePlan(RemoteExecutor.java:186)
	at org.apache.flink.api.java.RemoteEnvironment.execute(RemoteEnvironment.java:173)
	at org.apache.beam.runners.flink.FlinkPipelineExecutionEnvironment.executePipeline(FlinkPipelineExecutionEnvironment.java:150)
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:87)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:317)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:303)
	at com.spotify.scio.ScioContext.execute(ScioContext.scala:639)
	at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:627)
	at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:615)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:704)
	at com.spotify.scio.ScioContext.run(ScioContext.scala:615)
	at scio.WordCount$.main(WordCount.scala:27)
	at scio.WordCount.main(WordCount.scala)
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
	at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$8(RestClusterClient.java:382)
	at org.apache.flink.client.program.rest.RestClusterClient$$Lambda$323/00000000F98EE420.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$8(FutureUtils.java:263)
	at org.apache.flink.runtime.concurrent.FutureUtils$$Lambda$345/00000000F6992020.accept(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.flink.runtime.rest.util.RestClientException: [Internal server error., <Exception on server side:
org.apache.flink.runtime.client.JobSubmissionException: Failed to submit job.
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$internalSubmitJob$2(Dispatcher.java:333)
	at org.apache.flink.runtime.dispatcher.Dispatcher$$Lambda$158/0000000000000000.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: org.apache.flink.runtime.client.JobExecutionException: Could not set up JobManager
	at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:36)
	at org.apache.flink.util.function.CheckedSupplier$$Lambda$160/0000000000000000.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 6 more
Caused by: org.apache.flink.runtime.client.JobExecutionException: Could not set up JobManager
	at org.apache.flink.runtime.jobmaster.JobManagerRunner.<init>(JobManagerRunner.java:152)
	at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:83)
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:375)
	at org.apache.flink.runtime.dispatcher.Dispatcher$$Lambda$159/0000000000000000.get(Unknown Source)
	at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:34)
	... 8 more
Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'DataSource (at textFile@{WordCount.scala:20}:1/Read (org.apache.beam.runners.flink.translation.wrappers.SourceInputFormat))': Loading the input/output formats failed: org.apache.beam.runners.flink.translation.wrappers.SourceInputFormat@49d5286e
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:218)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:106)
	at org.apache.flink.runtime.scheduler.LegacyScheduler.createExecutionGraph(LegacyScheduler.java:207)
	at org.apache.flink.runtime.scheduler.LegacyScheduler.createAndRestoreExecutionGraph(LegacyScheduler.java:184)
	at org.apache.flink.runtime.scheduler.LegacyScheduler.<init>(LegacyScheduler.java:176)
	at org.apache.flink.runtime.scheduler.LegacySchedulerFactory.createInstance(LegacySchedulerFactory.java:70)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:275)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:265)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:98)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:40)
	at org.apache.flink.runtime.jobmaster.JobManagerRunner.<init>(JobManagerRunner.java:146)
	... 12 more
Caused by: java.lang.Exception: Loading the input/output formats failed: org.apache.beam.runners.flink.translation.wrappers.SourceInputFormat@49d5286e
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:156)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:60)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:214)
	... 22 more
Caused by: java.lang.RuntimeException: Deserializing the input/output formats failed: Could not read the user code wrapper: org.apache.beam.runners.core.construction.SerializablePipelineOptions; local class incompatible: stream classdesc serialVersionUID = -5067588320286657615, local class serialVersionUID = 8599785494114821479
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:68)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:153)
	... 24 more
Caused by: org.apache.flink.runtime.operators.util.CorruptConfigurationException: Could not read the user code wrapper: org.apache.beam.runners.core.construction.SerializablePipelineOptions; local class incompatible: stream classdesc serialVersionUID = -5067588320286657615, local class serialVersionUID = 8599785494114821479
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:290)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:66)
	... 25 more
Caused by: java.io.InvalidClassException: org.apache.beam.runners.core.construction.SerializablePipelineOptions; local class incompatible: stream classdesc serialVersionUID = -5067588320286657615, local class serialVersionUID = 8599785494114821479
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2085)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1951)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2494)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2416)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2494)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2416)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:566)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:476)
	at java.util.HashMap.readObject(HashMap.java:1412)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2383)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2494)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2416)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2494)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2416)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:566)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:476)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:576)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:562)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:550)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:511)
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:288)
	... 26 more

End of exception on server side>]
	at org.apache.flink.runtime.rest.RestClient.parseResponse(RestClient.java:389)
	at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$3(RestClient.java:373)
	at org.apache.flink.runtime.rest.RestClient$$Lambda$344/00000000F6991A20.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	... 4 more
Exception in thread "main" java.lang.RuntimeException: Pipeline execution failed
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:90)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:317)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:303)
	at com.spotify.scio.ScioContext.execute(ScioContext.scala:639)
	at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:627)
	at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:615)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:704)
	at com.spotify.scio.ScioContext.run(ScioContext.scala:615)
	at scio.WordCount$.main(WordCount.scala:27)
	at scio.WordCount.main(WordCount.scala)
Caused by: org.apache.flink.client.program.ProgramInvocationException: Could not retrieve the execution result. (JobID: a0afc70d43baf6aff71159462941d652)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:255)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:338)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:326)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:301)
	at org.apache.flink.client.RemoteExecutor.executePlanWithJars(RemoteExecutor.java:209)
	at org.apache.flink.client.RemoteExecutor.executePlan(RemoteExecutor.java:186)
	at org.apache.flink.api.java.RemoteEnvironment.execute(RemoteEnvironment.java:173)
	at org.apache.beam.runners.flink.FlinkPipelineExecutionEnvironment.executePipeline(FlinkPipelineExecutionEnvironment.java:150)
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:87)
	... 9 more
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
	at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$8(RestClusterClient.java:382)
	at org.apache.flink.client.program.rest.RestClusterClient$$Lambda$323/00000000F98EE420.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$8(FutureUtils.java:263)
	at org.apache.flink.runtime.concurrent.FutureUtils$$Lambda$345/00000000F6992020.accept(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.flink.runtime.rest.util.RestClientException: [Internal server error., <Exception on server side:
org.apache.flink.runtime.client.JobSubmissionException: Failed to submit job.
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$internalSubmitJob$2(Dispatcher.java:333)
	at org.apache.flink.runtime.dispatcher.Dispatcher$$Lambda$158/0000000000000000.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: org.apache.flink.runtime.client.JobExecutionException: Could not set up JobManager
	at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:36)
	at org.apache.flink.util.function.CheckedSupplier$$Lambda$160/0000000000000000.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 6 more
Caused by: org.apache.flink.runtime.client.JobExecutionException: Could not set up JobManager
	at org.apache.flink.runtime.jobmaster.JobManagerRunner.<init>(JobManagerRunner.java:152)
	at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:83)
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:375)
	at org.apache.flink.runtime.dispatcher.Dispatcher$$Lambda$159/0000000000000000.get(Unknown Source)
	at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:34)
	... 8 more
Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'DataSource (at textFile@{WordCount.scala:20}:1/Read (org.apache.beam.runners.flink.translation.wrappers.SourceInputFormat))': Loading the input/output formats failed: org.apache.beam.runners.flink.translation.wrappers.SourceInputFormat@49d5286e
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:218)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:106)
	at org.apache.flink.runtime.scheduler.LegacyScheduler.createExecutionGraph(LegacyScheduler.java:207)
	at org.apache.flink.runtime.scheduler.LegacyScheduler.createAndRestoreExecutionGraph(LegacyScheduler.java:184)
	at org.apache.flink.runtime.scheduler.LegacyScheduler.<init>(LegacyScheduler.java:176)
	at org.apache.flink.runtime.scheduler.LegacySchedulerFactory.createInstance(LegacySchedulerFactory.java:70)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:275)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:265)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:98)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:40)
	at org.apache.flink.runtime.jobmaster.JobManagerRunner.<init>(JobManagerRunner.java:146)
	... 12 more
Caused by: java.lang.Exception: Loading the input/output formats failed: org.apache.beam.runners.flink.translation.wrappers.SourceInputFormat@49d5286e
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:156)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:60)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:214)
	... 22 more
Caused by: java.lang.RuntimeException: Deserializing the input/output formats failed: Could not read the user code wrapper: org.apache.beam.runners.core.construction.SerializablePipelineOptions; local class incompatible: stream classdesc serialVersionUID = -5067588320286657615, local class serialVersionUID = 8599785494114821479
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:68)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:153)
	... 24 more
Caused by: org.apache.flink.runtime.operators.util.CorruptConfigurationException: Could not read the user code wrapper: org.apache.beam.runners.core.construction.SerializablePipelineOptions; local class incompatible: stream classdesc serialVersionUID = -5067588320286657615, local class serialVersionUID = 8599785494114821479
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:290)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:66)
	... 25 more
Caused by: java.io.InvalidClassException: org.apache.beam.runners.core.construction.SerializablePipelineOptions; local class incompatible: stream classdesc serialVersionUID = -5067588320286657615, local class serialVersionUID = 8599785494114821479
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2085)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1951)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2494)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2416)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2494)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2416)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:566)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:476)
	at java.util.HashMap.readObject(HashMap.java:1412)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2383)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2494)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2416)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2494)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2416)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:566)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:476)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:576)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:562)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:550)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:511)
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:288)
	... 26 more

End of exception on server side>]
	at org.apache.flink.runtime.rest.RestClient.parseResponse(RestClient.java:389)
	at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$3(RestClient.java:373)
	at org.apache.flink.runtime.rest.RestClient$$Lambda$344/00000000F6991A20.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	... 4 more
TaskFailed - taskid:submit_flink
```

What am I doing wrong? Wat to fix?

**Comment by regadas** [comment]
Hi @RohitR1 is you project using the same Flink version as the cluster? I think I saw this happen with version mismatch.

**Comment by RohitR1** [comment]
> I think I saw this happen with version mismatch.

Both Flink in scio and running flink cluster is 1.9.1

**Comment by regadas** [comment]
I got to try a fresh project generated from https://github.com/spotify/scio.g8 and worked out of the box. So I'm guessing the issue could lie with the Flink cluster you are using.

**Comment by regadas** [comment]
@RohitR1 gonna close this since this is not really a bug. We can keep the discussion though (either here or in the slack channel if you want)

**Comment by regadas** [comment]
@RohitR1 Actually I just realized that you might be mixing scala versions. like you are compiling with 2.12 and using Flink 2.11
