### ISSUE TITLE
Scio Job wordcount failing to write to GCS even though container has permission

### ISSUE THREAD

**Issue by RohitR1** [spotify/scio#3229]
From inside Flink container, I am able to copy files and list files: 
```bash
gsutil ls gs://mybucket/wc/
gs://mybucket/wc/sample.py

gsutil cp README.txt gs://mybucket/wc/
Copying file://README.txt [Content-Type=text/plain]...
- [1 files][  1.3 KiB/  1.3 KiB]
Operation completed over 1 objects/1.3 KiB.
```

I tried following:

```bash
sbt new spotify/scio.g8
sbt stage
target/universal/stage/bin/word-count --output=wc -> Passed
[direct-runner-worker] INFO org.apache.beam.sdk.io.WriteFiles - Finalizing 4 file results
[direct-runner-worker] INFO org.apache.beam.sdk.io.FileBasedSink - Finalizing for destination null num shards 4.

ls wc/
part-00000-of-00004.txt part-00001-of-00004.txt part-00002-of-00004.txt part-00003-of-00004.txt
```

But Scio job is failing with Flink Cluster:
```bash
target/universal/stage/bin/svoc-backfill --output=gs://mybucket/wc/ --runner=FlinkRunner --flinkMaster=localhost:8081
```

Error:

```bash
[main] INFO org.apache.beam.sdk.io.FileBasedSource - Filepattern gs://dataflow-samples/shakespeare/kinglear.txt matched 1 files with total size 157283
[main] INFO org.apache.flink.client.program.rest.RestClusterClient - Submitting job a57cf4d5300fec95647fc1f16193c0be (detached: false).
[main] INFO org.apache.flink.runtime.rest.RestClient - Shutting down rest endpoint.
[main] INFO org.apache.flink.runtime.rest.RestClient - Rest endpoint shutdown complete.
[main] ERROR org.apache.beam.runners.flink.FlinkRunner - Pipeline execution failed
org.apache.flink.client.program.ProgramInvocationException: Job failed. (JobID: a57cf4d5300fec95647fc1f16193c0be)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:262)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:338)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:326)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:301)
	at org.apache.flink.client.RemoteExecutor.executePlanWithJars(RemoteExecutor.java:209)
	at org.apache.flink.client.RemoteExecutor.executePlan(RemoteExecutor.java:186)
	at org.apache.flink.api.java.RemoteEnvironment.execute(RemoteEnvironment.java:173)
	at org.apache.beam.runners.flink.FlinkPipelineExecutionEnvironment.executePipeline(FlinkPipelineExecutionEnvironment.java:150)
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:87)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:317)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:303)
	at com.spotify.scio.ScioContext.execute(ScioContext.scala:639)
	at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:627)
	at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:615)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:704)
	at com.spotify.scio.ScioContext.run(ScioContext.scala:615)
	at scio.WordCount$.main(WordCount.scala:27)
	at scio.WordCount.main(WordCount.scala)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:146)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:259)
	... 17 more
Caused by: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: Unable to get application default credentials. Please see https://developers.google.com/accounts/docs/application-default-credentials for details on how to specify credentials. This version of the SDK is dependent on the gcloud core component version 2015.02.05 or newer to be able to get credentials from the currently authorized user via gcloud auth.
	at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:36)
	at org.apache.beam.sdk.io.WriteFiles$WriteUnshardedTempFilesFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:227)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:183)
	at org.apache.beam.runners.flink.metrics.DoFnRunnerWithMetricsUpdate.processElement(DoFnRunnerWithMetricsUpdate.java:62)
	at org.apache.beam.runners.flink.translation.functions.FlinkDoFnFunction.flatMap(FlinkDoFnFunction.java:121)
	at org.apache.beam.runners.flink.translation.functions.FlinkDoFnFunction.mapPartition(FlinkDoFnFunction.java:132)
	at org.apache.flink.runtime.operators.MapPartitionDriver.run(MapPartitionDriver.java:103)
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:504)
	at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:369)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to get application default credentials. Please see https://developers.google.com/accounts/docs/application-default-credentials for details on how to specify credentials. This version of the SDK is dependent on the gcloud core component version 2015.02.05 or newer to be able to get credentials from the currently authorized user via gcloud auth.
	at org.apache.beam.sdk.extensions.gcp.auth.NullCredentialInitializer.throwNullCredentialException(NullCredentialInitializer.java:60)
	at org.apache.beam.sdk.extensions.gcp.auth.NullCredentialInitializer$NullCredentialHttpUnsuccessfulResponseHandler.handleResponse(NullCredentialInitializer.java:53)
	at com.google.cloud.hadoop.util.ChainingHttpRequestInitializer$3.handleResponse(ChainingHttpRequestInitializer.java:111)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:542)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:475)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:592)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getObject(GoogleCloudStorageImpl.java:1955)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfo(GoogleCloudStorageImpl.java:1857)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getWriteGeneration(GoogleCloudStorageImpl.java:1926)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.create(GoogleCloudStorageImpl.java:374)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.create(GcsUtil.java:475)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.create(GcsUtil.java:445)
	at org.apache.beam.sdk.extensions.gcp.storage.GcsFileSystem.create(GcsFileSystem.java:127)
	at org.apache.beam.sdk.extensions.gcp.storage.GcsFileSystem.create(GcsFileSystem.java:60)
	at org.apache.beam.sdk.io.FileSystems.create(FileSystems.java:239)
	at org.apache.beam.sdk.io.FileSystems.create(FileSystems.java:226)
	at org.apache.beam.sdk.io.FileBasedSink$Writer.open(FileBasedSink.java:938)
	at org.apache.beam.sdk.io.WriteFiles$WriteUnshardedTempFilesFn.processElement(WriteFiles.java:534)
Exception in thread "main" java.lang.RuntimeException: Pipeline execution failed
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:90)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:317)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:303)
	at com.spotify.scio.ScioContext.execute(ScioContext.scala:639)
	at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:627)
	at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:615)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:704)
	at com.spotify.scio.ScioContext.run(ScioContext.scala:615)
	at scio.WordCount$.main(WordCount.scala:27)
	at scio.WordCount.main(WordCount.scala)
Caused by: org.apache.flink.client.program.ProgramInvocationException: Job failed. (JobID: a57cf4d5300fec95647fc1f16193c0be)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:262)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:338)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:326)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:301)
	at org.apache.flink.client.RemoteExecutor.executePlanWithJars(RemoteExecutor.java:209)
	at org.apache.flink.client.RemoteExecutor.executePlan(RemoteExecutor.java:186)
	at org.apache.flink.api.java.RemoteEnvironment.execute(RemoteEnvironment.java:173)
	at org.apache.beam.runners.flink.FlinkPipelineExecutionEnvironment.executePipeline(FlinkPipelineExecutionEnvironment.java:150)
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:87)
	... 9 more
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:146)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:259)
	... 17 more
Caused by: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: Unable to get application default credentials. Please see https://developers.google.com/accounts/docs/application-default-credentials for details on how to specify credentials. This version of the SDK is dependent on the gcloud core component version 2015.02.05 or newer to be able to get credentials from the currently authorized user via gcloud auth.
	at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:36)
	at org.apache.beam.sdk.io.WriteFiles$WriteUnshardedTempFilesFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:227)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:183)
	at org.apache.beam.runners.flink.metrics.DoFnRunnerWithMetricsUpdate.processElement(DoFnRunnerWithMetricsUpdate.java:62)
	at org.apache.beam.runners.flink.translation.functions.FlinkDoFnFunction.flatMap(FlinkDoFnFunction.java:121)
	at org.apache.beam.runners.flink.translation.functions.FlinkDoFnFunction.mapPartition(FlinkDoFnFunction.java:132)
	at org.apache.flink.runtime.operators.MapPartitionDriver.run(MapPartitionDriver.java:103)
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:504)
	at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:369)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to get application default credentials. Please see https://developers.google.com/accounts/docs/application-default-credentials for details on how to specify credentials. This version of the SDK is dependent on the gcloud core component version 2015.02.05 or newer to be able to get credentials from the currently authorized user via gcloud auth.
	at org.apache.beam.sdk.extensions.gcp.auth.NullCredentialInitializer.throwNullCredentialException(NullCredentialInitializer.java:60)
	at org.apache.beam.sdk.extensions.gcp.auth.NullCredentialInitializer$NullCredentialHttpUnsuccessfulResponseHandler.handleResponse(NullCredentialInitializer.java:53)
	at com.google.cloud.hadoop.util.ChainingHttpRequestInitializer$3.handleResponse(ChainingHttpRequestInitializer.java:111)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:542)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:475)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:592)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getObject(GoogleCloudStorageImpl.java:1955)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfo(GoogleCloudStorageImpl.java:1857)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getWriteGeneration(GoogleCloudStorageImpl.java:1926)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.create(GoogleCloudStorageImpl.java:374)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.create(GcsUtil.java:475)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.create(GcsUtil.java:445)
	at org.apache.beam.sdk.extensions.gcp.storage.GcsFileSystem.create(GcsFileSystem.java:127)
	at org.apache.beam.sdk.extensions.gcp.storage.GcsFileSystem.create(GcsFileSystem.java:60)
	at org.apache.beam.sdk.io.FileSystems.create(FileSystems.java:239)
	at org.apache.beam.sdk.io.FileSystems.create(FileSystems.java:226)
	at org.apache.beam.sdk.io.FileBasedSink$Writer.open(FileBasedSink.java:938)
	at org.apache.beam.sdk.io.WriteFiles$WriteUnshardedTempFilesFn.processElement(WriteFiles.java:534)
```

What am I doing wrong? Can I get a good guide to solve this error?

**Comment by regadas** [comment]
Hi @RohitR1 we don't have a guide yet. Have you trying setting this according to https://developers.google.com/accounts/docs/application-default-credentials in the cluster? Make sure the credentials are reachable within the container.

**Comment by RohitR1** [comment]
> Make sure the credentials are reachable within the container.

Yes, I exec into container and ran these: 

```bash
gsutil ls gs://mybucket/wc/
gs://mybucket/wc/sample.py

gsutil cp README.txt gs://mybucket/wc/
Copying file://README.txt [Content-Type=text/plain]...
- [1 files][  1.3 KiB/  1.3 KiB]
Operation completed over 1 objects/1.3 KiB.
```

But Scio job failed

**Comment by RohitR1** [comment]
What can be reason for failure?

**Comment by regadas** [comment]
Hi @RohitR1, tried to replicate this and it seems that your credentials are not properly set under env `GOOGLE_APPLICATION_CREDENTIALS`. Make sure `jobmanager` and `taskmanager`'s have this env set.

Not sure how you are setting up the cluster locally but I recommend using minikube https://ci.apache.org/projects/flink/flink-docs-stable/ops/deployment/kubernetes.html

setting up credentials:

```bash
kubectl create secret generic gcloud-sa --from-file=key.json // create one in the console with enough perms
```

Create the volume and mount it in the `jobmanager` and `taskmanager` containers:
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

```yaml
volumeMounts:
  - name: gcloud-sa-volume
    mountPath: /etc/gcloud-sa
    readOnly: true

volumes:
  - name: gcloud-sa-volume
    secret:
      secretName: gcloud-sa
```

Set the env in the container:
```yaml
env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/gcloud-sa/key.json
```

**Comment by regadas** [comment]
@RohitR1 gonna close this since this is not really a bug. We can keep the discussion though (either here or in the slack channel if you want)
