### ISSUE TITLE
SMB IO should warn on non-directory inputs

### ISSUE THREAD

**Issue by kellen** [spotify/scio#3277]
When using e.g. `AvroSortedBucketIO`, if a file pattern is passed as part of the input path, scio should output a helpful error message. Current behavior in `0.9.3` leads to a NullPointerException.

```
val myEntityPaths: List[String] = List(
  "gs://bucket/dir1/*.avro",
  "gs://bucket/dir2/*.avro",
)
sc.sortMergeCoGroup(
  classOf[String],
  AvroSortedBucketIO
    .read(new TupleTag[MyEntity]("MyEntity"), classOf[MyEntity])
    .from(myEntityPaths.asJava),
  // ...
).map { ... }
```

Error:
```
INFO: Exception in thread "main" java.lang.NullPointerException
INFO:   at org.apache.beam.sdk.extensions.smb.SourceSpec.from(SourceSpec.java:59)
INFO:   at org.apache.beam.sdk.extensions.smb.SortedBucketSource.getOrComputeSourceSpec(SortedBucketSource.java:191)
INFO:   at org.apache.beam.sdk.extensions.smb.SortedBucketSource.getOutputCoder(SortedBucketSource.java:199)
INFO:   at org.apache.beam.sdk.io.Read$Bounded.expand(Read.java:158)
INFO:   at org.apache.beam.sdk.io.Read$Bounded.expand(Read.java:126)
INFO:   at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:542)
INFO:   at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:476)
INFO:   at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:44)
INFO:   at org.apache.beam.sdk.extensions.smb.SortedBucketIO$CoGbk.expand(SortedBucketIO.java:128)
INFO:   at org.apache.beam.sdk.extensions.smb.SortedBucketIO$CoGbk.expand(SortedBucketIO.java:79)
INFO:   at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:542)
INFO:   at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:493)
INFO:   at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:56)
INFO:   at org.apache.beam.sdk.Pipeline.apply(Pipeline.java:186)
INFO:   at com.spotify.scio.smb.syntax.SortedBucketScioContext.sortMergeCoGroup(SortMergeBucketScioContextSyntax.scala:285)
INFO:   at com.spotify.scio.smb.syntax.SortedBucketScioContext.sortMergeCoGroup(SortMergeBucketScioContextSyntax.scala:309)
```

**Comment by ClaireMcGinty** [comment]
thanks for reporting! this has been fixed in #3253 and will be included in the 0.9.4 release.

https://github.com/spotify/scio/blob/master/scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java#L465-L482
