### ISSUE TITLE
Getting a ClassCastException Error when trying to create an SCollection of certain types

### ISSUE THREAD

**Issue by wayoung** [spotify/scio#3680]
Trying to upgrade from Scio v0.9.6 to v0.10.0. After the upgrade, I am seeing this error:

> Cause: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field com.spotify.scio.coders.LowPriorityCoderDerivation$$anonfun$dispatch$2.idx$1 of type scala.collection.immutable.Map in instance of com.spotify.scio.coders.LowPriorityCoderDerivation$$anonfun$dispatch$2

After narrowing down the offending code in one of my tests, I found that even this trivial code in one of my tests causes the error.

```
"test" should "test" in {
    runWithContext { sc =>

      sc.parallelize(Seq(myTestClass))

    }
  }
```

`myTestClass` is a case class with the following definition:

```
case class MyTestClass(
  topType: Option[play_context.TopType]
)

val myTestClass = MyTestClass(None)
```

This type `play_context.TopType` is a type which used to work in the 0.9.6 version of Scio, but somehow fails with the aforementioned error in 0.10.0. The same goes for `play_context.SubType`. I'm not sure what about this class causes the error as there are no `Map` or `HashMap` objects in the definition, but something definitely changed.

**Comment by ClaireMcGinty** [comment]
Looking at your code, I reconstructed your data types and unit test setup in a clean repo, running Scio 0.10.0 and `"com.beachape" %% "enumeratum" % "1.6.1"`, and it runs successfully:

```scala
package org.clairem

import com.spotify.scio.testing._
import enumeratum._
import enumeratum.EnumEntry._

sealed abstract class TestType(val value: Int) extends Snakecase

object TestType extends Enum[TestType] {
  val values = findValues
  case object TestTypeObject extends TestType(1)
}

case class TestCaseClass(testType: Option[TestType])

class CodersTest extends PipelineSpec {
  import org.clairem.TestType.TestTypeObject
  
  val testTypeObject = TestCaseClass(Some(TestTypeObject))

  "Enumeration encoding" should "work" in {
    runWithContext { sc =>
      sc.parallelize(Seq(testTypeObject)) should containInAnyOrder(Seq(testTypeObject))
    }
  }
}
```

Can you try to run this example in your repo and check whether it works? I think we need to further narrow down where this bug is.

**Comment by wayoung** [comment]
There is something wrong with the `TopType` class, I just can't figure out what. I tested the following code, and the `TestType` example worked. The `TopType` example had the same error:

```
package com.spotify.data.babka.external_sources

import com.spotify.scio.testing._
import enumeratum._
import enumeratum.EnumEntry._
import com.spotify.jamalytics.play_context.TopType._

sealed abstract class TestType(val value: Int) extends Snakecase

object TestType extends Enum[TestType] {
  val values = findValues
  case object TestTypeObject extends TestType(1)
}

case class TestCaseClass(testType: Option[TestType])
case class TopTypeCaseClass(topType: Option[com.spotify.jamalytics.play_context.TopType])

class CodersTest extends PipelineSpec {
  import com.spotify.data.babka.external_sources.TestType.TestTypeObject

  val testTypeObject = TestCaseClass(Some(TestTypeObject))
  val topTypeObject = TopTypeCaseClass(Some(Catalog))

  "Enumeration encoding for TestType" should "work" in {
    runWithContext { sc =>
      sc.parallelize(Seq(testTypeObject)) should containInAnyOrder(Seq(testTypeObject))
    }
  }

  "Enumeration encoding for TopType" should "work" in {
    runWithContext { sc =>
      sc.parallelize(Seq(topTypeObject)) should containInAnyOrder(Seq(topTypeObject))
    }
  }
}
```

**Comment by wayoung** [comment]
Here's the error:

```
15:34:21.828Z [info] CodersTest:
15:34:21.828Z [info] Enumeration encoding for TestType
15:34:21.828Z [info] - should work (7 seconds, 121 milliseconds)
15:34:21.828Z [info] Enumeration encoding for TopType
15:34:21.828Z [info] - should work *** FAILED *** (844 milliseconds)
15:34:21.828Z [info]   org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field com.spotify.scio.coders.LowPriorityCoderDerivation$$anonfun$dispatch$2.idx$1 of type scala.collection.immutable.Map in instance of com.spotify.scio.coders.LowPriorityCoderDerivation$$anonfun$dispatch$2
15:34:21.828Z [info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:371)
15:34:21.828Z [info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:339)
15:34:21.828Z [info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:219)
15:34:21.828Z [info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
...
```

**Comment by ClaireMcGinty** [comment]
We resolved this by adding the SBT config `fork in Test := true` to the module.
