### ISSUE TITLE
Scio 0.10.0 not working with Enumeratum Enums

### ISSUE THREAD

**Issue by wayoung** [spotify/scio#3693]
This issue is a follow up to this [issue][1]. It shows a ClassCastException for Scio 0.10.0 on any Enums created with the [Enumeratum][2] library.

The initial issue was solved by adding this line to `build.sbt`:

> fork in Test := true

which allowed the tests to pass. But it does not seem to address the root cause because this fix does not work in every repo the error comes up in.

A full stack trace of the error is reproduced here:

```
[info]   org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field com.spotify.scio.coders.LowPriorityCoderDerivation$$anonfun$dispatch$2.idx$1 of type scala.collection.immutable.Map in instance of com.spotify.scio.coders.LowPriorityCoderDerivation$$anonfun$dispatch$2
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:371)
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:339)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:219)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
[info]   at org.apache.beam.sdk.Pipeline.run(Pipeline.java:322)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:398)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:334)
[info]   at com.spotify.scio.ScioContext.execute(ScioContext.scala:652)
[info]   at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:640)
[info]   at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:628)
[info]   at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:718)
[info]   at com.spotify.scio.ScioContext.run(ScioContext.scala:628)
[info]   at com.spotify.scio.testing.PipelineTestUtils.runWithContext(PipelineTestUtils.scala:41)
[info]   at com.spotify.scio.testing.PipelineTestUtils.runWithContext$(PipelineTestUtils.scala:38)
[info]   at com.spotify.data.babka.s4x_entities.TrackUserEntityPipelineTest.runWithContext(TrackUserEntityPipelineTest.scala:25)
[info]   at com.spotify.data.babka.s4x_entities.TrackUserEntityPipelineTest.$anonfun$new$300(TrackUserEntityPipelineTest.scala:93)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1684)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at com.spotify.data.babka.s4x_entities.TrackUserEntityPipelineTest.com$spotify$scio$testing$RunEnforcementJobTest$$super$withFixture(TrackUserEntityPipelineTest.scala:25)
[info]   at com.spotify.scio.testing.RunEnforcementJobTest.withFixture(RunEnforcementJobTest.scala:55)
[info]   at com.spotify.scio.testing.RunEnforcementJobTest.withFixture$(RunEnforcementJobTest.scala:51)
[info]   at com.spotify.data.babka.s4x_entities.TrackUserEntityPipelineTest.withFixture(TrackUserEntityPipelineTest.scala:25)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1682)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1694)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1694)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1676)
[info]   at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1752)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:431)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[info]   at scala.collection.immutable.List.foreach(List.scala:431)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1752)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1751)
[info]   at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
[info]   at org.scalatest.Suite.run(Suite.scala:1112)
[info]   at org.scalatest.Suite.run$(Suite.scala:1094)
[info]   at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1797)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1797)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1795)
[info]   at com.spotify.data.babka.s4x_entities.TrackUserEntityPipelineTest.com$spotify$scio$testing$PipelineSpec$$super$run(TrackUserEntityPipelineTest.scala:25)
[info]   at com.spotify.scio.testing.PipelineSpec.run(PipelineSpec.scala:74)
[info]   at com.spotify.scio.testing.PipelineSpec.run$(PipelineSpec.scala:70)
[info]   at com.spotify.data.babka.s4x_entities.TrackUserEntityPipelineTest.run(TrackUserEntityPipelineTest.scala:25)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:139)
[info]   at sbt.TestRunner.run(TestFramework.scala:154)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:317)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:277)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)
[info]   at sbt.TestFunction.apply(TestFramework.scala:329)
[info]   at sbt.Tests$.$anonfun$toTask$1(Tests.scala:311)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[info]   at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[info]   at sbt.Execute.work(Execute.scala:290)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
[info]   Cause: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field com.spotify.scio.coders.LowPriorityCoderDerivation$$anonfun$dispatch$2.idx$1 of type scala.collection.immutable.Map in instance of com.spotify.scio.coders.LowPriorityCoderDerivation$$anonfun$dispatch$2
[info]   at java.base/java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2205)
[info]   at java.base/java.io.ObjectStreamClass$FieldReflector.checkObjectFieldValueTypes(ObjectStreamClass.java:2168)
[info]   at java.base/java.io.ObjectStreamClass.checkObjFieldValueTypes(ObjectStreamClass.java:1422)
[info]   at java.base/java.io.ObjectInputStream.defaultCheckFieldValues(ObjectInputStream.java:2428)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2335)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2050)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1634)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2050)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1634)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
[info]   at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
[info]   at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
[info]   at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
[info]   at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
[info]   at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
[info]   at org.apache.beam.sdk.coders.SerializableCoder.decode(SerializableCoder.java:194)
[info]   at org.apache.beam.sdk.coders.SerializableCoder.decode(SerializableCoder.java:54)
[info]   at org.apache.beam.sdk.coders.Coder.decode(Coder.java:159)
[info]   at org.apache.beam.sdk.util.CoderUtils.decodeFromSafeStream(CoderUtils.java:118)
[info]   at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:101)
[info]   at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:95)
[info]   at org.apache.beam.sdk.util.CoderUtils.clone(CoderUtils.java:144)
[info]   at org.apache.beam.runners.direct.CloningBundleFactory$CloningBundle.add(CloningBundleFactory.java:87)
[info]   at org.apache.beam.runners.direct.ParDoEvaluator$BundleOutputManager.output(ParDoEvaluator.java:305)
[info]   at org.apache.beam.repackaged.direct_java.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:272)
[info]   at org.apache.beam.repackaged.direct_java.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:84)
[info]   at org.apache.beam.repackaged.direct_java.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:418)
[info]   at org.apache.beam.sdk.transforms.DoFnOutputReceivers$WindowedContextOutputReceiver.output(DoFnOutputReceivers.java:76)
[info]   at org.apache.beam.sdk.io.Read$OutputSingleSource.processElement(Read.java:979)
```

[1]: https://github.com/spotify/scio/issues/3680
[2]: https://github.com/lloydmeta/enumeratum

**Comment by Evg3n** [comment]
So for the testing...I had a test failure and I found that there was one enum defined using Enumeratum library. I tried to change enum to use the regular Scala style for creating enums (extend Enumeration). The test was successful after that.
Also, the pipeline was successful on the cluster without that change. So it only seems to affect tests.

**Comment by wayoung** [comment]
To reproduce the error:

1) Copy the below code into your test suite that uses scio v0.10.0
2) Run the following command to run the test: `sbt "testOnly *CodersTest"`

```
package com.spotify.data.babka

import com.spotify.scio.testing._
import enumeratum._
import enumeratum.EnumEntry._

sealed abstract class TestType(val value: Int) extends Snakecase

object TestType extends Enum[TestType] {
  val values = findValues
  case object TestTypeObject1 extends TestType(1)
  case object TestTypeObject2 extends TestType(2)
  case object TestTypeObject3 extends TestType(3)
  case object TestTypeObject4 extends TestType(4)
  case object TestTypeObject5 extends TestType(5)
}

case class TestCaseClass(testType: Option[TestType])

class CodersTest extends PipelineSpec {
  import com.spotify.data.babka.TestType.TestTypeObject2

  val testTypeObject = TestCaseClass(Some(TestTypeObject2))

  "Enumeration encoding for TestType" should "work" in {
    runWithContext { sc =>
      sc.parallelize(Seq(testTypeObject))
    }
  }
}
```

**Comment by nevillelyh** [comment]
Cannot repro. Check your sbt settings?

```
git pull
git checkout neville/3693
sbt "+scio-examples/testOnly CodersTest"
```

Both 2.12 & 2.13 pass.
