### ISSUE TITLE
NPE on required field of repeated record

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#371]
Generated companion's method `fromTableRow` for:

```
[
  {
    "fields": [
      {
        "fields": [
          {
            "type": "STRING",
            "name": "b",
            "mode": "REQUIRED"
          }
        ],
        "type": "RECORD",
        "name": "a",
        "mode": "REPEATED"
      }
    ],
    "type": "RECORD",
    "name": "r",
    "mode": "NULLABLE"
  },
  {
    "type": "STRING",
    "name": "foo",
    "mode": "NULLABLE"
  }
]
```

throws NPE. To reproduce:
1. use the schema above
2. add single row - with `foo: "bar"` and no value for `r`
3. generated BQT class
4. `sc.typedBigQuery[<BQT-class>]().closeAndCollect`

Example:

```
scio> sc.typedBigQuery[T]().closeAndCollect()                                                                                                                                 [0/995]
[main] INFO com.google.cloud.dataflow.sdk.options.GcpOptions$DefaultProjectFactory - Inferred default GCP project 'scio-playground' from gcloud. If this is the incorrect project, please cancel this Pipeline and specify the command-line argument --project.
[main] WARN com.spotify.scio.bigquery.BigQueryClient - Legacy syntax is deprecated, use SQL syntax instead. See https://cloud.google.com/bigquery/sql-reference/
[main] WARN com.spotify.scio.bigquery.BigQueryClient - Legacy query: `SELECT * FROM [scio-playground:ravioli.npe3]`
[main] WARN com.spotify.scio.bigquery.BigQueryClient - Legacy syntax is deprecated, use SQL syntax instead. See https://cloud.google.com/bigquery/sql-reference/
[main] WARN com.spotify.scio.bigquery.BigQueryClient - Legacy query: `SELECT * FROM [scio-playground:ravioli.npe3]`
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Cache miss for query: `SELECT * FROM [scio-playground:ravioli.npe3]`
[main] INFO com.spotify.scio.bigquery.BigQueryClient - New destination table: scio-playground:scio_bigquery_staging_eu.scio_query_20161216203101_866995684
[main] WARN com.spotify.scio.bigquery.BigQueryClient - Legacy syntax is deprecated, use SQL syntax instead. See https://cloud.google.com/bigquery/sql-reference/
[main] WARN com.spotify.scio.bigquery.BigQueryClient - Legacy query: `SELECT * FROM [scio-playground:ravioli.npe3]`
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Staging dataset scio-playground:scio_bigquery_staging_eu already exists
[main] WARN com.spotify.scio.bigquery.BigQueryClient - Legacy syntax is deprecated, use SQL syntax instead. See https://cloud.google.com/bigquery/sql-reference/
[main] WARN com.spotify.scio.bigquery.BigQueryClient - Legacy query: `SELECT * FROM [scio-playground:ravioli.npe3]`
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Executing legacy query: `SELECT * FROM [scio-playground:ravioli.npe3]`
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Query: 0 out of 1 completed
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Query completed: jobId: scio-playground-f18f016a-6cd2-4a47-b373-eee52582662d
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Query: `SELECT * FROM [scio-playground:ravioli.npe3]`
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Elapsed: 6.618s, pending: 0.319s, execution: 6.299s
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Total bytes processed: 5 bytes, cache hit: false
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Query: 1 out of 1 completed
[pool-1-thread-1] INFO com.google.cloud.dataflow.sdk.io.Write - Initializing write operation com.google.cloud.dataflow.sdk.io.PatchedAvroIO$AvroSink$AvroWriteOperation@72614f51
[pool-1-thread-2] INFO com.google.cloud.dataflow.sdk.util.BigQueryServicesImpl - No BigQuery job with job id beam_job_fca735ce1ec94d77be57ba7a1020c603-extract found.
com.google.cloud.dataflow.sdk.Pipeline$PipelineExecutionException: java.lang.NullPointerException
  at com.google.cloud.dataflow.sdk.runners.inprocess.InProcessPipelineRunner.run(InProcessPipelineRunner.java:280)
  at com.google.cloud.dataflow.sdk.runners.inprocess.InProcessPipelineRunner.run(InProcessPipelineRunner.java:69)
  at com.google.cloud.dataflow.sdk.Pipeline.run(Pipeline.java:181)
  at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:303)
  at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:297)
  at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:343)
  at com.spotify.scio.repl.ReplScioContext.requireNotClosed(ReplScioContext.scala:37)
  at com.spotify.scio.ScioContext.close(ScioContext.scala:297)
  at com.spotify.scio.repl.ReplScioContext.close(ReplScioContext.scala:30)
  at com.spotify.scio.repl.package$ReplSCollection.closeAndCollect(package.scala:33)
  ... 32 elided
Caused by: java.lang.NullPointerException
  at T$$anonfun$fromTableRow$1$$anonfun$apply$1.apply(<console>:29)
  at T$$anonfun$fromTableRow$1$$anonfun$apply$1.apply(<console>:29)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at T$$anonfun$fromTableRow$1.apply(<console>:29)
  at T$$anonfun$fromTableRow$1.apply(<console>:29)
  at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:142)
```

**Comment by ravwojdyla** [comment]
Looks like we are not handling the case when the list (repeated field) is `null`/empty.

**Comment by ravwojdyla** [comment]
This seems to be one of the legacy SQL corner cases, can't reproduce this in the standard SQL.

**Comment by ravwojdyla** [comment]
Given that it's the legacy SQL issue, won't fix.
