### ISSUE TITLE
SCIO 0.10.x NPE on Scala class wrapped Protocol Buffer Entity

### ISSUE THREAD

**Issue by rich-j** [spotify/scio#3752]
Migrating from `SCIO` 0.9.6 to 0.10.2 fails for us. We read data from Google datastores as Protocol Buffer entities and pass the `Entity` data structure through our SCIO pipelines. We "wrap" the entity into a Scala class that provides access to our data properties but the only data structure that is serialized is the `Entity`. Migrating to `SCIO` 0.10.x and `beam` 2.28.0 fails with an NPE in `guava`. Here's the failure stacktrace:

<details>
  <summary>Stacktrace</summary>
  
```
[error] (run-main-0) java.lang.NullPointerException: null value in entry: T=null
[error] java.lang.NullPointerException: null value in entry: T=null
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:100)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.RegularImmutableMap.fromEntries(RegularImmutableMap.java:74)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:464)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:437)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.reflect.TypeResolver$TypeMappingIntrospector.getTypeMappings(TypeResolver.java:385)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.reflect.TypeResolver.covariantly(TypeResolver.java:75)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.reflect.TypeToken.getCovariantTypeResolver(TypeToken.java:1181)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.reflect.TypeToken.resolveSupertype(TypeToken.java:273)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.reflect.TypeToken.getSupertype(TypeToken.java:398)
[error] 	at org.apache.beam.sdk.values.TypeDescriptor.getSupertype(TypeDescriptor.java:188)
[error] 	at org.apache.beam.sdk.util.CoderUtils.getCodedType(CoderUtils.java:176)
[error] 	at org.apache.beam.sdk.coders.CoderRegistry.verifyCompatible(CoderRegistry.java:510)
[error] 	at org.apache.beam.sdk.coders.CoderRegistry.getDefaultCoders(CoderRegistry.java:438)
[error] 	at org.apache.beam.sdk.coders.CoderRegistry.getDefaultCoders(CoderRegistry.java:371)
[error] 	at org.apache.beam.sdk.coders.CoderRegistry.getCoder(CoderRegistry.java:321)
[error] 	at org.apache.beam.sdk.transforms.CombineFnBase$AbstractGlobalCombineFn.getDefaultOutputCoder(CombineFnBase.java:129)
[error] 	at org.apache.beam.sdk.transforms.Combine$CombineFn.getDefaultOutputCoder(Combine.java:391)
[error] 	at org.apache.beam.sdk.transforms.Combine$GroupedValues.expand(Combine.java:2219)
[error] 	at org.apache.beam.sdk.transforms.Combine$GroupedValues.expand(Combine.java:2124)
[error] 	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:547)
[error] 	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:481)
[error] 	at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:357)
[error] 	at org.apache.beam.sdk.transforms.Combine$PerKey.expand(Combine.java:1625)
[error] 	at org.apache.beam.sdk.transforms.Combine$PerKey.expand(Combine.java:1513)
[error] 	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:547)
[error] 	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:481)
[error] 	at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:357)
[error] 	at org.apache.beam.sdk.transforms.Combine$Globally.expand(Combine.java:1189)
[error] 	at org.apache.beam.sdk.transforms.Combine$Globally.expand(Combine.java:1073)
[error] 	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:547)
[error] 	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:498)
[error] 	at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:370)
[error] 	at com.spotify.scio.values.PCollectionWrapper.applyInternal(PCollectionWrapper.scala:42)
[error] 	at com.spotify.scio.values.PCollectionWrapper.applyInternal$(PCollectionWrapper.scala:38)
[error] 	at com.spotify.scio.values.SCollectionImpl.applyInternal(SCollection.scala:1545)
[error] 	at com.spotify.scio.values.SCollection.pApply(SCollection.scala:208)
[error] 	at com.spotify.scio.values.SCollection.pApply$(SCollection.scala:194)
[error] 	at com.spotify.scio.values.SCollectionImpl.pApply(SCollection.scala:1545)
[error] 	at com.spotify.scio.values.SCollection.pApply(SCollection.scala:214)
[error] 	at com.spotify.scio.values.SCollection.pApply$(SCollection.scala:211)
[error] 	at com.spotify.scio.values.SCollectionImpl.pApply(SCollection.scala:1545)
[error] 	at com.spotify.scio.values.SCollection.count(SCollection.scala:501)
[error] 	at com.spotify.scio.values.SCollection.count$(SCollection.scala:500)
[error] 	at com.spotify.scio.values.SCollectionImpl.count(SCollection.scala:1545)
[error] 	at gd.Check$.main(Check.scala:42)
[error] 	at gd.Check.main(Check.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run 'last Compile / bgRunMain' for the full output
[error] Nonzero exit code: 1
```
</details>

We have isolated some code that reproduces the issue:

```scala
// ...other SCIO imports...
import com.google.datastore.v1.{Entity, KindExpression, Query}

def main(cmdlineArgs: Array[String]): Unit = {
  val (sc, args) = ContextAndArgs(cmdlineArgs)
  implicit val dataCheckContext: DataCheckContext = DataCheckContext(cmdlineArgs)

  // If no data exists for datastore "kind" SCIO will provide a warning but still function
  val kind = KindExpression.newBuilder().setName("person").build()    // "person" is a name that exists in our datastore
  val query = Query.newBuilder().addKind(kind).build()

  // Retrieve data entities and wrap in a class that can extract application properties
  val allData = sc.datastore(dataCheckContext.projectId, query)
    .map( (entity: Entity) => {
      Some(new XP(entity))    // <-- This works : SCollection[Option[XP]]
//      new XP(entity)        // <-- This fails and is really what we want : SCollection[XP]
    } )

  val countTap: ClosedTap[Long] = allData.count.materialize   // <-- NPE exception is thrown on the "count" call
  val result = sc.run().waitUntilFinish()
  println(s"Count ${result.tap(countTap).value.sum}")
}

// Class that "wraps" an entity and provides accessors to application properties (none needed in this example)
class XP(val entity: Entity) {}

// Serialization only has to deal with the protocol buffer entity
object XP {
  implicit def xpCoder: Coder[XP] =
    Coder.xmap(Coder[Entity])(e => new XP(e), o => o.entity)
}
```

In our code, the `allData` value is an `SCollection` of `entity` that we use a `map` function to wrap each `entity` into Scala class `XP`. The `XP` class has various accessors for the data contained in the `entity`. The companion object provides a `Coder` that can serialize the object as the Protocol Buffer entity. This has worked well for us up though `SCIO` 0.9.6.

**Comment by rich-j** [comment]
Replaced with simplified test case in #3895
