### ISSUE TITLE
Flink execution can throw EOFException on serialization

### ISSUE THREAD

**Issue by regadas** [spotify/scio#3800]
I haven't looked into this yet, but I'm seeing these popping up from time to time.

```
java.io.EOFException: Can't collect further: memorySource depleted
	at Due to Exception while trying to `encode` an instance of Tuple2: Can't decode field _1.(:0)
	at org.apache.flink.runtime.io.disk.SimpleCollectingOutputView.nextSegment(SimpleCollectingOutputView.java:76)
	at org.apache.flink.runtime.memory.AbstractPagedOutputView.advance(AbstractPagedOutputView.java:139)
	at org.apache.flink.runtime.memory.AbstractPagedOutputView.write(AbstractPagedOutputView.java:205)
	at org.apache.beam.runners.flink.translation.wrappers.DataOutputViewWrapper.write(DataOutputViewWrapper.java:44)
	at java.base/java.io.DataOutputStream.write(Unknown Source)
	at java.base/java.io.FilterOutputStream.write(Unknown Source)
	at org.apache.beam.sdk.coders.StringUtf8Coder.writeString(StringUtf8Coder.java:51)
	at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:84)
	at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:68)
	at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:37)
	at com.spotify.scio.coders.instances.Tuple2Coder$$anonfun$encode$2.apply$mcV$sp(TupleCoders.scala:56)
	at com.spotify.scio.coders.instances.Tuple2Coder$$anonfun$encode$2.apply(TupleCoders.scala:56)
	at com.spotify.scio.coders.instances.Tuple2Coder$$anonfun$encode$2.apply(TupleCoders.scala:56)
	at com.spotify.scio.coders.instances.Tuple2Coder.onErrorMsg(TupleCoders.scala:41)
	at com.spotify.scio.coders.instances.Tuple2Coder.encode(TupleCoders.scala:56)
	at com.spotify.scio.coders.instances.Tuple2Coder.encode(TupleCoders.scala:35)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply$mcV$sp(Coder.scala:269)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply(Coder.scala:269)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply(Coder.scala:269)
	at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:259)
	at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:269)
	at org.apache.beam.sdk.coders.IterableLikeCoder.encode(IterableLikeCoder.java:114)
	at org.apache.beam.sdk.coders.IterableLikeCoder.encode(IterableLikeCoder.java:60)
	at org.apache.beam.sdk.transforms.Top$BoundedHeapCoder.encode(Top.java:547)
	at org.apache.beam.sdk.transforms.Top$BoundedHeapCoder.encode(Top.java:532)
	at org.apache.beam.sdk.coders.Coder.encode(Coder.java:136)
	at org.apache.beam.sdk.coders.KvCoder.encode(KvCoder.java:73)
	at org.apache.beam.sdk.coders.KvCoder.encode(KvCoder.java:37)
	at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.encode(WindowedValue.java:591)
	at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.encode(WindowedValue.java:582)
	at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.encode(WindowedValue.java:542)
	at org.apache.beam.runners.flink.translation.types.CoderTypeSerializer.serialize(CoderTypeSerializer.java:111)
	at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.serialize(TupleSerializer.java:140)
	at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.serialize(TupleSerializer.java:37)
	at org.apache.flink.runtime.operators.sort.NormalizedKeySorter.write(NormalizedKeySorter.java:297)
	at org.apache.flink.runtime.operators.sort.SorterInputGateway.writeRecord(SorterInputGateway.java:77)
	at org.apache.flink.runtime.operators.sort.ReadingThread.go(ReadingThread.java:69)
	at org.apache.flink.runtime.operators.sort.ThreadBase.run(ThreadBase.java:73)
	at ### Coder materialization stack ###.(:0)
	at com.spotify.scio.coders.CoderMaterializer$.beamImpl(CoderMaterializer.scala:66)
	at com.spotify.scio.coders.CoderMaterializer$.beamImpl(CoderMaterializer.scala:67)
	at com.spotify.scio.coders.CoderMaterializer$.beamImpl(CoderMaterializer.scala:66)
	at com.spotify.scio.coders.CoderMaterializer$.beamImpl(CoderMaterializer.scala:67)
	at com.spotify.scio.coders.CoderMaterializer$.beam(CoderMaterializer.scala:49)
	at com.spotify.scio.coders.CoderMaterializer$.beam(CoderMaterializer.scala:35)
	at com.spotify.scio.values.SCollection.parDo(SCollection.scala:225)
	at com.spotify.scio.values.SCollection.parDo$(SCollection.scala:222)
	at com.spotify.scio.values.SCollectionImpl.parDo(SCollection.scala:1545)
	at com.spotify.scio.values.SCollection.map(SCollection.scala:692)
```

**Comment by RustedBones** [comment]
@regadas is this still happening ?
