### ISSUE TITLE
NPE on SCollection.count when coded with Coder.xmap

### ISSUE THREAD

**Issue by rich-j** [spotify/scio#3895]
Migrating to SCIO 0.10.x we get an NPE on `SCollection.count` when the data has been coded with `Coder.xmap`.

This bug replaces #3752 with a minimum reproducible test case using basic SCIO without a `datastore`.

```scala
package xx

import com.spotify.scio._
import com.spotify.scio.io.ClosedTap
import com.spotify.scio.values.SCollection
import com.spotify.scio.coders.Coder

object ScioNPE {
  def main(cmdlineArgs: Array[String]): Unit = {
    val (sc, args) = ContextAndArgs(cmdlineArgs)

    val data: SCollection[XP] = sc.parallelize(Seq(1))
      .map[XP](_ => new XP(2))

    val countTap: ClosedTap[Long] = data.count.materialize // <-- NPE on count
    val result = sc.run().waitUntilFinish()
    println(s"Count ${result.tap(countTap).value.sum}")
  }
}

case class XP(v: Int)

object XP {
  implicit def xpCoder: Coder[XP] =
    Coder.xmap(Coder[Int])(_ => new XP(1), _ => 0)
}

```

<details>
  <summary>Stacktrace</summary>
  
```
[error] (run-main-11) java.lang.NullPointerException: null value in entry: T=null
[error] java.lang.NullPointerException: null value in entry: T=null
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:100)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.RegularImmutableMap.fromEntries(RegularImmutableMap.java:74)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:464)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:437)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.reflect.TypeResolver$TypeMappingIntrospector.getTypeMappings(TypeResolver.java:385)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.reflect.TypeResolver.covariantly(TypeResolver.java:75)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.reflect.TypeToken.getCovariantTypeResolver(TypeToken.java:1181)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.reflect.TypeToken.resolveSupertype(TypeToken.java:273)
[error] 	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.reflect.TypeToken.getSupertype(TypeToken.java:398)
[error] 	at org.apache.beam.sdk.values.TypeDescriptor.getSupertype(TypeDescriptor.java:188)
[error] 	at org.apache.beam.sdk.util.CoderUtils.getCodedType(CoderUtils.java:176)
[error] 	at org.apache.beam.sdk.coders.CoderRegistry.verifyCompatible(CoderRegistry.java:510)
[error] 	at org.apache.beam.sdk.coders.CoderRegistry.getDefaultCoders(CoderRegistry.java:438)
[error] 	at org.apache.beam.sdk.coders.CoderRegistry.getDefaultCoders(CoderRegistry.java:371)
[error] 	at org.apache.beam.sdk.coders.CoderRegistry.getCoder(CoderRegistry.java:321)
[error] 	at org.apache.beam.sdk.transforms.CombineFnBase$AbstractGlobalCombineFn.getDefaultOutputCoder(CombineFnBase.java:129)
[error] 	at org.apache.beam.sdk.transforms.Combine$CombineFn.getDefaultOutputCoder(Combine.java:389)
[error] 	at org.apache.beam.sdk.transforms.Combine$GroupedValues.expand(Combine.java:2195)
[error] 	at org.apache.beam.sdk.transforms.Combine$GroupedValues.expand(Combine.java:2100)
[error] 	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
[error] 	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:482)
[error] 	at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:357)
[error] 	at org.apache.beam.sdk.transforms.Combine$PerKey.expand(Combine.java:1601)
[error] 	at org.apache.beam.sdk.transforms.Combine$PerKey.expand(Combine.java:1489)
[error] 	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
[error] 	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:482)
[error] 	at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:357)
[error] 	at org.apache.beam.sdk.transforms.Combine$Globally.expand(Combine.java:1187)
[error] 	at org.apache.beam.sdk.transforms.Combine$Globally.expand(Combine.java:1071)
[error] 	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
[error] 	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:499)
[error] 	at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:370)
[error] 	at com.spotify.scio.values.PCollectionWrapper.applyInternal(PCollectionWrapper.scala:42)
[error] 	at com.spotify.scio.values.PCollectionWrapper.applyInternal$(PCollectionWrapper.scala:38)
[error] 	at com.spotify.scio.values.SCollectionImpl.applyInternal(SCollection.scala:1582)
[error] 	at com.spotify.scio.values.SCollection.pApply(SCollection.scala:208)
[error] 	at com.spotify.scio.values.SCollection.pApply$(SCollection.scala:194)
[error] 	at com.spotify.scio.values.SCollectionImpl.pApply(SCollection.scala:1582)
[error] 	at com.spotify.scio.values.SCollection.pApply(SCollection.scala:214)
[error] 	at com.spotify.scio.values.SCollection.pApply$(SCollection.scala:211)
[error] 	at com.spotify.scio.values.SCollectionImpl.pApply(SCollection.scala:1582)
[error] 	at com.spotify.scio.values.SCollection.count(SCollection.scala:538)
[error] 	at com.spotify.scio.values.SCollection.count$(SCollection.scala:537)
[error] 	at com.spotify.scio.values.SCollectionImpl.count(SCollection.scala:1582)
[error] 	at xx.ScioNPE$.main(ScioNPE.scala:15)
[error] 	at xx.ScioNPE.main(ScioNPE.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

```
</details>

**Comment by jto** [comment]
I probably has nothing to do with `xmap`. I think `count` is just not setting the coder properly.

**Comment by rich-j** [comment]
@jto if you comment out `xpCoder` in the above example it will work. The above is a "minimum reproducible test case" that shows the failure. The above example uses an `Int` that doesn't require the explicit `xmap` - this is a simplification of our [original bug](https://github.com/spotify/scio/issues/3752) that does require the `xmap`.

Our current workaround is to map the coded data to anything before passing it to count.  In the above example, change the `countTap` definition to:

```dart
 val countTap: ClosedTap[Long] = data.map(_=>0).count.materialize // <-- With workaround it works
```

**Comment by jto** [comment]
The following example will run correctly:

```scala
object ScioNPE {
  def main(cmdlineArgs: Array[String]): Unit = {
    val (sc, args) = ContextAndArgs(cmdlineArgs)

    val data: SCollection[XP] = sc
      .parallelize(Seq(1))
      .map[XP](_ => new XP(2))

    val bcoder = CoderMaterializer.beam(sc, XP.xpCoder)
    data.internal.setCoder(bcoder)

    val countTap: ClosedTap[Long] = data.count.materialize // <-- NPE on count
    val result = sc.run().waitUntilFinish()
    println(s"Count ${result.tap(countTap).value.sum}")
  }
}

case class XP(v: Int)

object XP {
  implicit def xpCoder: Coder[XP] =
    Coder.xmap(Coder[Int])(_ => XP(1), _ => 0)
}
```

As I said this probably as nothing to do with `xmap` but rather is the coder not being set properly. Interestingly replacing:

```scala
data.internal.setCoder(bcoder)
```

by

```scala
data.setCoder(bcoder)
```

will cause the NPE to happen again. This is a regression bc. `WrappedBCoder` exists in the first place to workaround Beam buggy reflection usage in Coders. The issue was introduced by `SCollection.setCoder` changes in 65dfbf3 which for some reason now unwraps the `WrappedBCoder`. @nevillelyh what was to reason to do that ?
