### ISSUE TITLE
NoSuchMethodError: scio 0.11.1 + scio-bigquery 0.9.6

### ISSUE THREAD

**Issue by Hejwo** [spotify/scio#4094]
Hi,
i've got following error when running my pipiline:
```
Exception in thread "main" java.lang.NoSuchMethodError: com.spotify.scio.ScioContext.read(Lcom/spotify/scio/io/ScioIO;Lcom/spotify/scio/coders/Coder;)Lcom/spotify/scio/values/SCollection;
	at com.spotify.scio.bigquery.syntax.ScioContextOps$.typedBigQuery$extension(ScioContextSyntax.scala:139)
	at com.spotify.scio.bigquery.syntax.ScioContextOps$.typedBigQuery$extension(ScioContextSyntax.scala:123)
        ...
```
and following dependencies:
```
val scioVersion = "0.11.1"
val beamVersion = "2.33.0"

      "com.spotify" %% "scio-core" % scioVersion,
      "com.spotify" %% "scio-bigquery" % "0.9.6",
      "com.spotify" %% "scio-test" % scioVersion % Test,
      "org.apache.beam" % "beam-runners-direct-java" % beamVersion,
      "org.apache.beam" % "beam-runners-google-cloud-dataflow-java" % beamVersion,
      "org.apache.beam" % "beam-sdks-java-extensions-json-jackson" % beamVersion,
      "org.slf4j" % "slf4j-simple" % "1.7.32",
      "com.github.pureconfig" %% "pureconfig" % "0.13.0",
      "com.typesafe.scala-logging" %% "scala-logging" % "3.9.3"
```

Could you please help me?
Probablly it's problem with transitive dependencies but I can't find which ones.

**Comment by clairemcginty** [comment]
hi! take a look at our [v0.10.0 migration guide](https://spotify.github.io/scio/migrations/v0.10.0-Migration-Guide.html#google-cloud-platform-modules) - `scio-bigquery` dependency should be removed and replaced with ` "com.spotify" %% "scio-google-cloud-platform" % scioVersion`.

**Comment by Hejwo** [comment]
hi again! thanks for quick response.  
It helped - i'm competently new to scio and wasn't aware of merging all gcp tools into 1 dep.  
Closing this one.
