### ISSUE TITLE
Tests are failing on Apple M1 machine

### ISSUE THREAD

**Issue by shnapz** [spotify/scio#4515]
There are several types of test failures that reproduce only on Apple M1 machines (apparently).

1. Annoy4s failures: 
```
[info]   Cause: java.lang.NoClassDefFoundError: Could not initialize class annoy4s.Annoy$
[info]   at com.spotify.scio.extra.annoy.AnnoyWriter.<init>(AnnoyUri.scala:85)
[info]   at com.spotify.scio.extra.annoy.package$AnnoyPairSCollection$$anonfun$asAnnoy$extension$2$$anonfun$apply$2.apply(package.scala:188)
[info]   at com.spotify.scio.extra.annoy.package$AnnoyPairSCollection$$anonfun$asAnnoy$extension$2$$anonfun$apply$2.apply(package.scala:185)
[info]   at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:266)
```
```
[info]   Cause: java.lang.UnsatisfiedLinkError: dlopen(/Users/XXXXXX/Library/Caches/JNA/temp/jna7056718402105222277.tmp, 0x0009): tried: '/Users/XXXXXX/Library/Caches/JNA/temp/jna7056718402105222277.tmp' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
[info]   at com.sun.jna.Native.open(Native Method)
[info]   at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
[info]   at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
[info]   at com.sun.jna.Library$Handler.<init>(Library.java:192)
[info]   at com.sun.jna.Native.loadLibrary(Native.java:672)
[info]   at com.sun.jna.Native.loadLibrary(Native.java:656)
[info]   at annoy4s.Annoy$.<clinit>(Annoy.scala:100)
[info]   at com.spotify.scio.extra.annoy.AnnoyWriter.<init>(AnnoyUri.scala:85)
[info]   at com.spotify.scio.extra.annoy.package$AnnoyPairSCollection$$anonfun$asAnnoy$extension$2$$anonfun$apply$2.apply(package.scala:188)
[info]   at com.spotify.scio.extra.annoy.package$AnnoyPairSCollection$$anonfun$asAnnoy$extension$2$$anonfun$apply$2.apply(package.scala:185)
```
2. TensorFlow failures
```
[info]   Cause: java.lang.NoClassDefFoundError: Could not initialize class org.tensorflow.SavedModelBundle
[info]   at com.spotify.zoltar.tf.TensorFlowModel.create(TensorFlowModel.java:114)
[info]   at com.spotify.zoltar.tf.TensorFlowLoader.lambda$create$4(TensorFlowLoader.java:86)
[info]   at com.spotify.zoltar.ModelLoader.lambda$load$0(ModelLoader.java:176)
```

**Comment by shnapz** [comment]
Temporary solution for annoy4s problems:
- Clone [annoy4s/annoy4s](https://github.com/annoy4s/annoy4s) locally
- Repeat the change from [this PR](https://github.com/annoy4s/annoy4s/pull/18)
- Follow "To compile the native library and install annoy4s on local machine" at its README page

**Comment by RustedBones** [comment]
This should have been resolved bu updating the jna lib in the local deps. @shnapz feel free to reopen if this is not the case (do not have an M1 to double check that)
