### ISSUE TITLE
no native library is found for os.name=Mac and os.arch=x86_64

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#47]
```
scio> sc.textFile("README.md")
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=x86_64
  at org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:331)
  at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:171)
  at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:152)
  at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
  at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:97)
  at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:89)
  at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:79)
  at com.google.cloud.dataflow.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:49)
  at com.google.cloud.dataflow.sdk.util.SerializableUtils.ensureSerializable(SerializableUtils.java:84)
  at com.google.cloud.dataflow.sdk.io.Read$Bounded.<init>(Read.java:107)
  at com.google.cloud.dataflow.sdk.io.Read$Bounded.<init>(Read.java:102)
  at com.google.cloud.dataflow.sdk.io.Read.from(Read.java:61)
  at com.google.cloud.dataflow.sdk.io.TextIO$Read$Bound.apply(TextIO.java:318)
  at com.google.cloud.dataflow.sdk.io.TextIO$Read$Bound.apply(TextIO.java:203)
  at com.google.cloud.dataflow.sdk.runners.PipelineRunner.apply(PipelineRunner.java:74)
  at com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner.apply(DirectPipelineRunner.java:247)
  at com.google.cloud.dataflow.sdk.Pipeline.applyInternal(Pipeline.java:367)
  at com.google.cloud.dataflow.sdk.Pipeline.applyTransform(Pipeline.java:290)
  at com.google.cloud.dataflow.sdk.values.PBegin.apply(PBegin.java:58)
  at com.google.cloud.dataflow.sdk.Pipeline.apply(Pipeline.java:171)
  at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:290)
  at com.spotify.scio.ScioContext$$anonfun$textFile$1.apply(ScioContext.scala:425)
  at com.spotify.scio.ScioContext$$anonfun$textFile$1.apply(ScioContext.scala:422)
  at com.spotify.scio.ScioContext.pipelineOp(ScioContext.scala:248)
  at com.spotify.scio.ScioContext.textFile(ScioContext.scala:421)
  ... 32 elided
```
seems to be coming from recent change (37dec8f) in dataflow sdk.

Seems like an issue in xerial/snappy-java

**Comment by ravwojdyla** [comment]
It actually could combination of be our rename strategy for `.jnilib` files and [this hack](https://github.com/xerial/snappy-java/blob/develop/src/main/java/org/xerial/snappy/SnappyLoader.java#L319) in snappy-java.

**Comment by nevillelyh** [comment]
Hehe I found that on the plane, didn't have internet to push commit :)
