### ISSUE TITLE
BaseAsyncLookupDoFn Try does not always have serializable fields

### ISSUE THREAD

**Issue by snallapa** [spotify/scio#4749]
https://github.com/spotify/scio/blob/f76330e5ff0b6e0565ea0c55e93b659106fdaaf1/scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncLookupDoFn.java#L296 this field does not have to be serializable. We do bigtable lookups and run into this now:

```
generic::unknown: org.apache.beam.sdk.util.UserCodeException: java.lang.IllegalArgumentException: Unable to encode element 'com.spotify.scio.transforms.BaseAsyncLookupDoFn$Try@6665b952' with coder 'SerializableCoder(com.spotify.scio.transforms.BaseAsyncLookupDoFn$Try)'.
	at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:39)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.outputTo(FnApiDoFnRunner.java:1794)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.access$3000(FnApiDoFnRunner.java:145)
	at org.apache.beam.fn.harness.FnApiDoFnRunner$FinishBundleArgumentProvider$Context.output(FnApiDoFnRunner.java:2131)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.lambda$finishBundle$10(BaseAsyncLookupDoFn.java:244)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.flush(BaseAsyncLookupDoFn.java:258)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.finishBundle(BaseAsyncLookupDoFn.java:244)
	at com.spotify.oasis.transforms.PatronusReadDoFn$DoFnInvoker.invokeFinishBundle(Unknown Source)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.finishBundle(FnApiDoFnRunner.java:1773)
	at org.apache.beam.fn.harness.data.PTransformFunctionRegistry.lambda$register$0(PTransformFunctionRegistry.java:128)
	at org.apache.beam.fn.harness.control.ProcessBundleHandler.processBundle(ProcessBundleHandler.java:551)
	at org.apache.beam.fn.harness.control.BeamFnControlClient.delegateOnInstructionRequestType(BeamFnControlClient.java:151)
	at org.apache.beam.fn.harness.control.BeamFnControlClient$InboundObserver.lambda$onNext$0(BeamFnControlClient.java:116)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Unable to encode element 'com.spotify.scio.transforms.BaseAsyncLookupDoFn$Try@6665b952' with coder 'SerializableCoder(com.spotify.scio.transforms.BaseAsyncLookupDoFn$Try)'.
	at org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:300)
	at org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
	at org.apache.beam.sdk.coders.KvCoder.registerByteSizeObserver(KvCoder.java:130)
	at org.apache.beam.sdk.coders.KvCoder.registerByteSizeObserver(KvCoder.java:37)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$SampleByteSizeDistribution.tryUpdate(PCollectionConsumerRegistry.java:445)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:295)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:241)
Caused by: java.io.NotSerializableException: io.grpc.Status
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
	at java.base/java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:438)
	at java.base/java.lang.Throwable.writeObject(Throwable.java:996)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1016)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1487)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:345)
	at org.apache.beam.sdk.coders.SerializableCoder.encode(SerializableCoder.java:192)
	at org.apache.beam.sdk.coders.SerializableCoder.encode(SerializableCoder.java:57)
	at org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:297)
	at org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
	at org.apache.beam.sdk.coders.KvCoder.registerByteSizeObserver(KvCoder.java:130)
	at org.apache.beam.sdk.coders.KvCoder.registerByteSizeObserver(KvCoder.java:37)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$SampleByteSizeDistribution.tryUpdate(PCollectionConsumerRegistry.java:445)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:295)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:241)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.outputTo(FnApiDoFnRunner.java:1791)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.access$3000(FnApiDoFnRunner.java:145)
	at org.apache.beam.fn.harness.FnApiDoFnRunner$FinishBundleArgumentProvider$Context.output(FnApiDoFnRunner.java:2131)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.lambda$finishBundle$10(BaseAsyncLookupDoFn.java:244)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.flush(BaseAsyncLookupDoFn.java:258)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.finishBundle(BaseAsyncLookupDoFn.java:244)
	at com.spotify.oasis.transforms.PatronusReadDoFn$DoFnInvoker.invokeFinishBundle(Unknown Source)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.finishBundle(FnApiDoFnRunner.java:1773)
	at org.apache.beam.fn.harness.data.PTransformFunctionRegistry.lambda$register$0(PTransformFunctionRegistry.java:128)
	at org.apache.beam.fn.harness.control.ProcessBundleHandler.processBundle(ProcessBundleHandler.java:551)
	at org.apache.beam.fn.harness.control.BeamFnControlClient.delegateOnInstructionRequestType(BeamFnControlClient.java:151)
	at org.apache.beam.fn.harness.control.BeamFnControlClient$InboundObserver.lambda$onNext$0(BeamFnControlClient.java:116)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829) 
```

**Comment by snallapa** [comment]
I was able to use kryo coder but then ran into this:
```
 org.apache.beam.sdk.util.UserCodeException: java.lang.IllegalArgumentException: Unable to encode element 'Failure(com.google.cloud.bigtable.grpc.scanner.BigtableRetriesExhaustedException: Exhausted retries after 2 failures.)' with coder 'DisjunctionCoder[scala.util.Try](id -> BooleanCoder, false -> LazyCoder(scala.util.Failure,CoderOptions(false,KryoOptions(65536,67108864,true,false))), true -> LazyCoder(scala.util.Success,CoderOptions(false,KryoOptions(65536,67108864,true,false))))'.
	at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:39)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.outputTo(FnApiDoFnRunner.java:1794)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.access$3000(FnApiDoFnRunner.java:145)
	at org.apache.beam.fn.harness.FnApiDoFnRunner$FinishBundleArgumentProvider$Context.output(FnApiDoFnRunner.java:2131)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.lambda$finishBundle$10(BaseAsyncLookupDoFn.java:244)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.flush(BaseAsyncLookupDoFn.java:258)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.finishBundle(BaseAsyncLookupDoFn.java:244)
	at com.spotify.oasis.transforms.UTPReadDoFn$DoFnInvoker.invokeFinishBundle(Unknown Source)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.finishBundle(FnApiDoFnRunner.java:1773)
	at org.apache.beam.fn.harness.data.PTransformFunctionRegistry.lambda$register$0(PTransformFunctionRegistry.java:128)
	at org.apache.beam.fn.harness.control.ProcessBundleHandler.processBundle(ProcessBundleHandler.java:551)
	at org.apache.beam.fn.harness.control.BeamFnControlClient.delegateOnInstructionRequestType(BeamFnControlClient.java:151)
	at org.apache.beam.fn.harness.control.BeamFnControlClient$InboundObserver.lambda$onNext$0(BeamFnControlClient.java:116)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Unable to encode element 'Failure(com.google.cloud.bigtable.grpc.scanner.BigtableRetriesExhaustedException: Exhausted retries after 2 failures.)' with coder 'DisjunctionCoder[scala.util.Try](id -> BooleanCoder, false -> LazyCoder(scala.util.Failure,CoderOptions(false,KryoOptions(65536,67108864,true,false))), true -> LazyCoder(scala.util.Success,CoderOptions(false,KryoOptions(65536,67108864,true,false))))'.
	at org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:300)
	at org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
	at com.spotify.scio.coders.WrappedBCoder.registerByteSizeObserver(Coder.scala:292)
	at com.spotify.scio.coders.CoderGrammar$$anon$1.registerByteSizeObserver(Coder.scala:508)
	at com.spotify.scio.coders.WrappedBCoder.registerByteSizeObserver(Coder.scala:292)
	at org.apache.beam.sdk.coders.KvCoder.registerByteSizeObserver(KvCoder.java:130)
	at org.apache.beam.sdk.coders.KvCoder.registerByteSizeObserver(KvCoder.java:37)
	at com.spotify.scio.coders.WrappedBCoder.registerByteSizeObserver(Coder.scala:292)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$SampleByteSizeDistribution.tryUpdate(PCollectionConsumerRegistry.java:445)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:295)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:241)
Caused by: com.esotericsoftware.kryo.KryoException: Error during Java serialization.
	at Due to Exception while trying to `encode` an instance of scala.util.Failure:  Can't encode field exception value com.google.cloud.bigtable.grpc.scanner.BigtableRetriesExhaustedException: Exhausted retries after 2 failures..(:0)
	at com.esotericsoftware.kryo.serializers.JavaSerializer.write(JavaSerializer.java:54)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
	at com.spotify.scio.coders.KryoAtomicCoder$$anonfun$encode$1.apply(KryoAtomicCoder.scala:153)
	at com.spotify.scio.coders.KryoAtomicCoder$$anonfun$encode$1.apply(KryoAtomicCoder.scala:143)
	at com.spotify.scio.coders.KryoAtomicCoder$.withKryoState(KryoAtomicCoder.scala:288)
	at com.spotify.scio.coders.KryoAtomicCoder.encode(KryoAtomicCoder.scala:143)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply$mcV$sp(Coder.scala:271)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply(Coder.scala:271)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply(Coder.scala:271)
	at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:261)
	at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:271)
	at com.spotify.scio.coders.RecordCoder$$anonfun$encode$3.apply$mcV$sp(Coder.scala:332)
	at com.spotify.scio.coders.RecordCoder$$anonfun$encode$3.apply(Coder.scala:332)
	at com.spotify.scio.coders.RecordCoder$$anonfun$encode$3.apply(Coder.scala:332)
	at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:316)
	at com.spotify.scio.coders.RecordCoder.encode(Coder.scala:332)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply$mcV$sp(Coder.scala:271)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply(Coder.scala:271)
	at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply(Coder.scala:271)
	at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:261)
	at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:271)
	at com.spotify.scio.coders.LazyCoder.encode(Coder.scala:187)
	at com.spotify.scio.coders.DisjunctionCoder.encode(Coder.scala:128)
	at org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:297)
	at org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
	at com.spotify.scio.coders.WrappedBCoder.registerByteSizeObserver(Coder.scala:292)
	at com.spotify.scio.coders.CoderGrammar$$anon$1.registerByteSizeObserver(Coder.scala:508)
	at com.spotify.scio.coders.WrappedBCoder.registerByteSizeObserver(Coder.scala:292)
	at org.apache.beam.sdk.coders.KvCoder.registerByteSizeObserver(KvCoder.java:130)
	at org.apache.beam.sdk.coders.KvCoder.registerByteSizeObserver(KvCoder.java:37)
	at com.spotify.scio.coders.WrappedBCoder.registerByteSizeObserver(Coder.scala:292)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$SampleByteSizeDistribution.tryUpdate(PCollectionConsumerRegistry.java:445)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:295)
	at org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$MetricTrackingFnDataReceiver.accept(PCollectionConsumerRegistry.java:241)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.outputTo(FnApiDoFnRunner.java:1791)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.access$3000(FnApiDoFnRunner.java:145)
	at org.apache.beam.fn.harness.FnApiDoFnRunner$FinishBundleArgumentProvider$Context.output(FnApiDoFnRunner.java:2131)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.lambda$finishBundle$10(BaseAsyncLookupDoFn.java:244)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.flush(BaseAsyncLookupDoFn.java:258)
	at com.spotify.scio.transforms.BaseAsyncLookupDoFn.finishBundle(BaseAsyncLookupDoFn.java:244)
	at com.spotify.oasis.transforms.UTPReadDoFn$DoFnInvoker.invokeFinishBundle(Unknown Source)
	at org.apache.beam.fn.harness.FnApiDoFnRunner.finishBundle(FnApiDoFnRunner.java:1773)
	at org.apache.beam.fn.harness.data.PTransformFunctionRegistry.lambda$register$0(PTransformFunctionRegistry.java:128)
	at org.apache.beam.fn.harness.control.ProcessBundleHandler.processBundle(ProcessBundleHandler.java:551)
	at org.apache.beam.fn.harness.control.BeamFnControlClient.delegateOnInstructionRequestType(BeamFnControlClient.java:151)
	at org.apache.beam.fn.harness.control.BeamFnControlClient$InboundObserver.lambda$onNext$0(BeamFnControlClient.java:116)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829) 
```

**Comment by RustedBones** [comment]
This is a normal exception:

By default, the coder for `Try[T]` will encode failures with the generic kryo coder. When there is no kryo registration for the exception, it will use the default java serialization.
The problem is that the `cause` of your `BigtableRetriesExhaustedException` is a `StatusRuntimeException` which is not serializable.

To make this work, you should register a custom serializer for `BigtableRetriesExhaustedException` as explained in the [doc](https://spotify.github.io/scio//FAQ.html#how-do-i-use-custom-kryo-serializers-).

In our case, we want to force using the `StatusRuntimeException` for the cause. (Looking at the usage, the case is always defined with a `StatusRuntimeException`)

You can add the following to your project to fix the issue

```scala
class BigtableRetriesExhaustedExceptionSerializer
    extends KSerializer[BigtableRetriesExhaustedException] {

  override def write(kryo: Kryo, output: Output, e: BigtableRetriesExhaustedException): Unit = {
    kryo.writeObject(output, e.getMessage)
    kryo.writeObject(output, e.getCause)
  }

  override def read(
    kryo: Kryo,
    input: Input,
    `type`: Class[BigtableRetriesExhaustedException]
  ): BigtableRetriesExhaustedException = {
    val message = kryo.readObject(input, classOf[String])
    val cause = kryo.readObject(input, classOf[StatusRuntimeException])
    new BigtableRetriesExhaustedException(message, cause)
  }
}

@KryoRegistrar
class MyKryoRegistrar extends IKryoRegistrar {
  override def apply(k: Kryo): Unit =
    k.forClass[BigtableRetriesExhaustedException](new BigtableRetriesExhaustedExceptionSerializer())
}
```

**Comment by RustedBones** [comment]
Maybe as we support the `StatusRuntimeException` we should also add the `BigtableRetriesExhaustedException` support by default in `scio-google-cloud-platform` as this can be a generic exception thrown by the `BigtableDataGrpcClient`

**Comment by clairemcginty** [comment]
Adding Serializers for common/IO-specific GRPC exceptions sounds good to me! I guess there's a chance that even with a registered Serializer for `BigtableRetriesExhaustedException`, Kryo might throw an exception during encoding if its inner [Throwable](https://github.com/googleapis/java-bigtable-hbase/blob/v1.26.3/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/scanner/BigtableRetriesExhaustedException.java#L29) isn't serializable.  Although in the only [usage](https://github.com/googleapis/java-bigtable-hbase/blob/v1.26.3/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/AbstractRetryingOperation.java#L242) I could find, it's invoked with a `StatusRuntimeException`, which should be fine :)
