### ISSUE TITLE
 com.spotify.scio.bigquery.client.BigQuery.defaultInstance().run does not respect destinationTable=null setting for UML 

### ISSUE THREAD

**Issue by fallonchen** [spotify/scio#5136]
Using the default BigQuery client instance to run a triple-quoted UML statement with newlines will result in an invalidQuery error: 

```Cannot set destination table in jobs with DML statements```.

One simple example for reproduction:

Set up a table in your project, like: 
```
CREATE OR REPLACE TABLE <your dataset>.trips AS (
  SELECT
    bike_id,
    start_time,
    duration_minutes
  FROM
    bigquery-public-data.austin_bikeshare.bikeshare_trips
    LIMIT 10
);
```

Then in `sbt console`
```
scala> import com.spotify.scio.bigquery.client.BigQuery
scala> val q = """UPDATE `<your project>.<your dataset>.trips` 
     | SET duration_minutes=0
     | WHERE duration_minutes > 10"""
scala> BigQuery.defaultInstance().query.run(q, destinationTable = null, writeDisposition = null, createDisposition = null)
```
Results in:

```
Jan 05, 2024 4:51:39 PM com.spotify.scio.bigquery.client.QueryOps com$spotify$scio$bigquery$client$QueryOps$$run
INFO: Executing standard SQL query (INTERACTIVE): `UPDATE `<your project>.<your dataset>.trips` 
SET duration_minutes=0
WHERE duration_minutes > 10`
....
( message above repeats 6x) 
...

java.lang.RuntimeException: com.spotify.scio.bigquery.client.QueryJob id:shopify-merch-3a259850-60ba-402d-9583-b206ddc4b0a1 failed with error: {"message":"Cannot set destination table in jobs with DML statements","reason":"invalidQuery"}
  at com.spotify.scio.bigquery.client.JobOps$$anonfun$3.apply(JobOps.scala:101)
  at com.spotify.scio.bigquery.client.JobOps$$anonfun$3.apply(JobOps.scala:91)
  at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:304)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:303)
  at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:297)
  at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
  at scala.collection.TraversableLike.filter(TraversableLike.scala:395)
  at scala.collection.TraversableLike.filter$(TraversableLike.scala:395)
  at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
  at com.spotify.scio.bigquery.client.JobOps.waitForJobs(JobOps.scala:91)
  at com.spotify.scio.bigquery.client.QueryOps$$anonfun$9.apply(QueryOps.scala:226)
  at com.spotify.scio.bigquery.client.QueryOps$$anonfun$9.apply(QueryOps.scala:225)
  at scala.util.Success.$anonfun$map$1(Try.scala:255)
  at scala.util.Success.map(Try.scala:213)
  at com.spotify.scio.bigquery.client.QueryOps.run(QueryOps.scala:225)
  ... 55 elided
```

**Oddly enough, this can be worked around by making the statement inline:** 
``` val q = """UPDATE `<your project>.<your dataset>.trips` SET duration_minutes = 0 WHERE duration_minutes > 0"""```
will run successfully, but it's unclear why this works - I think it might have to do with the cache?

**Comment by RustedBones** [comment]
Thanks a lot for the complete bug report. There is indeed a DML statement detection issue in case of multi-line query.
You could use `stripMargin.replace('\n', ' ')` as a workaround until fix gets released
