### ISSUE TITLE
java.lang.RuntimeException Table Already Exists

### ISSUE THREAD

**Issue by OktayGardener** [spotify/scio#556]
After trying to run a job that has multiple `@BigQueryType.fromQuery()` and runs SQL queries, that has already been run in the past (or most recently), scio complains that the tables already exist. This is a real productivity (and money) burner, and the only solution I have found so far is to remove the files in the folder `.bigquery` and run the queries again.

I get the following error message:

```
[error] (run-main-0) java.lang.RuntimeException: Query job failed: id: my-project-1004fec1-a1e9-4abd-ad93-818ad01bc518, error: {"message":"Already Exists: Table my-project:scio_bigquery_staging_eu.scio_query_20170418101904_121422454","reason":"duplicate"}
java.lang.RuntimeException: Query job failed: id: my-project-1004fec1-a1e9-4abd-ad93-818ad01bc518, error: {"message":"Already Exists: Table my-project:scio_bigquery_staging_eu.scio_query_20170418101904_121422454","reason":"duplicate"}
	at com.oktay.scio.bigquery.BigQueryClient$$anonfun$4.apply(BigQueryClient.scala:278)
	at com.oktay.scio.bigquery.BigQueryClient$$anonfun$4.apply(BigQueryClient.scala:273)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at com.oktay.scio.bigquery.BigQueryClient.waitForJobs(BigQueryClient.scala:273)
	at com.oktay.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:335)
	at com.oktay.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:333)
	at com.oktay.scio.ScioContext.requireNotClosed(ScioContext.scala:356)
	at com.oktay.scio.ScioContext.close(ScioContext.scala:333)
	at com.oktay.play.TSVFiles$.main(TSVFiles.scala:60)
	at com.oktay.play.TSVFiles.main(TSVFiles.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last thesis/compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last thesis/compile:runMain for the full output.
[error] (thesis/compile:runMain) Nonzero exit code: 1
[error] Total time: 20 s, completed Apr 18, 2017 1:37:47 PM
```

**Comment by nevillelyh** [comment]
This happens when running pending jobs. So there might be a race condition where multiple pending jobs have the same destination table?
https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala#L273

**Comment by nevillelyh** [comment]
@OktayGardener do you have a consistent way to re-produce this? Does this issue re-appear even after you delete `.bigquery` cache directory?

**Comment by OktayGardener** [comment]
@nevillelyh Run a job with certain parameters that queries a few BigQuery tables, wait until it's completed and you are able to view the job at BigQuery and Cloud Console. Try to run the exact same command again, and you will most likely end up with this error. The error does not prevail after clearing the .bigquery folder, but time is lost since there exist no reference to the previously queried tables, and you would have to wait until the queries are run once again.

So for example, I run:

`run-main com.oktay.play.TSVFiles --project=my-project --runner=DataflowRunner --zone=europe-west1-d --tempLocation=gs://my-project/tmp/oktay/staging2 --maxNumWorkers=50 --workerMachineType=n1-standard-8 --workerCacheMb=2000 --date=2017-04-09  --output=gs://my-project/tmp/oktay/2017-04-09`

**Comment by nevillelyh** [comment]
Closing this and tracking it in #710.
