### ISSUE TITLE
NoSuchMethodError from jline in scio-repl

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#577]
```
Exception in thread "main" java.lang.NoSuchMethodError: jline.console.completer.CandidateListCompletionHandler.setPrintSpaceAfterFullCompletion(Z)V
	at scala.tools.nsc.interpreter.jline.JLineConsoleReader.initCompletion(JLineReader.scala:139)
	at scala.tools.nsc.interpreter.jline.InteractiveReader.postInit(JLineReader.scala:54)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$25.apply(ILoop.scala:899)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$25.apply(ILoop.scala:897)
	at scala.tools.nsc.interpreter.SplashReader.postInit(InteractiveReader.scala:130)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$scala$tools$nsc$interpreter$ILoop$$anonfun$$loopPostInit$1$1.apply$mcV$sp(ILoop.scala:926)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$scala$tools$nsc$interpreter$ILoop$$anonfun$$loopPostInit$1$1.apply(ILoop.scala:908)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$scala$tools$nsc$interpreter$ILoop$$anonfun$$loopPostInit$1$1.apply(ILoop.scala:908)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$mumly$1.apply(ILoop.scala:189)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:221)
	at scala.tools.nsc.interpreter.ILoop.mumly(ILoop.scala:186)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$startup$1$1.apply(ILoop.scala:979)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:990)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
	at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:891)
	at com.spotify.scio.repl.BaseScioShell$class.process(ScioShell.scala:97)
	at com.spotify.scio.repl.ScioShell$.process(ScioShell.scala:111)
	at com.spotify.scio.repl.BaseScioShell$class.main(ScioShell.scala:104)
	at com.spotify.scio.repl.ScioShell$.main(ScioShell.scala:111)
	at com.spotify.scio.repl.ScioShell.main(ScioShell.scala)

Exception in thread "Thread-2" java.lang.InterruptedException
	at java.util.concurrent.SynchronousQueue.put(SynchronousQueue.java:879)
	at scala.tools.nsc.interpreter.SplashLoop.run(InteractiveReader.scala:77)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nevillelyh** [comment]
Turns out jline version isn't in sync with scala version. It's just a coincidence that scala 2.10.6 depends on jline 2.10.6.

**Comment by rk186009** [comment]
Did you manage to fix this? If yes, can you please share the fix?
