### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

### ISSUE THREAD

**Issue by chandu0101** [spotify/scio#604]
I am trying to run WordCount Example using `DataflowRunner` 

```scala
May 10, 2017 12:24:40 AM com.google.api.client.http.HttpRequest execute
WARNING: exception thrown while executing request
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1281)
        at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:90)
        at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1248)
        at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1246)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessController.doPrivileged(AccessController.java:713)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1245)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545)
        at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:562)
        at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:419)
        at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:427)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel$UploadOperation.call(AbstractGoogleAsyncWriteChannel.java:357)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
```

Running built in template(wordcount) from google console is working fine though.

**Comment by ravwojdyla** [comment]
Hi @chandu0101 This does not seems like a fatal error, more like a warning. Did the job run?

**Comment by chandu0101** [comment]
thanks for quick reply , i thought its something to do with my jdk , terminated process  and updated JDK , still same error this time i just allowed it to run , got NPE 

```scala

Dataflow SDK version: 0.6.0
[error] (run-main-0) java.lang.NullPointerException
java.lang.NullPointerException
        at org.apache.beam.runners.dataflow.DataflowPipelineJob.fromMetricUpdates(DataflowPipelineJob.java:471)
        at org.apache.beam.runners.dataflow.DataflowPipelineJob.getAggregatorValues(DataflowPipelineJob.java:443)
        at com.spotify.scio.ScioResult$$anonfun$getAggregatorValues$2.apply(ScioResult.scala:177)
        at com.spotify.scio.ScioResult$$anonfun$getAggregatorValues$2.apply(ScioResult.scala:177)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at com.spotify.scio.ScioResult.getAggregatorValues(ScioResult.scala:177)
        at com.spotify.scio.ScioResult.accumulatorTotalValue(ScioResult.scala:101)
        at org.backtoseed.prices.etl.Tomato$.main(Tomato.scala:64)
        at org.backtoseed.prices.etl.Tomato.main(Tomato.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
```

**Comment by ravwojdyla** [comment]
This should have a more meaningful error/message (reported in #606 ), but you can't retrieve accumulators from template staging code, cause at that time there is not job running. So either:
 * run the job the way it is (without `templateLocation`)
 * stage template (keep `templateLocation`) but remove accumulator retrieval code (example: `accumulatorTotalValue`)

**Comment by chandu0101** [comment]
cool ok 👍  , now i am progressed to different error 

```scala

Dataflow SDK version: 0.6.0
[error] (run-main-0) java.lang.RuntimeException: Failed to create a workflow job: (4cc45aea49323736): The workflow was automatically rejected by the service because it may trigger an identified bug in the SDK.
[error] Bug details: Job requests a worker pool in an unrecognized zone. For a list of valid zones, see: https://cloud.google.com/compute/docs/regions-zones/regions-zones.
[error] Contact dataflow-feedback@google.com for further help. Please use this identifier in your communication: WORKER_POOL_ZONE_UNKNOWN.
java.lang.RuntimeException: Failed to create a workflow job: (4cc45aea49323736): The workflow was automatically rejected by the service because it may trigger an identified bug in the SDK.
Bug details: Job requests a worker pool in an unrecognized zone. For a list of valid zones, see: https://cloud.google.com/compute/docs/regions-zones/regions-zones.
Contact dataflow-feedback@google.com for further help. Please use this identifier in your communication: WORKER_POOL_ZONE_UNKNOWN.
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:616)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:151)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:210)
        at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:344)
        at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:336)
        at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:363)
        at com.spotify.scio.ScioContext.close(ScioContext.scala:336)
        at org.backtoseed.prices.etl.Tomato$.main(Tomato.scala:62)
        at org.backtoseed.prices.etl.Tomato.main(Tomato.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "(4cc45aea49323736): The workflow was automatically rejected by the service because it may trigger an identified bug in the SDK.\nBug details: Job requests a worker pool in an unrecognized zone. For a list of valid zones, see: https://cloud.google.com/compute/docs/regions-zones/regions-zones.\nContact dataflow-feedback@google.com for further help. Please use this identifier in your communication: WORKER_POOL_ZONE_UNKNOWN.",
    "reason" : "badRequest"
  } ],
  "message" : "(4cc45aea49323736): The workflow was automatically rejected by the service because it may trigger an identified bug in the SDK.\nBug details: Job requests a worker pool in an unrecognized zone. For a list of valid zones, see: https://cloud.google.com/compute/docs/regions-zones/regions-zones.\nContact dataflow-feedback@google.com for further help. Please use this identifier in your communication: WORKER_POOL_ZONE_UNKNOWN.",
  "status" : "INVALID_ARGUMENT"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at org.apache.beam.runners.dataflow.DataflowClient.createJob(DataflowClient.java:61)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:603)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:151)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:210)
        at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:344)
        at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:336)
        at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:363)
        at com.spotify.scio.ScioContext.close(ScioContext.scala:336)
        at org.backtoseed.prices.etl.Tomato$.main(Tomato.scala:62)
        at org.backtoseed.prices.etl.Tomato.main(Tomato.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by ravwojdyla** [comment]
`asia-southeast1` is a region not a `zone`, please follow the error message and read the [doc](https://cloud.google.com/compute/docs/regions-zones/regions-zones). You can for example use `--zone=asia-southeast1-a`.

**Comment by chandu0101** [comment]
ok now i am filled with joy of running a hello world on new platform in no sleep frustration mode, back to sleep!. @ravwojdyla  thanks alot for your help.
