### ISSUE TITLE
Unable to execute pipeline with windowing /sharding transform

### ISSUE THREAD

**Issue by sfines** [spotify/scio#638]
When running in a bounded window using SCIO 0.3.2-SNAPSHOT the following exception is thrown 
` Unable to deserialize Coder: WindowedValue$FullWindowedValueCoder(KvCoder(BigQueryIO$ShardedKeyCoder(StringUtf8Coder),BigQueryIO$TableRowInfoCoder),GlobalWindow$Coder)`

[This Commit](https://github.com/apache/beam/commit/cbcec7c0520f151f348604621cc251b6ed9b1616) in the beam repository fixes the beam issue which causes this error.

**Comment by sfines** [comment]
Here's a sample that reproduces it with the snapshot. 
[ReproduceWindowingBug.scala.zip](https://github.com/spotify/scio/files/1023724/ReproduceWindowingBug.scala.zip)

The stack trace given on execution is: 

`Exception in thread "main" java.lang.RuntimeException: Unable to deserialize Coder: WindowedValue$FullWindowedValueCoder(KvCoder(BigQueryIO$ShardedKeyCoder(StringUtf8Coder),BigQueryIO$TableRowInfoCoder),IntervalWindow$IntervalWindowCoder). Check that a suitable constructor is defined.  See Coder for details.
	at org.apache.beam.sdk.util.SerializableUtils.ensureSerializable(SerializableUtils.java:115)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$StepTranslator.addOutput(DataflowPipelineTranslator.java:657)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$StepTranslator.addOutput(DataflowPipelineTranslator.java:604)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$7.translateSingleHelper(DataflowPipelineTranslator.java:865)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$7.translate(DataflowPipelineTranslator.java:856)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$7.translate(DataflowPipelineTranslator.java:853)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.visitPrimitiveTransform(DataflowPipelineTranslator.java:415)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:486)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:481)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:481)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:481)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.access$400(TransformHierarchy.java:231)
	at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:206)
	at org.apache.beam.sdk.Pipeline.traverseTopologically(Pipeline.java:321)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.translate(DataflowPipelineTranslator.java:365)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator.translate(DataflowPipelineTranslator.java:154)
	at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:514)
	at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:151)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:210)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:344)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:336)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:363)
	at com.spotify.scio.ScioContext.close(ScioContext.scala:336)
	at com.dexcom.stream.processing.ReproduceWindowingBug$.main(ReproduceWindowingBug.scala:49)
	at com.dexcom.stream.processing.ReproduceWindowingBug.main(ReproduceWindowingBug.scala)
Caused by: java.lang.RuntimeException: Unable to deserialize class interface org.apache.beam.sdk.coders.Coder
	at org.apache.beam.sdk.util.Serializer.deserialize(Serializer.java:102)
	at org.apache.beam.sdk.util.SerializableUtils.ensureSerializable(SerializableUtils.java:112)
	... 24 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO$ShardedKeyCoder, problem: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder["component_encodings"]->java.util.ArrayList[0]->org.apache.beam.sdk.coders.KvCoder["component_encodings"]->java.util.ArrayList[0])
`

**Comment by ravwojdyla** [comment]
This seems hard to backport, in this case probably makes sense to just wait for scio 0.4.x release based on beam v2. Closing for now.
