### ISSUE TITLE
IllegalAccessError on BigQueryTableRowIterator

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#644]
In `scio-repl version 0.3.1`:

```
scio> bq.getQueryRows(CC.query)
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Cache hit for query: `<query>`
[main] INFO com.spotify.scio.bigquery.BigQueryClient - Existing destination table: scio-playground:scio_bigquery_staging_eu.scio_query_20170531155618_1825239285
java.lang.IllegalAccessError: org/apache/beam/sdk/io/gcp/bigquery/BigQueryTableRowIterator
  at com.spotify.scio.bigquery.BigQueryClient$$anon$1.<init>(BigQueryClient.scala:184)
  at com.spotify.scio.bigquery.BigQueryClient.getTableRows(BigQueryClient.scala:183)
  at com.spotify.scio.bigquery.BigQueryClient.getQueryRows(BigQueryClient.scala:175)
  ... 32 elided
```

**Comment by andrewsmartin** [comment]
Copying my comment from #650...

This is probably a class loading issue. `BigQueryTableRowIterator` is package-private in the Beam SDK, and our patch made it public. At runtime it seems there can be a problem with classloading where it uses the Beam version instead. We can solve this by renaming the patched class.
