### ISSUE TITLE
Unable to deserialize FN //serialVersionUIDs

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#65]
Got this error a couple of times in the row, setting `serialVersionUID`s helps.

```
java.lang.IllegalArgumentException: unable to deserialize serialized fn info at com.google.cloud.dataflow.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:76) at com.google.cloud.dataflow.sdk.runners.worker.UserParDoFnFactory.create(UserParDoFnFactory.java:61) at com.google.cloud.dataflow.sdk.runners.worker.DefaultParDoFnFactory.create(DefaultParDoFnFactory.java:70) at com.google.cloud.dataflow.sdk.runners.worker.MapTaskExecutorFactory.createParDoOperation(MapTaskExecutorFactory.java:219) at com.google.cloud.dataflow.sdk.runners.worker.MapTaskExecutorFactory.createOperation(MapTaskExecutorFactory.java:133) at com.google.cloud.dataflow.sdk.runners.worker.MapTaskExecutorFactory.create(MapTaskExecutorFactory.java:85) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.doWork(DataflowWorker.java:176) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.getAndPerformWork(DataflowWorker.java:149) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.doWork(DataflowWorkerHarness.java:192) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:173) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:160) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: java.io.InvalidClassException: com.spotify.scio.values.SCollection$$anon$3; local class incompatible: stream classdesc serialVersionUID = 1458661216598417823, local class serialVersionUID = -3081382441803323297 at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:621) at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623) at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) at com.google.cloud.dataflow.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:73) ... 14 more
```

From `Serializable` doc:

```
If a serializable class does not explicitly declare a serialVersionUID, then the serialization runtime will calculate a default serialVersionUID value for that class based on various aspects of the class, as described in the Java(TM) Object Serialization Specification. However, it is strongly recommended that all serializable classes explicitly declare serialVersionUID values, since the default serialVersionUID computation is highly sensitive to class details that may vary depending on compiler implementations, and can thus result in unexpected InvalidClassExceptions during deserialization. Therefore, to guarantee a consistent serialVersionUID value across different java compiler implementations, a serializable class must declare an explicit serialVersionUID value. It is also strongly advised that explicit serialVersionUID declarations use the private modifier where possible, since such declarations apply only to the immediately declaring class--serialVersionUID fields are not useful as inherited members. Array classes cannot declare an explicit serialVersionUID, so they always have the default computed value, but the requirement for matching serialVersionUID values is waived for array classes.
```

We may have to add `serialVersionUID` or `@SerialVersionUID` in a bunch of places.

**Comment by ravwojdyla** [comment]
We could use `serialver` to get `serialVersionUID`, for example:

```
➜  scio git:(master) serialver -classpath scio-hdfs/target/scala-2.11/scio-hdfs-assembly-0.1.4-SNAPSHOT.jar 'com.google.cloud.dataflow.contrib.hadoop.HadoopUserUtils'
com.google.cloud.dataflow.contrib.hadoop.HadoopUserUtils:    private static final long serialVersionUID = -4820140022740077528L;
```

**Comment by ravwojdyla** [comment]
On the other hand:
 * dataflow sdk doc doesn't mention anything about `serialVersionUID`, especially for `DoFn`s
 * `Serializable` classes in dataflow sdk mostly do not specify `serialVersionUID`

The problem may come from the fact that I'm using oracle jvm locally to serialize, while dataflow service is most likely using openjdk - according to `Serializable` doc, `serialVersionUID` is sensitive on the compiler/jvm.

**Comment by ravwojdyla** [comment]
Will most likely add `serialVersionUID` to dataflow sdk, that should also fix issues also on our end.

**Comment by ravwojdyla** [comment]
More on `serialVersionUID` from [here](http://docs.oracle.com/javase/1.5.0/docs/guide/serialization/spec/class.html#4100):

```
Each versioned class must identify the original class version for which it is capable of writing streams and from which it can read. For example, a versioned class must declare:

     private static final long serialVersionUID = 3487495895819393L;
The stream-unique identifier is a 64-bit hash of the class name, interface class names, methods, and fields. The value must be declared in all versions of a class except the first. It may be declared in the original class but is not required. The value is fixed for all compatible classes. If the SUID is not declared for a class, the value defaults to the hash for that class. The serialVersionUIDs for dynamic proxy classes and enum types always have the value 0L.
```

**Comment by ravwojdyla** [comment]
Not sure if we want to do anything about this issue?

**Comment by ravwojdyla** [comment]
Since this issue nobody reported anything similar. Will close for now, if this comes back, we might need to investigate again.
