### ISSUE TITLE
RuntimeValue templates doesn't work

### ISSUE THREAD

**Issue by dgouyette** [spotify/scio#695]
I try to provide a RuntimeValue to my job

```
trait WordCountOptions  extends PipelineOptions {
  def getInput: ValueProvider[String]
  def setInput(value: ValueProvider[String]): Unit
}
```

I made a really simple code to reproduce the error 

```
    val options = PipelineOptionsFactory.fromArgs(cmdlineArgs: _*).withValidation().as[WordCountOptions](classOf[WordCountOptions])
    PipelineOptionsFactory.register(classOf[WordCountOptions])

    val (sc, args) = ContextAndArgs(cmdlineArgs)
    val pipeline: Pipeline = sc.pipeline

    if (options.getInput.isAccessible) {

      sc.parallelize(List(options.getInput.get()))
        .map(_.toUpperCase)
      val result = sc.close().waitUntilFinish()
      println(result.allCounters)
    } else {

      pipeline.run()
      sc.close()
    }
```

When i want to launch the template with a google function like 

```
const google = require('googleapis');
const jobs = {};
exports.triggerDataflow = function (event, callback) {
    const file = event.data;
    console.log("file", "name=" + file.name, "metageneration=" + file.metageneration, file.metageneration === 1);
    if (file.resourceState === 'exists' && file.name) {
        google.auth.getApplicationDefault(function (err, authClient, projectId) {
            if (err) {
                console.error(err);
                throw err;
            }
            if (authClient.createScopedRequired && authClient.createScopedRequired()) {
                authClient = authClient.createScoped([
                    'https://www.googleapis.com/auth/cloud-platform',
                    'https://www.googleapis.com/auth/userinfo.email'
                ]);
            }
            const dataflow = google.dataflow({
                version: 'v1b3',
                auth: authClient
            });
            let parameters = {
                projectId: "fcmsstaging",
                resource: {
                    parameters: {
                        input: `gs://${file.bucket}/${file.name}`
                    },
                    jobName: "Wordcount",
                    gcsPath: "gs://mybucket/WordcountTemplate"
                }
            };
            console.log(parameters);
            dataflow.projects.templates.create(parameters, function (err, response) {
                if (err) {
                    console.error("problem running dataflow template, error was: ", err);
                }
                console.log("Dataflow template response: ", response);
                callback();

            });
        });
    }else {
        console.log("file.resourceState="+ file.resourceState, "file.name="+file.name)
    }
};
```

I got the error 

```
 textPayload:  "problem running dataflow template, error was:  { Error: (65aa8d8c253b7aa3): The workflow could not be created. Causes: (65aa8d8c253b75f4): Found unexpected parameters: ['input' (perhaps you meant 'runner')]
    at Request._callback (/user_code/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/user_code/node_modules/googleapis/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/user_code/node_modules/googleapis/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/user_code/node_modules/googleapis/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
  code: 400,
  errors: 
   [ { message: '(65aa8d8c253b7aa3): The workflow could not be created. Causes: (65aa8d8c253b75f4): Found unexpected parameters: [\'input\' (perhaps you meant \'runner\')]',
       domain: 'global',
       reason: 'badRequest' } ] }"   
```

I previously ask the question on Stackoverflow here https://stackoverflow.com/questions/44628467/inconsistent-behavior-on-the-functioning-of-the-dataflow-templates 

It's seem it due to scio (works with apache beam and java sdk.

I tried scio 0.3.2 and scio 0.4.0-alpha1
Same error.

Here a repo which reproduce the error.

https://github.com/dgouyette/scioTemplateParameterIssue

**Comment by ravwojdyla** [comment]
@dgouyette there is a couple of issues here:
 * scio does not currently expose `ValueProvider` based APIs - we now have an issue open for this #696
 * afaiu your example - you are actually creating a template for an empty pipeline - that is because `options.getInput.isAccessible` is `false` at template creation time

A working - please double check example would be something like:

```
object WordCount {
  def main(cmdlineArgs: Array[String]): Unit = {
    val (sc, args) = ContextAndArgs(cmdlineArgs)
    sc.customInput("input", TextIO.read().from(sc.optionsAs[WordCountOptions].getInput))
      .map(_.toUpperCase)
      .saveAsTextFile(args("output"))
    sc.close()
  }
}
```

I submitted PR to your repo so you can try it out - it's [here](https://github.com/dgouyette/scioTemplateParameterIssue/pull/1).
* to create template, I used:
```
run-main com.example.WordCount --runner=DataflowRunner --project=<project> --templateLocation=gs://<template-bucket>  --tempLocation=gs://<temp-location> --output=gs://<example-of-static-arg-output>
```
* to submit job:
```
gcloud beta dataflow jobs run rav-test --gcs-location=gs://<template-bucket> --parameters=input=gs://<runtime-value>
```

**Comment by dgouyette** [comment]
Thanks. It's works.  
But it'll be more difficult with the others components (BigTable, ElasticSearch, XmlIO)...

**Comment by ravwojdyla** [comment]
@dgouyette as long as the internal/beam IO supports `ValueProvider` you can just use `customInput` and for output `saveAsCustomOutput`. If beam IO doesn't support `ValueProvider`  then there isn't much you can do, except open an issue to beam (and/or handle it in your own logic).
