### ISSUE TITLE
KryoRegistrarLoader taking forever when running REPL from $HOME

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#733]
When running the 0.3.4 REPL locally, the process gets stuck with the following `jstack` trace. Looks like `KryoRegistrarLoader` is doing something stupid?

```scala
val classLoader = Thread.currentThread().getContextClassLoader
ClassPath.from(classLoader).getAllClasses.asScala.toSeq
  .filter(_.getName.endsWith("KryoRegistrar"))
```

```
2017-07-19 22:52:51
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode):

"Attach Listener" #49 daemon prio=9 os_prio=31 tid=0x00007ff86a08c000 nid=0x5507 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"pool-3-thread-4" #41 prio=5 os_prio=31 tid=0x00007ff869232800 nid=0x1207 runnable [0x00007000078e8000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.list(Native Method)
	at java.io.File.list(File.java:1122)
	at java.io.File.listFiles(File.java:1207)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:486)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:495)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanDirectory(ClassPath.java:481)
	at com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:360)
	at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:345)
	at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:332)
	at com.google.common.reflect.ClassPath.from(ClassPath.java:97)
	at com.spotify.scio.coders.KryoRegistrarLoader$.<init>(KryoAtomicCoder.scala:53)
	at com.spotify.scio.coders.KryoRegistrarLoader$.<clinit>(KryoAtomicCoder.scala)
	at com.spotify.scio.coders.KryoAtomicCoder$$anon$1.initialValue(KryoAtomicCoder.scala:98)
	at com.spotify.scio.coders.KryoAtomicCoder$$anon$1.initialValue(KryoAtomicCoder.scala:75)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.spotify.scio.coders.KryoAtomicCoder.encode(KryoAtomicCoder.scala:110)
	at org.apache.beam.sdk.util.CoderUtils.encodeToSafeStream(CoderUtils.java:122)
	at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:106)
	at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:91)
	at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.<init>(MutationDetectors.java:106)
	at org.apache.beam.sdk.util.MutationDetectors.forValueWithCoder(MutationDetectors.java:44)
	at org.apache.beam.runners.direct.ImmutabilityCheckingBundleFactory$ImmutabilityEnforcingBundle.add(ImmutabilityCheckingBundleFactory.java:113)
	at org.apache.beam.runners.direct.ParDoEvaluator$BundleOutputManager.output(ParDoEvaluator.java:198)
	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnContext.outputWindowedValue(SimpleDoFnRunner.java:351)
	at org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:545)
	at com.spotify.scio.util.Functions$$anon$8.processElement(Functions.scala:145)
	at com.spotify.scio.util.Functions$$anon$8$auxiliary$VAwknRO2.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:198)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:159)
	at org.apache.beam.runners.core.PushbackSideInputDoFnRunner.processElement(PushbackSideInputDoFnRunner.java:111)
	at org.apache.beam.runners.core.PushbackSideInputDoFnRunner.processElementInReadyWindows(PushbackSideInputDoFnRunner.java:77)
	at org.apache.beam.runners.direct.ParDoEvaluator.processElement(ParDoEvaluator.java:134)
	at org.apache.beam.runners.direct.DoFnLifecycleManagerRemovingTransformEvaluator.processElement(DoFnLifecycleManagerRemovingTransformEvaluator.java:51)
	at org.apache.beam.runners.direct.TransformExecutor.processElements(TransformExecutor.java:139)
	at org.apache.beam.runners.direct.TransformExecutor.run(TransformExecutor.java:107)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-3-thread-3" #40 prio=5 os_prio=31 tid=0x00007ff86939b800 nid=0x100f waiting on condition [0x00007000077e9000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c64618c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-3-thread-2" #39 prio=5 os_prio=31 tid=0x00007ff868bdd000 nid=0x5153 runnable [0x00007000076e6000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c64618c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"sciorepl$ExecutorServiceParallelExecutor-monitor" #38 prio=5 os_prio=31 tid=0x00007ff8688b3800 nid=0x4d13 runnable [0x0000700006688000]
   java.lang.Thread.State: RUNNABLE
	at java.util.AbstractList.hashCode(AbstractList.java:540)
	at org.apache.beam.sdk.transforms.AutoValue_AppliedPTransform.hashCode(AutoValue_AppliedPTransform.java:106)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
	at org.apache.beam.runners.direct.WatermarkManager.getWatermarks(WatermarkManager.java:859)
	at org.apache.beam.runners.direct.EvaluationContext.fireAvailableCallbacks(EvaluationContext.java:231)
	at org.apache.beam.runners.direct.EvaluationContext.fireAllAvailableCallbacks(EvaluationContext.java:226)
	at org.apache.beam.runners.direct.EvaluationContext.forceRefresh(EvaluationContext.java:389)
	at org.apache.beam.runners.direct.EvaluationContext.extractFiredTimers(EvaluationContext.java:399)
	at org.apache.beam.runners.direct.ExecutorServiceParallelExecutor$MonitorRunnable.fireTimers(ExecutorServiceParallelExecutor.java:451)
	at org.apache.beam.runners.direct.ExecutorServiceParallelExecutor$MonitorRunnable.run(ExecutorServiceParallelExecutor.java:394)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"NonBlockingInputStreamThread" #12 daemon prio=5 os_prio=31 tid=0x00007ff8653ce000 nid=0x4f03 in Object.wait() [0x00007000075e3000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c000f450> (a jline.internal.NonBlockingInputStream)
	at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
	- locked <0x00000006c000f450> (a jline.internal.NonBlockingInputStream)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007ff864803000 nid=0x4903 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007ff86407d800 nid=0x4703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007ff86407c800 nid=0x4503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007ff86407b000 nid=0x4303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007ff86408d000 nid=0x4103 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007ff86403d000 nid=0x3103 in Object.wait() [0x0000700006ea3000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0026dd8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c0026dd8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007ff86403a800 nid=0x2f03 in Object.wait() [0x0000700006da0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0026ff8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000006c0026ff8> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=31 tid=0x00007ff864003000 nid=0x1c03 waiting on condition [0x000070000678c000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c6540780> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at org.apache.beam.runners.direct.ExecutorServiceParallelExecutor.awaitCompletion(ExecutorServiceParallelExecutor.java:241)
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:444)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:350)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:71)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:210)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:363)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:355)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:382)
	at com.spotify.scio.repl.ReplScioContext.requireNotClosed(ReplScioContext.scala:40)
	at com.spotify.scio.ScioContext.close(ScioContext.scala:355)
	at com.spotify.scio.repl.ReplScioContext.close(ReplScioContext.scala:33)
	at com.spotify.scio.repl.package$ReplSCollection.closeAndCollect(package.scala:32)
	at $line13.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<init>(<console>:28)
	at $line13.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<clinit>(<console>)
	at $line13.$eval$.$print$lzycompute(<console>:7)
	- locked <0x00000006c5b1b0a8> (a $line13.$eval$)
	at $line13.$eval$.$print(<console>:6)
	at $line13.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:819)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:691)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:425)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:993)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
	at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:891)
	at com.spotify.scio.repl.BaseScioShell$class.process(ScioShell.scala:97)
	at com.spotify.scio.repl.ScioShell$.process(ScioShell.scala:111)
	at com.spotify.scio.repl.BaseScioShell$class.main(ScioShell.scala:104)
	at com.spotify.scio.repl.ScioShell$.main(ScioShell.scala:111)
	at com.spotify.scio.repl.ScioShell.main(ScioShell.scala)

"VM Thread" os_prio=31 tid=0x00007ff864036000 nid=0x2d03 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007ff86400d000 nid=0x2503 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007ff86400d800 nid=0x2703 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007ff86400e000 nid=0x2903 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007ff86400f000 nid=0x2b03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007ff864047800 nid=0x4b03 waiting on condition 

JNI global references: 398
```

**Comment by nevillelyh** [comment]
Turns out it works fine when running in a local directory instead of `$HOME`. `ClassLoader` must be scanning all my class files.

**Comment by ravwojdyla** [comment]
CWD is the default classpath, so if you start scio-repl in `$HOME`, your `$HOME` is in the classpath thus `KryoRegistrarLoader` will scan your whole `$HOME` looking for possible serializers.

So seems like working as intended.

**Comment by nevillelyh** [comment]
It can be confusing for new users trying scio out in `$HOME` though. Wonder if there's a way to work around this?

**Comment by ravwojdyla** [comment]
@nevillelyh one way workaround this - could be to hardcoded classpath to the scio-repl jar. so in scio-repl script we could instead of using `-jar` do:

```
CLASSPATH=<scio-repl> java com.spotify.scio.repl.ScioShell
```

this would force classpath.

**Comment by ravwojdyla** [comment]
@nevillelyh this is one possible work around: spotify/homebrew-public/pull/14

**Comment by nevillelyh** [comment]
https://github.com/spotify/homebrew-public/pull/15 fixed it.
