### ISSUE TITLE
Avro serialization issue in 0.4.0-beta2

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#755]
Reported by @Tomczik76
cc @samschlegel
Could be related to 0fb8e3c5c4065ce800551deedd6a31b9474fdd7b

```
java.lang.ClassCastException: org.apache.avro.generic.GenericData$Record cannot be cast to org.apache.avro.specific.SpecificRecordBase
at com.spotify.scio.coders.SpecificAvroSerializer.read(AvroSerializer.scala:70)
at com.spotify.scio.coders.SpecificAvroSerializer.read(AvroSerializer.scala:56)
```

**Comment by nevillelyh** [comment]
False alarm. Turns out the Avro Java class was generated by an older version of the compiler.
