### ISSUE TITLE
IndexOutOfBoundsException on pubsubTopicWithAttributes in repl

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#768]
For:

```
sc.parallelize(Seq(("<>", Map("<>" -> "<>"))))
  .saveAsPubsubWithAttributes("<>")
sc.close()
```

and

```
sc.pubsubTopicWithAttributes("<>")
  .debug()
sc.close()
```

I get:

```
scio> sc.close()
[run-main-0] WARN org.apache.beam.sdk.io.gcp.pubsub.PubsubUnboundedSource - Created subscription <> to topic NestedValueProvider{value=NestedValueProvider{value=StaticValueProvider{value=<>}}}. Note this subscription WILL NOT be deleted when the pipeline terminates
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.IndexOutOfBoundsException: Index: 47, Size: 0
  at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:322)
  at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:292)
  at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:200)
  at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:63)
  at org.apache.beam.sdk.Pipeline.run(Pipeline.java:295)
  at org.apache.beam.sdk.Pipeline.run(Pipeline.java:281)
  at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:365)
  at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:357)
  at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:384)
  at com.spotify.scio.repl.ReplScioContext.requireNotClosed(ReplScioContext.scala:40)
  at com.spotify.scio.ScioContext.close(ScioContext.scala:357)
  at com.spotify.scio.repl.ReplScioContext.close(ReplScioContext.scala:33)
  ... 44 elided
Caused by: java.lang.IndexOutOfBoundsException: Index: 47, Size: 0
  at java.util.ArrayList.rangeCheck(ArrayList.java:653)
  at java.util.ArrayList.get(ArrayList.java:429)
  at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)
  at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:857)
  at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:811)
  at com.spotify.scio.coders.KryoAtomicCoder.decode(KryoAtomicCoder.scala:123)
  at org.apache.beam.sdk.coders.Coder.decode(Coder.java:160)
  at org.apache.beam.sdk.util.CoderUtils.decodeFromSafeStream(CoderUtils.java:130)
  at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:113)
  at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:107)
  at com.spotify.scio.ScioContext$$anonfun$pubsubInWithAttributes$1$$anonfun$apply$7.apply(ScioContext.scala:705)
  at com.spotify.scio.ScioContext$$anonfun$pubsubInWithAttributes$1$$anonfun$apply$7.apply(ScioContext.scala:704)
  at com.spotify.scio.util.Functions$$anon$8.processElement(Functions.scala:145)
```

**Comment by ravwojdyla** [comment]
Invalid - sorry. Closing.
