### ISSUE TITLE
Any allowed lateness fires empty windows and makes the reducers bug in scio

### ISSUE THREAD

**Issue by Igosuki** [spotify/scio#778]
I put the gist here https://gist.github.com/Igosuki/6a79e8b8a182dd1eb64a4bf255308061

Stacktrace : 
```
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.util.NoSuchElementException: None.get
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:322)
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:292)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:200)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:63)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:295)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:281)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:365)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:357)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:384)
	at com.spotify.scio.ScioContext.close(ScioContext.scala:357)
	at LateReduceExample $.main(LateReduceExample.scala:46)
	at LateReduceExample.main(BugExample.scala)
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at com.spotify.scio.util.Functions$ReduceFn.extractOutput(Functions.scala:172)
	at com.spotify.scio.util.Functions$ReduceFn.extractOutput(Functions.scala:158)
	at org.apache.beam.sdk.transforms.Combine$CombineFn.apply(Combine.java:400)
	at org.apache.beam.sdk.transforms.Combine$GroupedValues$1.processElement(Combine.java:2153)

```

Basically, there are no reduceOptions for JListWrappers which is the type of V when empty panes are fired by Beam.
Code that triggers the error is : 
```
override def extractOutput(accumulator: JList[T]): T = reduceOption(accumulator.asScala).get
```
In com.spotify.scio.util.Functions

Is this the expected behavior ?

In order to make it work on my production job I don't allow lateness for now.

**Comment by nevillelyh** [comment]
Good catch. Seems that the behavior is not deterministic though. The example sometimes completes successfully. Is that the case on your side?

I'll look into a fix for this.

**Comment by nevillelyh** [comment]
Actually not sure if this is fixable under the current architecture. The "official" `BinaryCombineFn` just returns `null` by default in the empty case which will cause a `Coder` NPE.

https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Combine.java#L444

And the int/long cases just suggests that something like `0` to be used.
https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Combine.java#L593

So it feels like what we really need is a `Monoid[T]` in this case. Alternatively you can also do `.aggregateByKey(0)(_ + _, _ + _)` to workaround the issue.

I can't think of a way to fix `reduceByKey` under the conditions that Beam uses `CombineFn`. Any suggestions?

**Comment by nevillelyh** [comment]
I was gonna suggest `foldByKey[T: Monoid]` but realized that it doesn't default to zero either. Fixed in 410b5927093fbaa0534bd242c805f590c3216abc

**Comment by nevillelyh** [comment]
@Igosuki did you get a chance to try it out? Don't think there's much I can do in the API layer w.r.t. `reduceByKey` behavior.

**Comment by nevillelyh** [comment]
Gonna close this since there isn't much we can do.

**Comment by Igosuki** [comment]
@nevillelyh Sorry, I've been too busy on other things. I switched to a bounded pipeline so I didn't get the chance to fix it.

**Comment by calonso** [comment]
Hi everyone! We're affected by the very same issue as described here and could successfully work around it by using the suggested `aggregateByKey`. Thanks @nevillelyh!

On the other hand I was thinking that a reasonable "fix" for this issue could be to modify the `reduceByKey` method to receive a `zeroValue`. What do you think?
