### ISSUE TITLE
Issue in TF record coders

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#815]
There seems to be some kind of issue with TF record coders, there has been a couple of reports of issues with coder discovery, and I myself saw random failures like:

```
[info]   java.lang.IllegalArgumentException: requirement failed: Invalid masked CRC32 of length
[info]   at scala.Predef$.require(Predef.scala:277)
[info]   at com.spotify.scio.io.TFRecordCodec$.read(TFRecordCodec.scala:45)
```

or

```
Caused by: java.util.zip.ZipException: invalid stored block lengths
INFO:     at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
INFO:     at org.apache.commons.compress.compressors.deflate.DeflateCompressorInputStream.read(DeflateCompressorInputStream.java:69)
INFO:     at com.spotify.scio.io.TFRecordCodec$.readFully(TFRecord.scala:221)
INFO:     at com.spotify.scio.io.TFRecordCodec$.read(TFRecord.scala:197)
INFO:     at com.spotify.scio.io.TFRecordReader.readNextRecord(TFRecord.scala:103)
```

**Comment by nevillelyh** [comment]
Is there any reproducible data?

**Comment by ravwojdyla** [comment]
@nevillelyh `com.spotify.scio.io.TFTapTest` sporadically fails:

```
> testOnly com.spotify.scio.io.TFTapTest
[info] Compiling 1 Scala source to /Users/rav/projects/scio/scio-tensorflow/target/scala-2.12/test-classes...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] TFTapTest:
[info] SCollection
[info] - should support saveAsTFRecordFile
[info] - should support saveAsTfExampleFile with case class or Seq feature spec *** FAILED ***
[info]   java.lang.IllegalArgumentException: requirement failed: Invalid masked CRC32 of length
[info]   at scala.Predef$.require(Predef.scala:277)
[info]   at com.spotify.scio.io.TFRecordCodec$.read(TFRecordCodec.scala:45)
[info]   at com.spotify.scio.io.TFFileStorageFunctions$$anon$1.<init>(TFFileStorageFunctions.scala:33)
[info]   at com.spotify.scio.io.TFFileStorageFunctions.tfRecordFile(TFFileStorageFunctions.scala:29)
[info]   at com.spotify.scio.io.TFRecordFileTap.value(TFRecordFileTap.scala:26)
[info]   at com.spotify.scio.io.Tap$$anon$1.value(Tap.scala:56)
[info]   at com.spotify.scio.io.TapSpec.verifyTap(TapTest.scala:43)
[info]   at com.spotify.scio.io.TapSpec.verifyTap$(TapTest.scala:41)
[info]   at com.spotify.scio.io.TFTapTest.verifyTap(TFTapTest.scala:28)
[info]   at com.spotify.scio.io.TFTapTest$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$3.apply(TFTapTest.scala:78)
[info]   ...
[info] - should support saveAsTfExampleFile with SCollection based feature spec
[info] - should throw on multiple feature specifications
```

**Comment by nevillelyh** [comment]
This is happening more frequently now. We should prioritize it? @ravwojdyla any clue what could've caused it? Maybe @regadas can help?

**Comment by nevillelyh** [comment]
Looks like in the failed cases, we got 2 tfrecords part files, one 100 bytes and one 0 bytes, while for the successful case both files are 50 bytes.

**Comment by guidj** [comment]
I had these randomly failing for today

```

2018-02-09 18:31:55.755672: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-09 18:31:55.755718: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-02-09 18:31:55.755725: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-09 18:31:55.755731: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
[info] TensorflowSpec:
[info] Tensorflow
[info] - should work for hello-wold
[info] - should work for serde model
[info] - should allow to predict
[info] - should allow to predict with 2 inputs
[info] TFTapTest:
[info] SCollection
[info] - should support saveAsTFRecordFile
[info] - should support saveAsTfExampleFile with case class or Seq feature spec *** FAILED ***
[info]   java.lang.IllegalArgumentException: requirement failed: Invalid masked CRC32 of length
[info]   at scala.Predef$.require(Predef.scala:277)
[info]   at com.spotify.scio.tensorflow.TFRecordCodec$.read(TFRecordCodec.scala:45)
[info]   at com.spotify.scio.tensorflow.TFFileStorageFunctions$$anon$1.<init>(TFFileStorageFunctions.scala:33)
[info]   at com.spotify.scio.tensorflow.TFFileStorageFunctions.tfRecordFile(TFFileStorageFunctions.scala:29)
[info]   at com.spotify.scio.tensorflow.TFRecordFileTap.value(TFRecordFileTap.scala:26)
[info]   at com.spotify.scio.io.Tap$$anon$1.value(Tap.scala:56)
[info]   at com.spotify.scio.io.TapSpec.verifyTap(TapTest.scala:43)
[info]   at com.spotify.scio.io.TapSpec.verifyTap$(TapTest.scala:41)
[info]   at com.spotify.scio.tensorflow.TFTapTest.verifyTap(TFTapTest.scala:29)
[info]   at com.spotify.scio.tensorflow.TFTapTest$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$3.apply(TFTapTest.scala:75)
[info]   ...
[info] - should support saveAsTfExampleFile with SCollection based feature spec *** FAILED ***
[info]   java.lang.IllegalArgumentException: requirement failed: Invalid masked CRC32 of length
[info]   at scala.Predef$.require(Predef.scala:277)
[info]   at com.spotify.scio.tensorflow.TFRecordCodec$.read(TFRecordCodec.scala:45)
[info]   at com.spotify.scio.tensorflow.TFFileStorageFunctions$$anon$1.<init>(TFFileStorageFunctions.scala:33)
[info]   at com.spotify.scio.tensorflow.TFFileStorageFunctions.tfRecordFile(TFFileStorageFunctions.scala:29)
[info]   at com.spotify.scio.tensorflow.TFRecordFileTap.value(TFRecordFileTap.scala:26)
[info]   at com.spotify.scio.io.Tap$$anon$1.value(Tap.scala:56)
[info]   at com.spotify.scio.io.TapSpec.verifyTap(TapTest.scala:43)
[info]   at com.spotify.scio.io.TapSpec.verifyTap$(TapTest.scala:41)
[info]   at com.spotify.scio.tensorflow.TFTapTest.verifyTap(TFTapTest.scala:29)
[info]   at com.spotify.scio.tensorflow.TFTapTest$$anonfun$3$$anonfun$apply$mcV$sp$3.apply(TFTapTest.scala:94)

```
