### ISSUE TITLE
scio-repl crashes after upgrading to 0.4.3

### ISSUE THREAD

**Issue by raynux** [spotify/scio#885]
Hi, I upgraded from 0.4.2 to 0.4.3 using homebrew, then `scio-repl` is no longer working. Also `java -jar scio-repl-0.4.3.jar` and `java -jar scio-repl-0.4.2.jar` fail, too. The error output at the bottom.

To make sure, I have completely uninstalled-then-installed homebrew, then `brew tap spotify/public; brew install sbt scio scala`, but still getting the same error.

Here's my High Sierra env
```
# java -version                                                                                                            
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

# echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
```
and `sbt console` seems working fine.

The error message here.
```
# scio-repl
Welcome to
                 _____
    ________________(_)_____
    __  ___/  ___/_  /_  __ \
    _(__  )/ /__ _  / / /_/ /
    /____/ \___/ /_/  \____/   version 0.4.3

Using Scala version 2.11.11 (Java HotSpot(TM) 64-Bit Server VM, Java 9)

Type in expressions to have them evaluated.
Type :help for more information.
      

Failed to initialize compiler: object java.lang.Object in compiler mirror not found.
** Note that as of 2.8 scala does not assume use of the java classpath.
** For the old behavior pass -usejavacp to scala, or if using a Settings
** object programmatically, settings.usejavacp.value = true.
Exception in thread "main" java.lang.NullPointerException
	at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:256)
	at scala.tools.nsc.interpreter.IMain$Request.x$20$lzycompute(IMain.scala:903)
	at scala.tools.nsc.interpreter.IMain$Request.x$20(IMain.scala:902)
	at scala.tools.nsc.interpreter.IMain$Request.headerPreamble$lzycompute(IMain.scala:902)
	at scala.tools.nsc.interpreter.IMain$Request.headerPreamble(IMain.scala:902)
	at scala.tools.nsc.interpreter.IMain$Request$Wrapper.preamble(IMain.scala:925)
	at scala.tools.nsc.interpreter.IMain$CodeAssembler$$anonfun$apply$23.apply(IMain.scala:1344)
	at scala.tools.nsc.interpreter.IMain$CodeAssembler$$anonfun$apply$23.apply(IMain.scala:1343)
	at scala.tools.nsc.util.package$.stringFromWriter(package.scala:64)
	at scala.tools.nsc.interpreter.IMain$CodeAssembler$class.apply(IMain.scala:1343)
	at scala.tools.nsc.interpreter.IMain$Request$Wrapper.apply(IMain.scala:915)
	at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:1009)
	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:1004)
	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:586)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:574)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.spotify.scio.repl.ScioILoop.com$spotify$scio$repl$ScioILoop$$addImports(ScioILoop.scala:198)
	at com.spotify.scio.repl.ScioILoop$$anonfun$createInterpreter$1.apply(ScioILoop.scala:243)
	at com.spotify.scio.repl.ScioILoop$$anonfun$createInterpreter$1.apply(ScioILoop.scala:242)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:221)
	at com.spotify.scio.repl.ScioILoop.createInterpreter(ScioILoop.scala:242)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$startup$1$1$$anonfun$apply$1.apply(ILoop.scala:971)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$startup$1$1$$anonfun$apply$1.apply(ILoop.scala:971)
	at scala.tools.nsc.interpreter.ILoop.savingReader(ILoop.scala:96)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$startup$1$1.apply(ILoop.scala:970)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:990)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
	at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:891)
	at com.spotify.scio.repl.BaseScioShell$class.process(ScioShell.scala:97)
	at com.spotify.scio.repl.ScioShell$.process(ScioShell.scala:111)
	at com.spotify.scio.repl.BaseScioShell$class.main(ScioShell.scala:104)
	at com.spotify.scio.repl.ScioShell$.main(ScioShell.scala:111)
	at com.spotify.scio.repl.ScioShell.main(ScioShell.scala)

Exception in thread "Thread-1" java.lang.InterruptedException
	at java.base/java.util.concurrent.SynchronousQueue.put(SynchronousQueue.java:875)
	at scala.tools.nsc.interpreter.SplashLoop.run(InteractiveReader.scala:77)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Help wanted!

**Comment by ravwojdyla** [comment]
@raynux hi. looks like an issue with java 9. we currently have not test java 9, in fact we have already heard a couple of problems around serialization etc. anyway for now the workaround would be to use java 8.

**Comment by raynux** [comment]
@ravwojdyla The error disappeared after switching to JAVA8. Thanks a lot!
