### ISSUE TITLE
Investigate if we need to port apache/flink#323

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio#915]
https://issues.apache.org/jira/browse/FLINK-1391
https://github.com/apache/flink/pull/323

otherwise kryo might get confused:

```
Caused by: java.lang.NullPointerException
    at org.apache.avro.generic.GenericData$Array.add(GenericData.java:277)
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
    at com.twitter.chill.Tuple2Serializer.read(TupleSerializers.scala:42)
    at com.twitter.chill.Tuple2Serializer.read(TupleSerializers.scala:33)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
    at com.spotify.scio.coders.KryoAtomicCoder.decode(KryoAtomicCoder.scala:121)
    at org.apache.beam.sdk.coders.Coder.decode(Coder.java:160)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromSafeStream(CoderUtils.java:130)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:113)
    at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:107)
    at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.<init>(MutationDetectors.java:107)
```

**Comment by andrewsmartin** [comment]
An array field was added to the test avro records in 2d82ec0, so this is now exercised in tests. Gonna close this as a no-op.
