### ISSUE TITLE
saveAsCassandra processing lull

### ISSUE THREAD

**Issue by sajacy** [spotify/scio#923]
I'm load testing a streaming topology that writes to Cassandra (and BigTable).

I will run these topologies for several days, and in a couple instances, I have seen errors in the Cassandra AbstractBulkRecordWriter that prevents the job from producing more outputs.  The job seems to be ~processing inputs~ suffering backpressure but otherwise without errors, and will not write to outputs, and system lag climbs linearly with the distance in time since the error occurs.

Maybe related (or not), running on fewer+bigger machine types seems to cause this error to happen more frequently (under the same load)

```
{
 insertId:  "4786808025042736477:991699:0:525677267"  
 jsonPayload: {
  job:  "2017-11-09_15_57_13-9587156077920131142"   
  logger:  "com.google.cloud.dataflow.worker.DataflowOperationContext"   
  message:  "Processing lull for PT8400.054S in state process of saveAsCassandra@{redacted.scala:172}13
  at sun.misc.Unsafe.park(Native Method)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:390)
  at org.apache.cassandra.hadoop.AbstractBulkRecordWriter.close(AbstractBulkRecordWriter.java:127)
  at org.apache.cassandra.hadoop.AbstractBulkRecordWriter.close(AbstractBulkRecordWriter.java:107)
  at com.spotify.scio.cassandra.BulkOperations$$anonfun$11.apply(BulkOperations.scala:109)
  at com.spotify.scio.cassandra.BulkOperations$$anonfun$11.apply(BulkOperations.scala:106)
  at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:145)
  at com.spotify.scio.util.Functions$$anon$7$DoFnInvoker.invokeProcessElement(Unknown Source)
"   
  step:  "saveAsCassandra@{Redacted.scala:172}13"   
  thread:  "36"   
  work:  "<nil>"   
  worker:  "redacted-11091557-1ee2-harness-r6f6"   
 }
 labels: {
  compute.googleapis.com/resource_id:  "4786808025042736477"   
  compute.googleapis.com/resource_name:  "redacted-11091557-1ee2-harness-r6f6"   
  compute.googleapis.com/resource_type:  "instance"   
  dataflow.googleapis.com/job_id:  "2017-11-09_15_57_13-9587156077920131142"   
  dataflow.googleapis.com/job_name:  "redacted-1109235652-8b5f0be"   
  dataflow.googleapis.com/region:  "us-central1"   
 }
 logName:  "projects/redacted/logs/dataflow.googleapis.com%2Fworker"  
 receiveTimestamp:  "2017-11-10T12:32:21.097400332Z"  
 resource: {
  labels: {
   job_id:  "2017-11-09_15_57_13-9587156077920131142"    
   job_name:  "redacted-1109235652-8b5f0be"    
   project_id:  "redacted"    
   region:  "us-central1"    
   step_id:  "saveAsCassandra@{Redacted.scala:172}13"    
  }
  type:  "dataflow_step"   
 }
 severity:  "WARNING"  
 timestamp:  "2017-11-10T12:32:16.646Z"  
}
```

There are several stack traces with the same message, but seem to indicate same root cause:
```
{
 insertId:  "4786808025042736477:991699:0:525678271"  
 jsonPayload: {
  job:  "2017-11-09_15_57_13-9587156077920131142"   
  logger:  "com.google.cloud.dataflow.worker.DataflowOperationContext"   
  message:  "Processing lull for PT8400.117S in state process of saveAsCassandra@{Redacted.scala:172}13
  at org.apache.cassandra.hadoop.AbstractBulkRecordWriter.close(AbstractBulkRecordWriter.java:127)
  at org.apache.cassandra.hadoop.AbstractBulkRecordWriter.close(AbstractBulkRecordWriter.java:107)
  at com.spotify.scio.cassandra.BulkOperations$$anonfun$11.apply(BulkOperations.scala:109)
  at com.spotify.scio.cassandra.BulkOperations$$anonfun$11.apply(BulkOperations.scala:106)
  at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:145)
  at com.spotify.scio.util.Functions$$anon$7$DoFnInvoker.invokeProcessElement(Unknown Source)
"
...
```

and 

```
{
 insertId:  "4786808025042736477:991699:0:525679760"  
 jsonPayload: {
  job:  "2017-11-09_15_57_13-9587156077920131142"   
  logger:  "com.google.cloud.dataflow.worker.DataflowOperationContext"   
  message:  "Processing lull for PT8400.117S in state process of saveAsCassandra@{Redacted.scala:172}13
  at java.lang.Throwable.fillInStackTrace(Native Method)
  at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
  at java.lang.Throwable.<init>(Throwable.java:310)
  at java.lang.Exception.<init>(Exception.java:102)
  at java.util.concurrent.ExecutionException.<init>(ExecutionException.java:90)
  at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
  at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:377)
  at org.apache.cassandra.hadoop.AbstractBulkRecordWriter.close(AbstractBulkRecordWriter.java:127)
  at org.apache.cassandra.hadoop.AbstractBulkRecordWriter.close(AbstractBulkRecordWriter.java:107)
  at com.spotify.scio.cassandra.BulkOperations$$anonfun$11.apply(BulkOperations.scala:109)
  at com.spotify.scio.cassandra.BulkOperations$$anonfun$11.apply(BulkOperations.scala:106)
  at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:145)
  at com.spotify.scio.util.Functions$$anon$7$DoFnInvoker.invokeProcessElement(Unknown Source)
" 
...
```

code snippet is:

```
    // window the input
    val windowed = sc.fromPubsub[Redacted]()
      .withFixedWindows(Duration.millis(windowDurationMs /* 5 mins */), options = windowOpts)

    windowed
      .withName("Construct CQL")
      .flatMap { case (userId, t, p) =>
        constructTCQL(userId, t) ++ constructPCQL(userId, p)
      }
      // tuples are (userid,featurekey,featurevalue), all strings
      .saveAsCassandra(casOpts)({ case (x, y, z) => List(x, y, z) })
```

where windowOptions is:
```
  def windowOptions(args: Args): WindowOptions = {
    val maxSkewMs = args.long("maxSkewMs", 2 * 60 * 1000) // 2 minutes
    val maxPaneSize = args.int("maxPaneSize", 10000) // 10k elements
    WindowOptions(
      allowedLateness = Duration.millis(maxSkewMs),
      trigger = AfterWatermark.pastEndOfWindow()
        .withEarlyFirings(AfterPane.elementCountAtLeast(maxPaneSize))
        .withLateFirings(AfterPane.elementCountAtLeast(maxPaneSize)),
      accumulationMode = AccumulationMode.DISCARDING_FIRED_PANES
    )
  }
```

**Comment by sajacy** [comment]
Added windowing configuration for more context.

**Comment by nevillelyh** [comment]
Is this still affecting you? More info? Does it affect streaming only or batch also?

**Comment by sajacy** [comment]
Still unresolved, and doesn't seem to affect batch, but  we've stopped development on this.  Feel free to close.

**Comment by jto** [comment]
It seems that "Processing lull..." are not actually errors but simply debug information output when an IO takes too long (more than 5 minutes) to execute. Could it simply be that you reached the maximum writes allowed by you Cassandra cluster ?

Sources:
- https://lists.apache.org/thread.html/324a4f86e567e3e1692466e70f44a08276123b467bacb2ecbf00515f@%3Cuser.beam.apache.org%3E
- https://stackoverflow.com/questions/48503565/dataflow-job-halts-with-processing-lull#comment84059150_48503565

**Comment by nevillelyh** [comment]
Gonna close this since Cassandra bulk writer has a lot of mutable global states that's hard to manage in streaming mode. We documented this and now only recommend this sink for high-throughput batch use cases.
https://github.com/spotify/scio/commit/eb9ef7f937ad89007bc7ada90ad210cbb3689e34
