### ISSUE TITLE
future returned from saveAsElasticsearch - examples outdated?

### ISSUE THREAD

**Issue by elonybear** [spotify/scio#969]
Running a pipeline through GCP that builds an Elasticsearch index. I'd like to do write some output to GCS once the index has been completed. Typical `saveAs` functions return a future which can be waited on. However, waiting on the future returned by `saveAsElasticsearch` throws this error:

```
INFO: Exception in thread "main" java.util.concurrent.ExecutionException: Boxed Error
INFO: 	at scala.concurrent.impl.Promise$.resolver(Promise.scala:59)
INFO: 	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:51)
INFO: 	at scala.concurrent.impl.Promise$KeptPromise.<init>(Promise.scala:328)
INFO: 	at scala.concurrent.Promise$.fromTry(Promise.scala:142)
INFO: 	at scala.concurrent.Promise$.failed(Promise.scala:128)
INFO: 	at scala.concurrent.Future$.failed(Future.scala:469)
INFO: 	at com.spotify.scio.elasticsearch.package$ElasticsearchSCollection$.saveAsElasticsearch$extension(package.scala:85)
INFO: 	at com.spotify.data.publindex_testing.ElasticsearchClient$.writeToElasticsearch(ElasticsearchClient.scala:66)
INFO: 	at com.spotify.data.publindex_testing.BuildESIndexJob$.buildIndex(BuildESIndexJob.scala:184)
INFO: 	at com.spotify.data.publindex_testing.BuildESIndexJob$.pipeline(BuildESIndexJob.scala:143)
INFO: 	at com.spotify.data.publindex_testing.BuildESIndexJob$.main(BuildESIndexJob.scala:119)
INFO: 	at com.spotify.data.publindex_testing.BuildESIndexJob.main(BuildESIndexJob.scala)
INFO: Caused by: scala.NotImplementedError: Custom future not implemented
INFO: 	... 6 more
```

Then I noticed that in each of the `saveAs` functions, it returns `Future.Failed` by default. However, I'm following the scio examples in waiting for the result after doing my `saveAsElasticsearch` operation. Is this a discrepancy in the examples?

**Comment by nevillelyh** [comment]
It's not implemented because ES is not an immutable storage and this is the intended behavior. Please wait on `ScioResult#finalResult` instead.
