### ISSUE TITLE
Credential exception in Travis build

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#98]
During REPL integration test.

https://travis-ci.org/spotify/scio/jobs/124600968

```
java.lang.RuntimeException: Unable to get application default credentials. Please see https://developers.google.com/accounts/docs/application-default-credentials for details on how to specify credentials. This version of the SDK is dependent on the gcloud core component version 2015.02.05 or newer to be able to get credentials from the currently authorized user via gcloud auth.
	at com.google.cloud.dataflow.sdk.util.Credentials.getCredential(Credentials.java:123)
	at com.google.cloud.dataflow.sdk.util.GcpCredentialFactory.getCredential(GcpCredentialFactory.java:43)
	at com.google.cloud.dataflow.sdk.options.GcpOptions$GcpUserCredentialsFactory.create(GcpOptions.java:263)
	at com.google.cloud.dataflow.sdk.options.GcpOptions$GcpUserCredentialsFactory.create(GcpOptions.java:253)
	at com.google.cloud.dataflow.sdk.options.ProxyInvocationHandler.getDefault(ProxyInvocationHandler.java:290)
	at com.google.cloud.dataflow.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:129)
	at com.sun.proxy.$Proxy47.getGcpCredential(Unknown Source)
	at com.google.cloud.dataflow.sdk.util.Transport.newStorageClient(Transport.java:182)
	at com.google.cloud.dataflow.sdk.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:78)
	at com.spotify.scio.repl.IoCommands.<init>(IoCommands.scala:47)
	at .<init>(<console>:22)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at com.spotify.scio.repl.ScioILoop.com$spotify$scio$repl$ScioILoop$$loadIoCommands(ScioILoop.scala:232)
	at com.spotify.scio.repl.ScioILoop$$anonfun$createInterpreter$1.apply(ScioILoop.scala:246)
	at com.spotify.scio.repl.ScioILoop$$anonfun$createInterpreter$1.apply(ScioILoop.scala:242)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:232)
	at com.spotify.scio.repl.ScioILoop.createInterpreter(ScioILoop.scala:242)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:839)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
	at com.spotify.scio.repl.BaseScioShell$class.process(ScioShell.scala:70)
	at com.spotify.scio.repl.ScioShell$.process(ScioShell.scala:82)
	at com.spotify.scio.repl.BaseScioShell$class.main(ScioShell.scala:75)
	at com.spotify.scio.repl.ScioShell$.main(ScioShell.scala:82)
	at com.spotify.scio.repl.ScioShell.main(ScioShell.scala)
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
	at com.google.api.client.googleapis.auth.oauth2.DefaultCredentialProvider.getDefaultCredential(DefaultCredentialProvider.java:95)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.getApplicationDefault(GoogleCredential.java:213)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.getApplicationDefault(GoogleCredential.java:191)
	at com.google.cloud.dataflow.sdk.util.Credentials.getCredential(Credentials.java:121)
	... 38 more
```

**Comment by nevillelyh** [comment]
Fixed in #100
