### ISSUE TITLE
Examples throw ClassNotFoundException without fork in run

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#981]
https://github.com/sbt/sbt/issues/3736

Adding `fork in run := true` fixes it but introduces other annoyance, e.g. stdout treated as error and relative path `README.md` in word count quick start not working.

```
[error] Caused by: java.lang.ClassNotFoundException: scala.Function0
[error]         at sbt.internal.inc.classpath.ClasspathFilter.loadClass(ClassLoaders.scala:74)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at java.lang.Class.forName0(Native Method)
[error]         at java.lang.Class.forName(Class.java:348)
[error]         at com.twitter.chill.KryoBase$$anonfun$1.apply(KryoBase.scala:41)
[error]         at com.twitter.chill.KryoBase$$anonfun$1.apply(KryoBase.scala:41)
```

**Comment by ravwojdyla** [comment]
Should be fixed by https://github.com/sbt/zinc/pull/473
