### ISSUE TITLE
[beam-master] IllegalMutationException in LibSVMTest

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#997]
`[info] libSVMCollection
[info] - should parse libsvm files *** FAILED ***
[info]   org.apache.beam.sdk.util.IllegalMutationException: PTransform PAssert$5/RunChecks/ParMultiDo(GroupedValuesChecker) illegaly mutated value [(0.0,SparseVector(34)((0,1.0), (8,1.0), (18,1.0), (20,1.0), (23,1.0), (33,1.0))), (0.0,SparseVector(34)((0,1.0), (8,1.0), (19,1.0), (20,1.0), (23,1.0), (33,1.0))), (1.0,SparseVector(34)((2,1.0), (8,1.0), (18,1.0), (20,1.0), (29,1.0), (33,1.0)))] of class class java.util.ArrayList. Input values must not be mutated in any way.
[info]   at org.apache.beam.runners.direct.ImmutabilityEnforcementFactory$ImmutabilityCheckingEnforcement.verifyUnmodified(ImmutabilityEnforcementFactory.java:95)
[info]   at org.apache.beam.runners.direct.ImmutabilityEnforcementFactory$ImmutabilityCheckingEnforcement.afterElement(ImmutabilityEnforcementFactory.java:70)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:171)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:125)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info]   ...
[info] - should parse libsvm files with length *** FAILED ***
[info]   org.apache.beam.sdk.util.IllegalMutationException: PTransform PAssert$18/RunChecks/ParMultiDo(GroupedValuesChecker) illegaly mutated value [(1.0,SparseVector(34)((2,1.0), (8,1.0), (18,1.0), (20,1.0), (29,1.0), (33,1.0))), (0.0,SparseVector(34)((0,1.0), (8,1.0), (19,1.0), (20,1.0), (23,1.0), (33,1.0))), (0.0,SparseVector(34)((0,1.0), (8,1.0), (18,1.0), (20,1.0), (23,1.0), (33,1.0)))] of class class java.util.ArrayList. Input values must not be mutated in any way.
[info]   at org.apache.beam.runners.direct.ImmutabilityEnforcementFactory$ImmutabilityCheckingEnforcement.verifyUnmodified(ImmutabilityEnforcementFactory.java:95)
[info]   at org.apache.beam.runners.direct.ImmutabilityEnforcementFactory$ImmutabilityCheckingEnforcement.afterElement(ImmutabilityEnforcementFactory.java:70)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:171)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:125)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
`

**Comment by nevillelyh** [comment]
Probably related to #996

**Comment by nevillelyh** [comment]
It's caused by the lack of `equals/hashCode` in Breeze `SparseArray`, fixed in 9f6c0d6387521e5396e8f651f1c8947468bf1542.
